vueuse/vueuse

packages/core/useWindowSize/index.test.ts, packages/core/useWindowSize/index.ts
Fixed `useWindowSize` not being reactive. I believe this mistake have sneaked during recent refactor.
Speaking of testing I couldn't come up with better option then spying on `window.addEventListener`. Let me know if you want that to be added to this PR.
```js
it('sets handler for window "resize" event', () => {
const windowAddEventListener = jest.spyOn(window, 'addEventListener');
renderHook(() => {
const { width, height } = useWindowSize(100, 200)
return { width, height }
})
expect(windowAddEventListener).toHaveBeenCalledWith('resize', expect.anything(), undefined)
})
```
=> Fixed useWindowSize not being reactive

packages/core/useTransition/index.md, packages/core/useTransition/index.stories.tsx, packages/core/useTransition/index.ts, packages/utils/index.ts
The other day I needed to get a bit fancier with state transitions, this PR allows for custom functions to be provided instead of just cubic bezier curves. I didn't add any presets, but now we're free to specify weird transitions like these 😅 
[![easings](https://user-images.githubusercontent.com/7980426/82950647-7f4f5500-9f5a-11ea-80bf-8f66a4e1c0ae.png)](https://easings.net/#easeInOutElastic)
=> Add support for custom transition functions

packages/core/useElementVisibility/index.ts
When using template refs, we can run into type errors. This PR makes `useElementVisibility` more tolerant of falsy initial values.
```vue
<template>
<div ref="root" />
</template>
<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api'
import { useElementVisibility } from '@vueuse/core'
export default defineComponent({
setup() {
const root = ref<Element>()
const isVisible = useElementVisibility(root) // Argument of type 'Ref<Element | undefined>' is not assignable to parameter of type 'Ref<Element>'
return { isVisible }
}
})
</script>
```
=> improve useElementVisibility typing

packages/core/useIntersectionObserver/index.md, packages/core/useIntersectionObserver/index.stories.tsx, packages/core/useIntersectionObserver/index.ts
新增 IntersectionObserver Hook
用于检测 【目标元素】 于 【根元素】 内是否曝光
用途：图片懒加载、商品曝光率检测
=> feat: add useIntersectionObserver

rollup.config.js, tsconfig.rollup.json
1. Change usage of `rollup-plugin-typescript2` opts.tsconfigOverride
2. Remove unnecessary `tsconfig.rollup.json`
=> fix: rollup typescript config overwrite

packages/core/asyncComputed/index.md, packages/core/asyncComputed/index.stories.tsx, packages/core/asyncComputed/index.ts
Okay, this took me quite a while. Mostly due to Storybook — I had to locally downgrade PostCSS to v7 because of an incompatibility between PostCSS 8 and Tailwind — but also due to tests. I haven't added any of those, even though I would've loved to, but I'd need refs for tests and `vue-demi` smacks me with "No vue dependency found" errors. Ideas?
(Resolves #128)
=> feat: add asyncComputed

packages/core/useRefHistory/index.md, packages/core/useRefHistory/index.stories.tsx, packages/core/useRefHistory/index.test.ts, packages/core/useRefHistory/index.ts
Changed limit to capacity, history to prev and redoHistory to next, as discussed in point 2 of https://github.com/antfu/vueuse/issues/137
```
<button @click="undo()" :disabled='!prev.length'>Undo</button>
<button @click="redo()" :disabled='!next.length'>Redo</button>
=> refactor!: API changes in useRefHistory (capacity, prev, next)

packages/core/useRefHistory/index.md, packages/core/useRefHistory/index.test.ts, packages/core/useRefHistory/index.ts
close #137 
Changed `next` and `prev` to `undoStack` and `redoStack`, also providing an alias `history`
=> refactor!: useRefHistory api improves

.gitpod.yml, README.md, docs/Contributing.md
Hi. I work for Gitpod(an online IDE which is free for Open Source) and we are currently on a mission to simplify contributors onboarding experience for cool and popular Open Source projects by automating their dev setups this can be helpful for newcomers/beginners i.e the can start in just a single click without having to set anything up.
This Pr adds Gitpod config to the repo via which, anyone would be able to launch a workspace where it will automatically:
- clone the `VueUse` repo.
- install the dependencies.
- run `yarn dev` to start the server.
You can give it a try on my fork of the repo via the following link:
https://gitpod.io/#https://github.com/nisarhassan12/vueuse
This is how it looks:
=> Simplify code contributions via online automated dev setup.

packages/core/useWebWorkerFn/index.md, packages/core/useWebWorkerFn/index.stories.tsx, packages/core/useWebWorkerFn/index.ts
This is to allow use of the TypeScript compiler option --isolatedModules.
Fixes #172
=> refactor!(useWebWorkerFn): export WebWorkerStatus as type instead of enum

packages/core/onStartTyping/index.ts, packages/core/useBattery/index.ts, packages/core/useBrowserLocation/index.ts, packages/core/useClipboard/index.ts, packages/core/useDocumentVisibility/index.ts, packages/core/useEventListener/index.ts, packages/core/useEventSource/index.ts, packages/core/useIdle/index.ts, packages/core/useNetwork/index.ts, packages/core/usePermission/index.ts
should be more intuitive
from 
```ts
useEventListener('visibilitychange', handler, undefined, document)
```
to
```ts
useEventListener(document, 'visibilitychange', handler)
```
=> BREAKING CHANGE: refactor!(useEventListener): move custom event target argument to first

packages/core/useRefHistory/index.md, packages/core/useRefHistory/index.test.ts, packages/core/useRefHistory/index.ts
As discussed in https://github.com/antfu/vueuse/issues/181, this PR aligns useRefHistory with watch/watchEffect using flush: 'pre' as the default. As stated in the Vue docs, flush: 'sync' should only be used in rare cases. After our experience working with this composable, I think it is worth the effort to try to find a way to use 'pre'
In the current PR, there are new tests for the new default case, and the old tests are also working when using flush: 'sync'. I tried to follow the async pattern in other composable.
batch only makes sense when using 'sync'
Supported operations in sync when using 'pre'
undo, undo
undo, modify
modify, undo (but the modification is lost)
modify, commit, modify, commit, undo
undo, modify, commit
We could also directly define that undo/redo and other history …
=> BREAKING CHANGE: refactor!(useRefHistory): flush 'pre' as default for useRefHistory

packages/core/useRafFn/index.ts, packages/core/useTransition/index.test.ts
It looks like [in this commit](https://github.com/antfu/vueuse/commit/eda2fd4b7fb7072fd7bb56fbbe886114fec661fa#diff-80fba29722597fce2f73a9b693b85a627c4c4192a581f0af7cd3f3ce0e68ebdeL28-R28) the lifecycle binding was accidentally changed from `onUnmounted` to `onMounted`.
This caused [`useRafFn`](https://vueuse.js.org/?path=/story/animation--useraffn) to immediately stop it's animation loop, and had the cascading effect of breaking [`useTransition`](https://vueuse.js.org/?path=/story/animation--usetransition) which relies on that loop.
=> fix(useRafFn): incorrect lifecycle hook

.storybook/style.css
Links and headings and not clickable/selectable on https://vueuse.js.org/?path=/story/sensors--usewindowscroll due to absolute div. I believe this change doesn't have any side effect on other docs.
=> chore: add 'position: relative;' for markdown-body

packages/core/usePermission/index.stories.tsx
[usePermission](https://vueuse.js.org/?path=/story/browser--usepermission) document is broken due to this undefined variable.
First I was trying to implement that permission. Looks like it is renamed to 'speaker-selection' from 'speaker' on latest draft. That require me to polyfill types like how you did for clipboard permission. Then I realized no one of existing browsers support that permission. And probably that's why this variable was removed.
=> docs(usePermission): remove undefined variable

packages/core/useElementVisibility/index.ts, packages/core/useTransition/index.ts
Just a couple tweaks to help get my functions ready for the stable release.
- `useRafFn` has `start`/`stop` marked as deprecated, renamed functions to `resume`/`pause`
- adds jsdoc to `useTransition`
- adds jsdoc to `useElementVisibility`
- minor cleanups to `useTransition` to improve readability
=> chore: useTransition / useElementVisibility cleanup and jsdoc

packages/core/useWebWorkerFn/index.stories.tsx
Current worker demo has some issues.
Normal sort block UI only on first run. Result of `sortNumbers(numbers)` cached by browser because of numbers are the same.
Also worker sort is blocks UI because `data.slice(0, 10)` is still a heavy task.
So I extracted array generation, sorting and slicing into a single function for keep heavy task in one place.
I printed result on screen to make the demo more optimistic.
I removed spread operator and filled Array with undefined because of how [Babel bundles that code](https://github.com/babel/babel/issues/7332). It was failing because Babel's `_toConsumableArray` function was not available in **worker**.
=> docs(useWebWorkerFn): improve demo

.storybook/style.css, packages/core/useWindowScroll/index.stories.tsx
I had issues with that when I was working on a modal demo for an utility function I'm currently working on.
I fixed select/click problem by pushing absolute div to outside of view. Also moved it up to make the texts selectable on fixed div.
=> chore: remove relative

packages/core/useRefHistory/index.md
I [asked today in VueLand](https://discord.com/channels/325477692906536972/713147202188607558/778634528172015636) and at least there, they think that splice generating three flushes for a single operation is not a bug in Vue3 reactivity. For the moment, this PR adds a small note about this for useRefHistory
=> docs(useRefHistory): add warning about splice in flush sync

packages/core/useClipboard/index.ts
- fix(useClipboard): set clipboard text only if successful
仅在复制成功时更新剪贴板的内容（如果当前页面无焦点会抛异常 `Uncaught DOMException: Document is not focused.`）
=> fix(useClipboard): set clipboard text only if successful

packages/core/useGeolocation/index.stories.tsx
- docs(useGeolocation): fix outputted coords
`GeolocationCoordinates` 无法直接序列化为 JSON
=> docs(useGeolocation): fix outputted coords

packages/core/useManualRefHistory/index.test.ts, packages/core/useManualRefHistory/index.ts
I have been using `dump: JSON.stringify`, `parse: JSON.parse` so I did not think about this before. 
When the ref holds a big object and `dump: clone` is used, there could be a performant hit because of making the snapshots reactive (since they are added to the stacks refs)
This PR uses `markRaw` when creating new snapshots as an optimization. It affects both useManualRefHistory and useRefHistory. It is a breaking change but I do not think it could affect anyone (since nobody should be modifying the snapshots and watching for that changes). history, last, undoStack, redoStack remain reactive, users can watch them, but each snapshot is not tracked.
I thought about using `readonly`, but looks like it is not part of vue-demi. I also do not know if there is any perf hit by using readonly. For …
=> refactor(useManualRefHistory)!: optimization, snapshots are no longer reactive

packages/core/asyncComputed/index.test.ts
Some tests for `asyncComputed` that I used while checking https://github.com/antfu/vueuse/issues/248
The first two are modified versions of the ones included in https://github.com/antfu/vueuse/pull/247, checking that the callback is called immediately and not lazily.
=> test: add basic asyncComputed tests

packages/core/asyncComputed/index.test.ts, packages/core/asyncComputed/index.ts
=> feat: add lazy option to asyncComputed

packages/core/useManualRefHistory/index.md, packages/core/useManualRefHistory/index.test.ts, packages/core/useManualRefHistory/index.ts, packages/core/useRefHistory/index.md, packages/core/useRefHistory/index.test.ts, packages/core/useRefHistory/index.ts
When using `clone: true` (or `deep: true`) and undoing, the same reference in `last` was assigned to the source because the parse function was a bypass. If the user mutates the source, the history was also mutated.
This PR uses clone for parse in that case fixing the issue. It also allows the user to specify the clone function directly in the clone param, so there is no need to repeat it like `{ dump: clone, parse: clone }`. So the `clone` param is now a boolean | CloneFn
The clone param is now also exposed in useRefHistory. Having a shallow watch + clone is now also possible.
Also, awesome work with vue-demi-switch @antfu! :tada: 
=> fix(useRefHistory): cloning when undoing

packages/core/useElementVisibility/index.ts
use `tryOnMounted` to set the event listener otherwise the event will always be attached to the window since the scroll target probably isn't mounted yet.
=> fix(useElementVisibility): set the listener for scrollTarget on mounted and use Ref

.storybook/style.css, packages/core/useTransition/index.md, packages/core/useTransition/index.stories.tsx, packages/core/useTransition/index.test.ts, packages/core/useTransition/index.ts
This PR turns the `duration` property of `useTransition` from a `number` to a `MaybeRef<number>`. Duration changes have no effect on transitions already in progress, and only effect subsequent transitions. I also refactored the unit tests from relying on Jest's `done` to async / await. The nested `setTimeout` calls get difficult to read at even just a layer or two deep.
Also, congrats on tagging 4.x! Thank you for all your work building and maintaining such an awesome library!
=> feat(useTransition): support for reactive durations

packages/core/useVModel/index.ts
`emit ||` shouldn't be part of the ternary expression condition
=> fix(useVModel): TypeError: _emit is not a function

packages/.vitepress/theme/styles/code.css, packages/.vitepress/theme/styles/layout.css
1. style scrollbars for browsers that are not as nice as safari (maybe the non-hover color could be more prominent)
2. hide scrollbars in the code line highlight overlay (this is a bug in vitepress default theme)
3. there was a horizontal scrollbar in the body that I couldn't fix, but I think it is safe to just hide it.
=> chore: fix docs scrollbars

packages/index.md
=> chore: fix typo

packages/core/useIntersectionObserver/index.ts, packages/core/useResizeObserver/index.ts
Currently there is a bug where [useResizeObserver](https://vueuse.js.org/core/useresizeobserver/) and [useIntersectionObserver](https://vueuse.js.org/core/useintersectionobserver/) will only work on the initial page load but will break if navigating to the page from a different route.
This PR addresses this(also see issue #300) by adding `flush: 'post'` to the `watch` functions in the `useResizeObserver` and `useIntersectionObserver` which seems to be the correct way to handle accessing dom refs according to [the Vue 3 documentation on Effect Flush Timing](https://v3.vuejs.org/guide/reactivity-computed-watchers.html#effect-flush-timing)
=> fix: useResizeObserver and useIntersectionObserver only working on initial page loads

packages/.vitepress/utils.ts, packages/core/useMouseInElement/demo.vue
**Problem**
The [`useMouseInElement` demo](https://vueuse.js.org/core/useMouseInElement/) was not working due to two issues. The first issue was a simple typo: `tesxt` instead of `text`. 
The second problem was caused by the `stringify` function used by the docs. This function uses the `YAML.dump` function but this happens to throw an error in this demo due to that fact that the `useMouseInElement` function returns a `stop` function which `YMAL.dump` considers an invalid type. 
**Solution**
To solve this  I added the `skipInvalid: true` option which according to [the docs](https://github.com/nodeca/js-yaml#dump-object---options-) will not throw errors on invalid types
=> fix: bug in useMouseInElement demo causing the demo to not work

packages/core/useMediaQuery/demo.vue, packages/core/useMediaQuery/index.md
There currently exists a bug in the [`useMediaQuery` demo](https://vueuse.js.org/core/useMediaQuery/) that causes the demo to not work properly.
This pull request fixes the bug by changing the media query from `(min-width = 1024px)` to `(min-width: 1024px)` and `(prefers-color-scheme = dark)` to `(prefers-color-scheme: dark)`. It also fixes a typo in the `useMediaQuery` documentation that causes the link to the `Media Query` MDN documentation link to not work.
=> fix: bug in useMediaQuery demo causing demo to not work properly

indexes.json, packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.ts, packages/functions.md
BREAKING CHANGES:
- the `ws` option in the return of `useWebSocket` is not a ref instead of plain WebSocket instance
- `useWebSocket`'s `send` will now buffers data before the connection established instead of discarding sliently
- `useWebSocket`'s returned `state` is renamed to `status`
----
Continued from the work in #325 by @shuperry. Close #283.
> Note: This PR will be held until v4.2
=> feat(useWebSocket)!: rework useWebSocket

packages/firebase/useAuth/index.md, packages/firebase/useAuth/index.ts
This fixes an issue with the `useAuth` function where it would import more from firebase than needed causing warnings in the console. It also fixes a small type in the docs for `useAuth`
The console error looked like this
=> fix(useAuth): fix imports to use only needed SDK & fixed typo in docs

packages/integrations/useAxios/demo.vue, packages/integrations/useAxios/index.md, packages/integrations/useAxios/index.ts
Adds support for Axios instances as mentioned in issue #273. 
Uses the following overrides so that it works with the existing API without breaking it.
```ts
export function useAxios<T = any>(url: string, config?: AxiosRequestConfig): UseAxiosReturn<T>
export function useAxios<T = any>(url: string, instance?: AxiosInstance): UseAxiosReturn<T>
export function useAxios<T = any>(url: string, config: AxiosRequestConfig, instance: AxiosInstance): UseAxiosReturn<T>
```
=> feat(useAxios): axios instance support, close #273

packages/core/useUrlSearchParams/index.test.ts, packages/core/useUrlSearchParams/index.ts
Hey @antfu ,
unfortunately I discovered another bug in `useUrlSearchParams` 😢 Now the url params will not be removed in history mode anymore.
=> fix(useUrlSearchParams): wrong iterable empty check

packages/core/useAsyncState/index.md, packages/core/useFetch/demo.vue, packages/core/useFetch/index.md, packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts, packages/shared/utils/index.ts
Basic implementation of `createFetch` as mentioned in issue #352. Adds new test for the `createFetch` function.
I was also thinking it might be interesting to have some hooks on the `createFetch` object like `beforeRequest` and possibly `afterRequest`. These would return a promise which would allow one to do something like get an authorization token and attach it to the headers but the implementation of something like that might be a bit more difficult. So before doing anything like that I thought it would be better to discuss it.
Also I had to copy the function overloads to the `createFetch` function, if you have a better idea on how to do this let me know!
=> feat(useFetch): new feature createFetch, close #352

packages/shared/ignorableWatch/demo.vue
Currently `Clear Log` button first clears log and resets counter to `0` then logs it. To really clear the log we have to click again. I fixed it by setting `flush: sync`.
=> chore: clear demo log within sync

packages/core/useUrlSearchParams/index.test.ts, packages/core/useUrlSearchParams/index.ts
Hello @antfu,
unfortunately I found another issue in the `useUrlSearchParams` function 😭.
Kind regards,
Lukas
=> fix(useUrlSearchParams): wrong parsing of hash url without params

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
**Problem**
Noticed this as I was working on `beforeFetch` hooks for the useFetch function. Basically the problem is that we end up reassigning the `fetchOptions` when we run the first fetch after we attach the signal. The problem comes with the second fetch though. Since the `fetchOptions` object now already contains a signal, it will overwrite our new signal with the old one.
```ts
if (supportsAbort) {
controller = new AbortController()
fetchOptions = {
signal: controller.signal,
...fetchOptions,
}
}
```
**Solution**
I ended up just moving the signal below where we spread out our fetchOptions which will overwrite the old signal.
```ts
if (supportsAbort) {
controller = new AbortController()
fetchOptions = {
...fetchOptions,
signal: controller.signal,
}
}
```
=> fix(useFetch): abort controller would only works on first request

packages/firebase/useFirestore/index.test.ts, packages/firebase/useFirestore/index.ts
This PR fixes #365.
I modified the `isDocumentReference` which now checks the number of slash (`/`) occurences in the path:
* even -> collection
* odd -> document
=> fix(useFirestore): sub-collection is wrongly detected as a document

packages/core/useFetch/index.ts
Hey @antfu this is the initial implementation of the `beforeFetch` feature I had in mind for useFetch. It isn't too complicated. This adds a new option to the `useFetch` options called `beforeFetch`. This new options accepts a promise that returns the url and request options. The basic usage would be as follows
```ts
useFetch('/api/me', {
beforeFetch: async(url, options) => {
options.headers = {
...options.headers,
Authorization: `Bearer ${await getAuthToken()}`,
}
return {
url,
options,
}
},
})
```
Of course this option would also apply to the `createFetch` function, where it would be more likely to be used.
Let me know what you think about this API. If you like it I'll go ahead and write some tests and add docs, otherwise we can refactor 😄
=> feat(useFetch): add beforeFetch option

packages/core/useFetch/index.md, packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
Updated the docs for `useFetch` and added some tests for the new `beforeFetch` function. Also changed the possible return type for `beforeFetch` to include void so the following is possible
```ts
beforeFetch({ options, cancel }) {
if (someCondition)
cancel()
}
```
=> chore(useFetch): add tests and update docs for useFetch

CONTRIBUTING.md, packages/core/_template/index.md
This PR fixes some grammatical errors as well as informs the contributor that they don't need to update the `footer` section of the `index.md`(this part confused me the first time I added a function 😅)
=> chore: updated contributing guide

packages/core/useTransition/demo.vue, packages/core/useTransition/index.md, packages/core/useTransition/index.test.ts, packages/core/useTransition/index.ts, packages/shared/utils/is.ts
This is the first of several PRs to implement features being designed in #364
There is a small breaking change here. The returned value is now a `ComputedRef` instead of a `Ref`, meaning anyone who manually set the value of a transitioned ref would no longer be able to do so. This was never part of the documented API though, so I'm not sure how much to worry about it. I think just making a mention in the release notes would be sufficient.
Vectors support any number of dimensions, and there is a quick track/sled example added to the demo.
=> feat(useTransition): support for vectors

packages/core/useVModels/index.md
`emit` destructed but not passed to `useVModels`
=> docs(useVModels): fix typo

packages/integrations/useAxios/demo.vue, packages/integrations/useAxios/index.ts
Expressive way when requests is dispatch, loading is more idiomatic what finished, because every time you need to use them with states requests you need to translate to !finished.
=> feat(useAxios): new `loading` state in return object

packages/core/useTransition/index.md, packages/core/useTransition/index.spec.ts, packages/core/useTransition/index.ts, packages/shared/useTimeoutFn/index.spec.ts, packages/shared/useTimeoutFn/index.ts
Just a quick helper option to make delayed and staggered transitions easier. Also, I take back my claim before that `onStarted` was unnecessary. It definitely serves a useful purpose now! 😅 
More info here https://github.com/vueuse/vueuse/issues/364
This also includes a tiny change to `useTimeoutFn`, in that now it supports a `MaybeRef<number>` as the interval.
=> feat(useTransition): support for delayed transitions

packages/core/useSwipe/index.test.ts, packages/core/useSwipe/index.ts
`onSwipeEnd` should be called at the end of any swipe, as soon as the threshold was exceeded during the swipe. I also added a test case for this scenario. I introduced an additional enum value `NONE` for this case.
Closes #390
=> fix(useSwipe): exceed threshold in between

packages/integrations/useAxios/index.ts
sometimes we need to extend or use this interface and in my opnion don't be bad if we export that.
=> fix(useAxios): export UseAxiosReturn type

packages/core/useBreakpoints/index.md
The `useBreakpoints()` variables are called `breakpoints`, but the follow up lines of code mistakenly referred them as  `breakpointer` instead
=> docs(useBreakpoints): fix typo

packages/shared/debouncedWatch/index.ts, packages/shared/throttledWatch/index.ts, packages/shared/useDebounceFn/index.ts, packages/shared/useThrottleFn/index.ts, packages/shared/utils/filters.ts, packages/shared/utils/index.test.ts
Adds option to use `Ref<number>` for debounce and throttle filter along with functions that wrap those filters. Would resolve #409
=> feat(filters): use number/ref with debounce & throttle filters

packages/integrations/useAxios/index.ts
=> fix(useAxios): use shallowRef for resposne, data, and error

packages/shared/useDebounce/index.ts
This is to address the discussion in #407. From what I understand the goal was just to change the return type to a readonly, correct? Wasn't really clear if any of the other changes discussed in there should be implemented, if they should let me know
closes #407
=> fix(useDebounce): make return type readonly, close #407

README.md, indexes.json, packages/add-ons.md, packages/integrations/README.md, packages/integrations/index.ts, packages/integrations/package.json, packages/integrations/useFocusTrap/demo.vue, packages/integrations/useFocusTrap/index.md, packages/integrations/useFocusTrap/index.ts, yarn.lock
Implementation of `useFocusTrap` function as discussed in #420.
Closes #420
=> feat(useFocusTrap): new function

package.json, packages/.vitepress/config.js, packages/.vitepress/theme/components/DarkModeSwitch.vue, packages/.vitepress/theme/components/NavBar.vue
This just fixes some accessibility issues and adds the theme colors to the head since lighthouse was warning about it.
Also noticed lighthouse complaining about the service worker
=> docs: fix accessibility issues. Add serve docs command & theme color to head

packages/core/useMouseInElement/index.md
Template used `ref="target"` but the setup function used `const el`.
=> docs: fix missing ref from target

packages/firebase/useFirestore/index.ts
=> fix(useFirestore): optional Chaining on isDocumentReference

README.md, indexes.json, packages/core/autoResetRef/demo.vue, packages/core/autoResetRef/index.md, packages/core/autoResetRef/index.test.ts, packages/core/autoResetRef/index.ts, packages/core/index.ts, packages/functions.md
This PR is the implementation of #432.
closes #432
=> feat(autoResetRef): new function

packages/core/useAsyncState/demo.vue, packages/core/useAsyncState/index.ts
Implements the suggestion in https://github.com/vueuse/vueuse/issues/480. I added it as an option in order to avoid breaking existing code.
In addition, the delay option was not working (`!delay` is false when delay is non-zero). This PR fixes it as well.
=> fix(useAsyncState): fix delay and option for disabling state reset

packages/core/useVModel/index.md, packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts
Hi everyone,
I've tried to solve the problem described in #402 by adding an additional options param. In addition I added tests for checking the `emit` calls.
Closes #402
=> feat(useVModel): eventName option

packages/integrations/useAxios/index.ts
See #449 for more deatils.
Initial attempt to bring the useAxios API more inline with the useFetch API. This PR doesn't include the execute() option that was mentioned in #449, as we would probably need another config option to enable something like that. It would probably be best to avoid too many overrides as we already have 3. Let me know if you guys have a good idea on how you'd like to implement something like that.
=> feat(useAxios): bring API into line with useFetch

packages/shared/createEventHook/index.md, packages/shared/createEventHook/index.test.ts, packages/shared/createEventHook/index.ts
=> feat(createEventHook): new function

packages/core/useMediaControls/index.ts
=> fix(useMediaControls): Doesn't rewrite default media properties

packages/core/useFetch/index.md, packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
Adds support for `afterFetch` in `useFetch`. Closes #456
Also uses the new `createEventHook` to add event hooks for `onFetchResponse` and `onFetchError`
=> feat(useFetch): add afterFetch option, onFetchResponse, and onFetchError

packages/core/useWebWorker/index.ts
=> feat(useWebWoker): return worker

packages/core/useMediaControls/index.ts
@wheatjs 
https://github.com/vueuse/vueuse/blob/87a464dbfc2bd489eb412a022df4b4b425b0bd43/packages/core/useMediaControls/index.ts#L468
The listener of `error` events on the media element mostly does not make sense.
`Error` never will be triggered on `<video>` or `<audio>` with `<source>` tag inside. This will be triggered directly on the `<source>` tag whose resource could not be loaded. And this event will not pop up. Check console in [simple demo](https://codepen.io/cawa-93/pen/wvJMZdK?editors=1010).
=> fix: Change `onMediaError` to `onSourceError`

packages/core/onClickOutside/demo.vue, packages/core/onClickOutside/index.ts
default to just pointerDown and add option to include more events. Closes #451
=> feat(onClickOutside): default to just pointerDown 

packages/core/onClickOutside/index.ts
`tryOnUnmounted(stop)` has been called inside `useEventListener` 
https://github.com/vueuse/vueuse/blob/6423bf88c3ec49bc6b6fe66412d44349872be5b8/packages/core/useEventListener/index.ts#L117-L124
=> fix(onClickOutside): duplicate code

packages/core/useDark/index.ts, packages/core/useLocalStorage/index.ts, packages/core/useSessionStorage/index.ts, packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
Closes #525 
This PR adds a new option for `useStorage`: `serializer` which allows custom serializer.
=> feat(useStorage): allow custom serializer

packages/core/useMediaControls/demo.vue, packages/core/useMediaControls/index.md, packages/core/useMediaControls/index.ts
If you change the volume or muted values by native controls (or in devtools) it does not effect reactive variables. [Here is a demonstration](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHVzZU1lZGlhQ29udHJvbHMgfSBmcm9tICdAdnVldXNlL2NvcmUnXG4gIFxuY29uc3Qgb3JpZ2luU291cmNlID0gJ2h0dHBzOi8vaW50ZXJhY3RpdmUtZXhhbXBsZXMubWRuLm1vemlsbGEubmV0L21lZGlhL2NjMC12aWRlb3MvZmxvd2VyLndlYm0nXG5jb25zdCBzcmMgPSByZWYob3JpZ2luU291cmNlKVxuXG5jb25zdCBtdXRlZCA9IHJlZihmYWxzZSlcbmNvbnN0IHZpZGVvRWxlbWVudCA9IHJlZigpXG5jb25zdCB7cGxheWluZywgdm9sdW1lfSA9IHVzZU1lZGlhQ29udHJvbHModmlkZW9FbGVtZW50LCB7XG4gIGF1dG9wbGF5OiBmYWxzZSwgLy8gPC0tXG4gIGNvbnRyb2xzOiB0cnVlLCBcbiAgcHJlbG9hZDogJ21ldGFkYXRhJyxcbiAgc3JjLFxuICBtdXRlZFxufSlcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGR …
=> refactor(useMediaControls): Deprecate options that can simply be set as attributes

packages/guidelines.md
Here is an initial draft for the guidelines. Let me know if you guys have any suggestions or corrections.
@antfu @cawa-93
=> docs(guidlines): added guidelines

packages/core/useMediaControls/index.md
I added little example for `useMediaControls` docs:
```js
const { playing, currentTime, duration, volume } = useMediaControls(video, { 
src: 'video.mp4',
})
// Change initial media properties
onMounted(() => {
volume.value = 0.5
currentTime.value = 60
})
```
At first glance, it may seem that to change the initial state, it is enough to simply change the value without wrapping in the mount hook:
```js
const { playing, currentTime, duration, volume } = useMediaControls(video, { 
src: 'video.mp4',
})
// Change initial media properties
volume.value = 0.5
currentTime.value = 60
```
But in reality it will not lead to the desired result because at the `setup` time target media element may not yet exist
https://github.com/vueuse/vueuse/blob/52c7a04cdacc5ac2601e51f1fe500a215d7cea15/packages/core/us …
=> docs(useMediaControls): Add example for changing initial media state

packages/rxjs/useObservable/index.md, packages/rxjs/useObservable/index.ts
Adds a few feature to allow users to configure error handling if they so choose. Without this feature, any error from the source observable would be treated as "unhandled" by RxJS, and thrown in a new call stack.
Resolves #566
=> feat(useObservable): now supports optional error handling via `onError`.

packages/core/useFetch/index.ts
~~fixes #553~~
fixes #526
While not yet clear what path we should take in order to have access to the response body when the status code is not `ok` I propose this PR.
=> fix(useFetch): parse body even if status is not ok

packages/core/useFetch/index.ts
fixes #539 
fixes #542
In this PR only `json` is handled as content type.
This is an alternative to #549
=> feat(useFetch): set content type only if it is json

packages/core/useMouse/index.md, packages/core/useMouse/index.ts
This PR makes it easy to create fluid drag and drop user experiences with `useMouse`.
- Uses the `dragover` event to continue to track mouse position while dragging.
I've enabled support for `dragover` by default.  I thought about putting it behind a `drag` option but chose not to.  I can't think of a use case where this would break somebody's app all because mouse position is now tracked during drag and drop.
=> feat: useMouse supports drag and drop

packages/core/useMousePressed/demo.vue, packages/core/useMousePressed/index.ts
This is an initial attempt at drag and drop support for isMousePressed.  I realized that I don't really need this since I can use the PR I made to `useMouse`.  I'm only making the PR to see if somebody thinks the feature is worth supporting and wants to do a few minutes of cleanup.  Here's the cleanup I think this might need:
If nobody is interested in carrying on this work, please close as it's not my intention to waste anybody's time.  🙏
=> feat(useMousePressed): support drag and drop

packages/core/useWindowFocus/demo.vue
I couldn't test the demo code with the vitepress dev command and that caused me to include a bug which reverted the shown state.
Not sure how I could've tested that demo page properly, I _did_ run the `build` script alongside the `dev` script but that didn't work and I couldn't test it.
Maybe there should be additional steps in the contributing.md
=> fix(useWindowFocus): revert example

packages/core/onKeyStroke/index.md
In docs was "keyUp" and in types "export declare type KeyStrokeEventName = "keydown" | "keypress" | "keyup""
=> docs: eventName "keyUp" in onKeyStroke docs

packages/core/useDark/demo.vue
This pull request fixes the `useDark` demo.
This incorrect usage causes the `MouseEvent` to be passed over to `toggleDark`, which in the [current implementation](https://github.com/vueuse/vueuse/blob/main/packages/core/useDark/index.ts#L96) results in never being able to switch back from dark mode (when system is not dark).
```js
// v is a MouseEvent
store.value = v ? 'dark' : 'light'
```
The bug can be replicated in the current [VueUse website](https://vueuse.org/).
https://user-images.githubusercontent.com/1158253/124516414-f4c16200-ddb7-11eb-853b-c109586d8144.mp4
It might be desirable to log a warning or throw an error if an `Event` is passed to the setter in `useDark`, as it's very likely a mistake, and can cause the bug in the video.
=> fix: useDark demo

packages/core/useFetch/index.ts
fixes #611 
Since `useFetch` is a reactive function it should resolve always. The error is saved in the reactive variables.
=> fix(useFetch): reject for `execute` on error

packages/core/usePointerSwipe/index.ts
=> fix(usePointerSwipe): set capture on event target instead of root element

packages/.vitepress/theme/composables/editLink.ts
fix: after rename of default branch from `master` to `main`, edit links didn't work anymore. This change will **likely** fix that.
fixes #558
=> docs: edit links to main branch

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
Adds `onFetchFinally` which will run on both successful and error responses. 
Fix issue with headers as described in #625 
Closes #625 
Closes #628
=> fix: add onFetchFinally. Fix headers issue #625

packages/core/useSwipe/index.ts
`touchcancel` event is also needed.
> https://developer.mozilla.org/zh-CN/docs/Web/API/Element/touchcancel_event
For example, when you swipe, you get a phone call.
=> fix(useSwipe): add touchcancel callback

packages/integrations/useQRCode/index.md
https://vueuse.org/integrations/useQRCode/
Alt text was included in [the source code of demo](https://github.com/vueuse/vueuse/blob/cb303d462e67925e040c6a499be5193d58ac1adb/packages/integrations/useQRCode/demo.vue#L17), but not in [the documentation](https://github.com/vueuse/vueuse/blob/cb303d462e67925e040c6a499be5193d58ac1adb/packages/integrations/useQRCode/index.md), so I added it.
=> chore(useQRCode): add alt text for Docs

packages/guide/config.md, packages/shared/whenever/index.md, packages/shared/whenever/index.test.ts, packages/shared/whenever/index.ts
Change
---
- resolve #660 
- Use `WatchCallback` type instead of  void `Fn` type
- Remove constraints `<T = Boolean>` in type parameter
- Adjust document
Discussion
---
- Have notice this composable function is only meant to used by simple Boolean ref. However I found this function extremely useful to deal with possible undefined watch update, which doesn't need to be Boolean at all. Am I using it wrong?
- Not sure whether to add type parameter on `WatchCallback`
- Not sure if the test is meaningless in current test case
- Have tried to add a demo about ignoring falsy value, but it seems to be misleading people the purpose of this function
**Demo.vue**
```vue
import { whenever } from '.'
import { ref } from 'vue-demi'
const number = ref(0)
const watchRes = ref('') …
```
=> feat(whenever): callback arguments

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
5.2.0
when setting the request method  and return type, you need to focus on the invoking sequence and can't invoking it more than once, which I don't think its flexible or easy to use.
https://codesandbox.io/s/boring-nobel-tq0m5?file=/src/App.vue
=> refactor(types): useFetch return type

packages/firebase/useAuth/index.md
Just fixed a small typo in the doc for `@vueuse/firebase > useAuth`
Cheers !
=> docs(useAuth): fix typo on usage section

packages/router/useRouteQuery/index.ts
link https://forum.vuejs.org/t/how-to-remove-one-query-string-from-url/39176/3
```ts
query.value = 'share'
// http://localhost:8080/timeline?mode=share
query.value = null
// http://localhost:8080/timeline?mode
query.value = undefined 
// http://localhost:8080/timeline
```
=> types(useRouteQuery): add `undefined` for remove key in query

packages/shared/tryOnScopeDispose/index.md, packages/shared/tryOnScopeDispose/index.ts
The document correctly specified that this works in effect scope, and
does nothing if not. Change the comment in code to be the same as in the
document.
=> docs(tryOnScopeDispose): align code comment to document

packages/shared/useTimeoutFn/index.md, packages/shared/useTimeoutFn/index.ts
The immediate option makes the timer starts immediately after calling
the function, but the current document is worded like the callback
function is called immediately without timeout. Fix the document.
=> docs(useTimeoutFn): clarify the meaning of immediate

packages/shared/utils/filters.ts
In throttledFilter, it does not modify lastExec variable.
So events can occur multiple times, ignoring duration.
Fixes #689
=> fix: bug in throttleFilter

packages/core/onClickOutside/index.md
Closes #699 
I included both TS and JS versions on the [gist](https://gist.github.com/sibbng/13e83b1dd1b733317ce0130ef07d4efd).
=> docs: note onClickOutside usage on IE11

packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.ts
Added support for an optional array parameter called protocols. This second parameter to the WebSocket constructor contains one or more protocol strings to use e.g. subprotocols. If not provided, internally the parameter always defaults to an empty array (`[]`), so that was chosen as parameter initializer. More information can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket).
=> feat(useWebSocket): Added support for optional protocols

packages/components/package.json, packages/core/package.json, packages/electron/package.json, packages/firebase/package.json, packages/integrations/package.json, packages/router/package.json, packages/rxjs/package.json, packages/shared/package.json, scripts/rollup.config.ts, scripts/utils.ts
This PR uses `.cjs` and `.mjs` file extensions for proper support within a Node module context.
Without it the following errors are generated when importing within a Vite server build:
```
import { isClient, isString, noop, tryOnScopeDispose, promiseTimeout, increaseWithUnit, useTimeoutFn, watchWithFilter, tryOnMounted, createFilterWrapper, bypassFilter, createSingletonPromise, containsProp, createEventHook, throttleFilter, timestamp, isFunction, isObject, ignorableWatch, isNumber, useIntervalFn, pausableFilter, tryOnUnmounted, identity, clamp, pausableWatch } from '@vueuse/shared';
^^^^
SyntaxError: Named export 'noop' not found. The requested module '@vueuse/shared' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported …
```
=> build!: use `.mjs`/`.cjs` file extensions for node module context support

packages/shared/eagerComputed/index.md, packages/shared/eagerComputed/index.ts
From https://dev.to/linusborg/vue-when-a-computed-property-can-be-the-wrong-tool-195j
Thanks to @LinusBorg
=> feat(eagerComputed): new function

packages/shared/createSharedComposable/index.ts
Prevent Vue warnings if it is called outside of a component lifecycle.
=> fix(createSharedComposable): use tryOnScopeDispose instead of onScopeDispose

packages/core/useFetch/index.ts
Sometimes we need a default value to avoid waiting for async results
like this:
```js
<div>
<p>{{ res.value }}</p>
</div>
const {
data: res,
} = useFetch(url, { refetch, defaultData: { id: 2, value: 'test' } })
=> feat(useFetch): add defaultData option

packages/core/useAsyncState/demo.vue, packages/core/useAsyncState/index.ts
It would be cool to be able to pass params to promise from `execute` function 
```javascript
const { state, isReady, execute } = useAsyncState(
(args) => {
let id = args?.id || 1
return axios.get(`https://jsonplaceholder.typicode.com/todos/${id}`).then(t => t.data )
},
{},
{
delay: 2000,
resetOnExecute: false,
},
)
</script>
<template>
<div>
<note>Ready: {{ isReady.toString() }}</note>
<pre lang="json" class="ml-2">{{ YAML.dump(state) }}</pre>
<button @click="execute(2000, {id: 2})">
Execute
</button>
</div>
</template>
```
=> feat(useAsyncState): Provide params to callback function

packages/core/useUrlSearchParams/index.md
I see some problem in the `useUrlSearchParams` documentation.
=> fix(useUrlSearchParams): missing bracket on code example

packages/.vitepress/theme/styles/overrides.css
Just fixed the color-scheme for the scrollbars when in dark mode.
Before
After
=> fix: New theme color scheme

packages/core/useTimestamp/component.ts, packages/core/useTimestamp/index.test.ts, packages/core/useTimestamp/index.ts
Sometimes it is useful to create timestamps that don't start immediately. Currently, this can be achieved by calling `pause()` as soon as the timestamp is created, but I think exposing the underlying `immediate` option would be a slightly cleaner solution.
```vue
<template>
<button @click="resume">{{ timestamp }}</button>
</template>
<script setup>
import { useTimestamp } from '@vueuse/core'
const { timestamp, resume } = useTimestamp({
controls: true,
immediate: false,
})
</script>
```
The default behavior remains unchanged, and I've added a test to verify this. Let me know if there is anything else is needed for this PR. And if we'd rather not expand the `useTimestamp` options, no worries, feel free to just close my PR.
=> feat(useTimestamp): expose immediate option

packages/integrations/package.json
```bash
error when starting dev server:
Error: Build failed with 1 error:
node_modules/@vueuse/integrations/index.mjs:3:54: error: Could not resolve "@vueuse/shared" (mark it as external to exclude it from the bundle)
```
=> fix: Could not resolve "@vueuse/shared"

packages/integrations/useFuse/index.md
I added some additional wording to the `useFuse` documentation because when I searched the docs for "fuzzy", "search", or "searching" nothing came up.
I'd never heard of fuse.js and nearly implemented my own composable on top of https://github.com/bevacqua/fuzzysearch! 😅
=> docs(useFuse): add "fuzzy search" language to useFuse

packages/core/useEventBus/index.md
I was reading the usage of eventBus with typescript and catch this little mistake, i belive.
=> chore: typo

packages/core/useWebWorker/index.ts
fix #932 
Needed to explicitly define the return interface so that `post` can pick up the TS 4.4 or TS 4.5 version
In addition I made it possible to provide a generic `Data` that is default to `any` => no breaking change
=> fix(useWebWorker): explicit define return interface

packages/shared/useCounter/index.md, packages/shared/useCounter/index.test.ts, packages/shared/useCounter/index.ts
Add as second parameter an options object with `minValue` and `maxValue` in order to create a limited counter.
can be useful for example to create a zoom 
```
const { count: zoom, inc, dec, reset } = useCounter(5, { minValue: 1, maxValue: 16 })
```
=> feat(useCounter): add options

packages/core/useFocus/index.ts
Resolves #926
I noticed some issues when using `useFocus` with an element that was conditionally rendered. I refactored it to have the focus state be a computed based off of the existing `useActiveElement` function instead of trying to keep a ref in sync with value changes and events.
=> fix(useFocus): resolve issues when used with v-if

packages/core/useClipboard/index.ts
Since reading the clipboard could be a sensible move (#321) and requires permissions on Chrome and is NOT supported by Firefox (#937). Instead of opt-out, we should make it opt-out for this feature.
=> fix(useClipboard)!: disable `read` by default

packages/core/useGeolocation/index.ts
useGeolocation API should return a valid number outside of the -90, + 90 / -180, +180 for coords.latitude and coords.longitude when the user isn't at coords { 0, 0 } and they haven't given permission to share their geoLocation.
This ensures we can make a determination between the user actually being at { 0, 0 } and not allowing us to access their geoLocation. 
If the value is Infinity, then we know "something" has gone wrong (i.e., we can confirm that the longitude or latitude is not valid)
=> fix(useGeolocation)!: latitude and longitude default to Infinity

packages/core/onClickOutside/demo.vue, packages/core/onClickOutside/directive.ts, packages/core/onClickOutside/index.ts
BREAKING CHANGE
- `event` option removed
- listen `click` event by default
- feat: prevent calling handler on selections inside target
Close #641 
Close #770
@antfu On #770 I said using `click` by default would fix all issues including _prevent handler call while selecting text in target element_. That was wrong but I come up with simpler solution with single `pointerdown` listener.
I work around click propagation issue by enabling capture phase in click listener. 
As I said, those listeners can be registered when target becomes available in DOM, so we don't have to use capture phase and constantly listening those events. I avoided doing that to prevent adding extra complexity on source code since footprint of those listeners are next to nothing.
=> refactor(onClickOutside)!: listen click event, remove event option

packages/core/useDevicesList/component.ts, packages/core/useDevicesList/index.ts
New option for [useDevicesList](https://vueuse.org/core/useDevicesList/) to describe media types for [permission request](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#parameters) instead of the current hardcoded `{ audio: true, video: true }`. It can be useful when only the audio or video stream is used, leaving the rest of the devices untouched.
---
This is my first PR here, please let me (over)explain myself even if it’s a slight change.
- The parameter is not _ref_ nor _reactive_. I don’t really see its advantage in general here but it would take an extra watcher, reset `permissionGranted`, too much complexity doesn’t sound good.
- The demo page is untouched. This new parameter is very straightforward and introducing checkboxes for this could be confusing. …
=> feat(useDevicesList): add option

packages/core/useAsyncState/index.ts
The first parameter `delay` of execute function should be optional(which has a default value of 0).
=> fix(useAsyncState): optional argument of `execute`

packages/.vitepress/config.ts
vitepress v0.20.1 has support `config.ts`. Let's use it.
=> refactor(docs): use config.ts for vitepress

packages/core/useWebSocket/index.ts
Uncaught InvalidAccessError: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 0 is neither.
=> fix(useWebSocket): close WebSocket gently

packages/core/useScroll/demo.vue, packages/core/useScroll/index.md, packages/core/useScroll/index.ts, packages/core/useVirtualList/component.ts
**Introduce detecting of scroll directions.**
...I also had some doubts as to whether I should reset directions to `false` when scrolling ended. This is in line with utility nature of the project, but as end user if I scroll up and, for example, nav bar appears, I expect it to be shown even if I stop scrolling - until I scroll in opposite direction.
Decided to reset it anyway and leave ui-firendly things on vueuser, but maybe it's room to add some callback options like `onChangeDirectionX`/`onChangeDirectionY` 🤔 🤔 🤔 
---
Related to #976
=> feat(useScroll): directions

packages/rxjs/useSubject/demo.vue, packages/rxjs/useSubject/index.md, packages/rxjs/useSubject/index.test.ts, packages/rxjs/useSubject/index.ts
Add simple way for two-way binding between Vue.js refs and RxJS subjects
- Connecting BehaviorSubject will immediately use it's current value
- Connecting other Subject types will set Ref's value to undefined
- Update Ref value will propagate to the subject
Closes #1028
=> feat(useSubject): new function

packages/core/useElementByPoint/demo.vue
If scrolling down on the page, the demo element is no longer highlighted. This is due to the fact that `elementFromPoint` is relative to the document viewport. To fix this set `useMouse({ type: 'client' })` so the mouse position is relative to the viewport.
- Use mouse position relative to viewport
- hooked into all scroll events instead of just the navigation scroll to update the bounding.
- use `transform: translate` instead of `top, left` to improve performance on pointer
=> docs(useElementByPoint): fixed demo to support document scroll

packages/.vitepress/theme/styles/code.css
Seems like selecting text in code blocks would always select the light theme block. Guess this was caused by the light theme having a higher z-index. Now whichever block is inactive with have a negative z-index.
=> fix(docs): code blocks did not show selected text when in dark mode

packages/core/useScroll/index.ts
Allow `onScroll` and `onStop`callbacks to access the original scroll event
=> feat(useScroll): pass original scroll event to callbacks

packages/core/useScroll/demo.vue
=> docs(useScroll): position retains one decimal

packages/nuxt/index.ts
Fixes #1058 
This PR simply adds `@vueuse/core` and `@vueuse/shared` to the `build.transpile` option of Nuxt config to prevent SSR issues with `refs`. I must admit I haven't tried to reproduce a similar issue with functions from other @vueuse packages (e.g. firebase, electron, etc.) Should those be added too?
=> fix: add @vueuse/core and @vueuse/shared to Nuxt build.transpile

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
Allows `useFetch` to be awaited. For example
```html
import { useFetch } from '@vueuse/core'
const { data }  = await useFetch(url)
console.log(data.value) // outputs resolved data
</script>
```
=> feat(useFetch): allow useFetch to be awaited

packages/core/useTitle/index.md, packages/core/useTitle/index.ts
Added optional titleTemplate injection, for '%s' injection identical to https://vue-meta.nuxtjs.org/guide/metainfo.html.
=> feat(useTitle): added optional titleTemplate injection

packages/core/useStorage/index.md
The `useStorage` docs are missing the third parameter of `useStorage` when talking about custom seralization.
`useStorage` has the following types:
```ts
declare function useStorage(key: string, initialValue: MaybeRef<string>, storage?: StorageLike, options?: StorageOptions<string>): RemovableRef<string>;
declare function useStorage(key: string, initialValue: MaybeRef<boolean>, storage?: StorageLike, options?: StorageOptions<boolean>): RemovableRef<boolean>;
declare function useStorage(key: string, initialValue: MaybeRef<number>, storage?: StorageLike, options?: StorageOptions<number>): RemovableRef<number>;
declare function useStorage<T>(key: string, initialValue: MaybeRef<T>, storage?: StorageLike, options?: StorageOptions<T>): RemovableRef<T>;
declare function useStorage<T = …
```
=> docs(useStorage): update example

packages/core/useElementByPoint/index.md
docs(useElementByPoint): fix doc error "packages/core/useElementByPoint/index.md"
```typescript
export interface UseElementByPointOptions {
x: MaybeRef<number>
y: MaybeRef<number>
}
/**
* Reactive element by point.
*
* @see https://vueuse.org/useElementByPoint
* @param options - UseElementByPointOptions
*/
export declare function useElementByPoint(options: UseElementByPointOptions): {
isActive: Ref<boolean>
pause: Fn
resume: Fn
element: Ref<HTMLElement | null>
}
export declare type UseElementByPointReturn = ReturnType<
typeof useElementByPoint
>
```
Hi guys ! 
Maybe it's a mistake
She need a `UseElementByPointOptions` parameter .
Not `x` & `y`
=> docs(useElementByPoint): fix example

packages/rxjs/from/index.ts
Makes this piece of code emit events, as it should:
```js
interval(1e3).pipe(
switchMap(() => fromEvent(someDivRef, 'scroll')),
).subscribe(x => console.log(x));
```
=> fix(fromEvent): set immediate for `from` (issue #1099)

packages/core/useBroadcastChannel/demo.vue
Fix isError to error so that error can be displayed normally when an error occurs when using useBroadcastChannel to deliver a message.
=> fix(useBroadcastChannel): fix isError to error

packages/core/ssr-handlers.ts
`globalThis` is not defined in qq browser
=> fix(ssr-handlers): compatible with QQ browser

packages/core/useWebSocket/index.ts
The `beforeunload` event is called with the passing of the event parameters instead of code.
Related #1057 
Related #1018
Related #995
=> fix(useWebSocket): close WebSocket

packages/core/useWebWorkerFn/lib/depsParser.ts
PR fix #430.
Multiple dependencies not working in useWebWorkerFn, because the syntax for multiple dependencies is `self.importScripts('foo.js', 'bar.js', ...);`, not `self.importScripts('foo.js, bar.js, ...');`.
=> fix(useWebWorkerFn): fix multiple dependencies handling

packages/core/useDraggable/index.ts
When using `exact: true`, `onEnd()` still gets called even if something else was dragged than the `target` directly.
Add the same check as in `onMove()` to detect if something was dragged.
=> fix(useDraggable): onEnd() runs even if target wasn't dragged directly in exact mode

packages/core/useCycleList/index.ts
Currently go prev when index=0 would get `undefined`
=> fix(useCycleList): operator precedence

packages/core/useWebNotification/index.md
TypeError: Failed to construct 'Notification': Notifications which set the renotify flag must specify a non-empty tag.
=> docs(useWebNotification): update example

packages/core/useMouse/index.md
The `useMouse` utility returns `sourceType`, not `source`.
https://github.com/vueuse/vueuse/blob/6b3bdaa6bdbe7454efda5f9044b5f5b81892c183/packages/core/useMouse/index.ts#L99
=> docs(useMouse): update example

packages/core/ssr-handlers.ts
In https://github.com/vueuse/vueuse/commit/3c8cdded6e949ccfbbdc2539f6d0d26e6c954b61 the build output is
```typescript
const _global = typeof globalThis === "undefined" ? undefined : globalThis;
```
`this` will transform to undefined.
This will cause an exception to occur if there is no `globalThis`
`Uncaught TypeError: Cannot read property '__vueuse_ssr_handlers__' of undefined`
=> fix(ssr-handlers): fix `_global` is undefined

packages/shared/whenever/index.md
类型“UseAsyncStateReturn<any, true>”上不存在属性“ready”
=> docs(whenever): change ready > isReady

packages/firebase/useRTDB/index.md
Replace
```ts
const todos = useRTDB(db.collection('todos'), { autoDispose: false })
```
with
```ts
const todos = useRTDB(db.ref('todos'), { autoDispose: false })
```
=> docs(useRTDB): replace collection ref with db ref

packages/.vitepress/plugins/markdownTransform.ts
Close #1238 
https://github.com/vueuse/vueuse/blob/ef8684ccd424834603a4b8fe6ffcde310938c7c2/packages/.vitepress/plugins/markdownTransform.ts#L110
Output html generate error caused by this logic.
Already tested, work normal with this PR .
=> docs: fix docs section duplicated

packages/shared/whenever/index.test.ts, packages/shared/whenever/index.ts
Add type for value callback param and avoid default `any` typing. Forwards type of `WatchSource` to `WatchCallback` and removes `false`, `null` and `undefined`
```typescript
const counter = ref<number | null | undefined>()
whenever(counter, value => {
// value is type number now instead of any
})
```
=> feat(whenever): add type for callback param

packages/core/useCycleList/index.ts
more rigorous default value
Before 👇👇
```ts
import { useCycleList } from '@vueuse/core'
const { state } = useCycleList([1, 2, 3, 4], {
initialValue: 0 
})
console.log(state.value) // 1
```
Now 👇👇
```ts
import { useCycleList } from '@vueuse/core'
const { state } = useCycleList([1, 2, 3, 4], {
initialValue: 0 
})
console.log(state.value) // 0
```
=> fix(useCycleList): nullish check

packages/core/useConfirmDialog/index.md
I used this in some project and found some mistakes in the example code. 
Problems solved: 
- `isCanceled` is not `ref` type, so it does not contain `.value`.  
- `ref` in a template on a tag with conditional rendering does not work.
- Remove `show` in the second example. It does not show the real situation when we have to use it.
---
=> docs(useConfirmDialog): update

packages/core/useFetch/index.ts, packages/core/useStyleTag/index.md
By https://www.rfc-editor.org/rfc/rfc7231#section-4.1:
> The method token is case-sensitive because it might be
used as a gateway to object-based systems with case-sensitive method
names.
By http://www.iana.org/assignments/http-methods/http-methods.xhtml all existing method are uppercase.
I currently have a REST API that doesn't support `patch` method but works with `PATCH`.
---
=> fix(useFetch): uppercase HTTP methods in useFetch

packages/integrations/useAxios/index.test.ts, packages/integrations/useAxios/index.ts
when use the following demo, can't run, options's value is intance, not { immediate: true }
```ts
import axios from 'axios'
import { useAxios } from '@vueuse/integrations/useAxios'
const instance = axios.create({
baseURL: '/api'
})
const { data, isFinished } = useAxios('/posts', { method: 'POST' }, instance)
```
the reason is
```js
if (args.length >= 2) {
options = args[args.length - 1];
}
```
---
=> fix(useAxios): args param need limit

packages/core/onClickOutside/directive.test.ts, packages/core/onClickOutside/directive.ts, packages/core/onClickOutside/index.md
1. `directive` work unnormal with `v-if`
2. `directive` can't  automatic registered (`VOnClickOutside` => `vOnClickOutside`)
---
=> fix(onClickOutside): should work normal w/ directive

packages/core/useDraggable/index.ts
=> feat(useDraggable): add stopPropagation option

packages/core/useMediaControls/demo.vue
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> chore: use .slice

packages/core/useFetch/index.ts
This PR fixes #1321. I ran into this issue earlier, `useFetch` (as well as the returned function from `createFetch`) return `UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>`, however, as soon as you used `.get()`, `.post()`, `.json()`, or any of the other methods, the return type would be narrowed down to `UseFetchReturn<T>`, which does not let us use `await`.
--- I didn't make the `UseFetchReturn<T>` interface extend `PromiseLike<UseFetchReturn<T>>` because that seems to require more code changes, and I'm unsure if it'd be breaking.
--- There's also a test for this (`should await json response`, at the end of this function's test file), TypeScript does not complain because it's an ESLint rule (https://typescript-eslint.io/rules/await-thenable) what's causing the error, and is not …
=> fix(useFetch): make helper methods return `PromiseLike<UseFetchReturn<T>>`

packages/core/unrefElement/index.ts
type friendly
before:
```typescript
const divRef = ref<HTMLDivElement>()
const el = unrefElement(divRef) // HTMLElement | SVGElement | undefined
```
after:
```typescript
const divRef = ref<HTMLDivElement>()
const el = unrefElement(divRef) // HTMLDivElement | undefined
```
---
=> fix(unrefElement): improve types

packages/core/onClickOutside/index.ts
Fix #1405
If we were using bubbling phase, issues like #1405 could have been fixed by appending `.stop` modifier. Switching to bubbling is breaking change and have different behaviour than capture phase in terms of execution order.
---
=> feat(onClickOutside): customizable phase

package.json, pnpm-lock.yaml
Bump `vue-demi` to fix issues when `vue` isn't available in `window` object in iife build.
Vue itself only declared a global `var` in the iife build, use `window.Vue` to access it is actually a browser convenience which isn't available in every environments.
---
=> fix: bump vue-demi

packages/contributors.json, packages/integrations/useAxios/index.test.ts, packages/integrations/useAxios/index.ts
=> fix(useAxios): reuse url when only AxiosRequestConfig is passed to execute

packages/core/useStorage/guess.ts, packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
Support [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) in the [`useStorage`](https://vueuse.org/core/usestorage/) composition. It also affects the `useLocalStorage` and `useSessionStorage` compositions.
To parse the date into a string, I decided to use the `toISOString`, because it's short and human-readable. Additionally, I found [this peace of spec](https://262.ecma-international.org/11.0/#sec-date.parse) that confirms that, given a Date `x` this code `new Date(x.toISOString())` generates the same date.
---
=> feat(useStorage): support serializing Date

packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
Fix `Set` serialize error, and add tests for `Map` and `Set`.
The entries() method returns a new [Iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) object that contains an array of [value, value] for each element in the Set object, in insertion order. For Set objects there is no key like in Map objects. However, to keep the API similar to the Map object, each entry has the same value for its key and value here, so that an array [value, value] is returned.
The [code](https://github.com/vueuse/vueuse/blob/c8dcfc7a5825420d65b777e47821ec56152bcbac/packages/core/useStorage/index.ts#L48) will lead to wrong result when reload data from storage.
Example:
```js
> new Set(JSON.parse(JSON.stringify(Array.from(new Set([0]).entries()))))
< …
```
=> fix(useStorage): fix `Set` serialize error

packages/integrations/useNProgress/index.ts
This commit changes the type definition for the `options` argument of `useNProgress()` from `NProgressOptions | undefined` to `Partial<NProgressOptions> | undefined`.
This matches NProgress' own type definitions and will prevent errors when using only a subset of NProgress options.
This error came up via `vue-tsc`:
```
resources/panel/components/AppProgress.vue:10:73 - error TS2345: Argument of type '{ minimum: number; showSpinner: false; }' is not assignable to parameter of type 'NProgressOptions'.
Type '{ minimum: number; showSpinner: false; }' is missing the following properties from type 'NProgressOptions': template, easing, speed, trickle, and 5 more.
10 const { start, done, remove, progress, isLoading } = useNProgress(null, {
~
11   minimum: props.minimum || 0.1, …
```
=> fix(useNProgress): allow partial options

packages/router/useRouteQuery/index.ts
This remove the query parameter from url when the ref is set to `defaultValue` or `null` instead of keeping it on the url
=> fix(useRouteQuery): unset route query on default value

packages/core/useRafFn/demo.vue, packages/core/useRafFn/index.ts
This commit is out of my notice about the green button `Transition` in [useTransition demo](https://vueuse.org/core/usetransition/) 
If you use the performance panel of chrome dev tool to record , and then click button `Transition` quickily for several times.
And then you will find there are many `Animation Frame Fired` in just one frame.
This commit try to add `cancelAnimationFrame` to avoid the unnecessary invoke of the repeated raf callbacks
---
=> fix(useRafFn): call `cancelAnimationFrame` on pause

packages/shared/refAutoReset/index.ts
The timeout is not cleared on scope dispose in refAutoReset. This PR fixes that.
---
=> fix(refAutoReset): clear timeout on scope dispose

packages/core/useScriptTag/index.test.ts, packages/core/useScriptTag/index.ts
Custom attributes feature (#1157) that has recently been added to `useScriptTag` didn't support arbitrary attribute names. Attributes were being set as fields directly on the element object and so only some of them worked (e.g. `id`). But any non-standard attributes (like `data-*` ones) didn't work.
---
=> fix(useScriptTag): enable setting arbitrary attrs

packages/shared/watchThrottled/demo.vue
The text describing the demo says that the throttle is 1 second, but the code is set to half a second, so I changed it to match what was stated.
NA
---
- [ X] Documentation update
=> chore: update demo

packages/integrations/useAxios/index.ts
Minor changes:
- Update useAxios package with better syntax: use isAborted like isLoading and isFinished in stead of just aborted (now just an alias).
-  Fix loading documentation comment.
=> fix(useAxios): rename `aborted` to `isAborted`

packages/core/useAsyncState/index.ts
If the provided `onError` handler throws an exception, the `isLoading` state will never be reset to false.
In this circumstance, the `error` ref will still be set, and the `isReady` ref will likewise be correctly left at `false`.
---
=> fix(useAsyncState): `isLoading` not reset

packages/integrations/package.json
With `@vueuse/intergrations`, `change-case` gets forcefully installed as a peer dependency, even if the dev has no need for it. There is a meme of the `node_modules` directory being the heaviest object on the universe for a reason, let's not lend it any additional gravity.
N/A
---
=> Mark change-case as an optional peer dependacy

packages/core/useElementBounding/index.ts
- Call update on compoment mounted
- Add a flag to disable that behaviour
- Default it to true to return the correct values immediately
Fixes #626
UseElementBounding doesn't return the correct value immediately, which is inconsistent with `element.getBoundingClientRect()`. This changes adds an optional flag defaulted to true to call the update function onMounted.
N/A
---
- [ x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x ] Provide a description in this PR that addresses **what** the PR is solving, or reference the …
=> fix(useElementBounding): call `update` on mounted (#626)

packages/core/computedAsync/index.test.ts, packages/core/computedAsync/index.ts
When the async computation in `computedAsync` finish out-of-order, all but the result for the final value are discarded.
This works fine, but was previously untested afaics.
The status ref `evaluating` which tracks, whether a computation is currently running, was however already set to `false` when any computation finished, even though others were still in progress.
I have added a test which checks both and fixed the problem with `evaluating`, so it is now only `false` after the computation for the latest dependency value(s) has finished.
=> fix(computedAsync): keep evaluating true for concurrent changes

packages/core/onClickOutside/index.ts
Fix #1520
[This article](https://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html) from 2014 clearly explains what is going on there. This PR simply workaround this issue by falling back to `pointerup` event. 
`click` event is fired after all release events (`mouseup`, `touchend`, `pointerup`). So, if click event is propagated normally within 50ms, timeout will be cleared. Initially, I was thinking to use `touchend` event. But the type of `touchend` event is not compatible with PointerEvent.
---
=> fix(onClickOutside): fallback to `pointerup` event if `click` event not propagate

packages/core/useNetwork/index.ts
add new attribute（ onlineAt time ）
This attribute records the network reconnection time
---
=> feat(useNetwork): new `onlineAt` attribute

packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts, packages/core/useVModels/index.ts
Add new option `defaultValue` to use when props value is not passed or undefined. 
It can be useful in some situations:
My case: I'm using the same component(Modal) for CREATE and UPDATE a data model. I need to check if props passed or not to make sync of existing data (from API), this is for UPDATE. And for CREATE: I need some default data to let my form work property with v-model
```ts
const type = useVModel(props, 'type', emit)
const _type = ref('')
if (type.value)
syncRef(type, _type) // old syncRef
```
simply 
```ts
const type = useVModel(props, 'type', emit, { defaultValue: 'none' )
```
This is similar to Uncontrolled | Controlled component from
[https://ahooks.js.org/hooks/use-controllable-value](url)
---
=> feat(useVModel): add option to define defaultValue

packages/core/useScrollLock/index.ts
Fixes https://github.com/vueuse/vueuse/issues/1558
useScrollLock In IOS will lock the entire page, In other cases only the specified element will be locked.
---
=> fix: `useScrollLock` lock the entire page

packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts
In #1567, I don't think null should use the default value.
Update the passive option case.
#1567 
#1565 
---
=> chore(useVModel): unified value

package.json, packages/.vitepress/theme/components/FunctionInfo.vue, packages/contributors.json, packages/core/useDebouncedRefHistory/demo.vue, packages/core/useManualRefHistory/demo.vue, packages/core/useRefHistory/demo.vue, packages/core/useThrottledRefHistory/demo.vue, packages/core/useWebWorkerFn/demo.vue, packages/vite.config.ts, pnpm-lock.yaml
Seems that dayjs doesn't ship esm which makes the demos that use it not work in the playground. Replaced it with the vueuse `formatDate` function instead for relevant demos. Also replaced its usage in the docs for the "last changed" property on components with VueUse's `useTimeAgo` function.
Since there were no more instances of it I removed it from the dependencies as well 
---
=> docs: remove unnecessary dayjs usage

packages/core/useScreenSafeArea/index.md
The documentation for `useScreenSafeArea` seems to be missing some descriptions of the functionalities, which makes it difficult for me to use it, so I tried to improve and make it more complete.
> In order to make the page to be fully rendered in the screen, the additional attribute `viewport-fit=cover` within  `viewport` meta tag must be set firstly
---
=> docs(useScreenSafeArea): improve the documentation

packages/guide/index.md
Since `buildModules` is not a config option anymore in Nuxt 3 I updated the docs with the correct option and splitted the configurations for Nuxt 2 and 3.
---
=> docs: Update Nuxt 3 configuration

packages/core/useThrottledRefHistory/index.test.ts, packages/shared/utils/filters.ts, packages/shared/utils/index.test.ts
- chore: remove duplicate test
- fix(throttleFilter): only invoke once when leading is also trailing edge
When using `watchThrottled` and only exactly one change occurs in the source, the callback is still called two times: once immediately on the first change and once after the timeout.
This second call should not occur, because the leading and trailing edges actually coincide, when there is a single event only.
---
=> fix(watchThrottled): duplicate callback invokation when leading and trailing edges coincide

packages/integrations/useAxios/index.ts
aborted, loading and finished aliases are now deprecated, so canceled has to be too and isCanceled created.
=> fix(useAxios): normalize isCanceled flag

packages/core/useVModel/index.test.ts, packages/shared/toRefs/index.test.ts, packages/shared/toRefs/index.ts
Match the prototype object of target object and new object in toRefs composition.
fixes [#1530](https://github.com/vueuse/vueuse/issues/1530)
---
=> fix(toRefs): keep class prototype, close #1530

packages/core/useUrlSearchParams/index.test.ts, packages/core/useUrlSearchParams/index.ts
Now the empty url will overwrite the initial value, making the initial value ineffective.
---
=> fix(useUrlSearchParams): should return initialValue

packages/core/useFetch/index.ts
This fixes an oversight where if you call any of the method-setting methods (`post`, `patch`, etc.), the return value is not `PromiseLike` as the typings would suggest.
```ts
useFetch('http://example.com').post({ foo: 'bar' }).then(() => {}) // undefined is not a function
```
---
=> fix(useFetch): return PromiseLike after setting method

packages/core/useFocus/index.ts
Closes #1560 
Caused by : both of the element to be `undefined` when the `Vitepress` generate HTML page.
---
=> fix(useFocus): `focused` should be `false` when `element` is undefined

packages/core/useMouseInElement/index.ts
Close #1614 
when element is not in viewport
isOutside property initial value is false (when pointer is outside of the screen)
reproduction contains fix
will provide PR immediately
Reproduction
https://stackblitz.com/edit/vitejs-vite-efwwbf?file=src/Comp.vue
---
=> fix(useMouseInElement) isOutside is true for detached elements (#1614)

packages/core/useMediaControls/index.md
This PR fixes a typing error in the documentation of `useMediaControls`
=> docs(useMediaControls): fix heading typo

packages/core/useCssVar/index.md, packages/core/useCssVar/index.ts
We might want to set an initial value for CSS var based on some variable if not preset on it.
This will allow us writing safe CSS where value will be always present.
I haven't added this to watch because I think changing the initial value once it's initialized doesn't matter.
=> feat(useCssVar): support `initialValue`

packages/core/useMagicKeys/index.ts
Chrome send native autofill events that are a bit different than native KeyboardEvent: they do not have some properties (fixed by 03929c770b74691873a724b976d9443daa64d67d) and the `getModifierState` method is not present.
---
=> fix(useMagicKeys): `getModifierState` is not function error in Chrome

packages/core/useScreenOrientation/demo.vue
This PR fixes a typo in the demo component of `useScreenOrientation`.
=> chore(useScreenOrientation): fix typo in demo component

packages/core/useElementBounding/index.md
In the usage part of the original file, the penultimate line of the code has an extra parenthesis, which has been deleted.
---
=> docs: remove unexpected parentheses

packages/shared/watchAtMost/index.ts, packages/shared/watchDebounced/index.ts, packages/shared/watchIgnorable/index.ts, packages/shared/watchOnce/index.ts, packages/shared/watchPausable/index.ts, packages/shared/watchThrottled/index.ts, packages/shared/watchWithFilter/index.ts
The watchCallback paramters type tells an unexpected union type.
My PR is refered to [apiWatch.ts](https://github.com/vuejs/core/blob/cd9265451042dbb3b5911ce09ef55562ab43f688/packages/runtime-core/src/apiWatch.ts#L123)
Please help to review, thanks~
---
=> fix(multi-watch-sources): fix `T` type for `WatchCallback`

packages/shared/useIntervalFn/index.ts
Currently, once the `interval` is changed, the intervalFn will:
- always resume when `immediate = true`, even if it is not active
- never resume when `immediate = false`, even if it is active
It seems like a bug, because we should respect the `isActive` instead.
---
=> fix(useIntervalFn): watch interval correctly

packages/core/useUrlSearchParams/index.ts
The `useUrlSearchParams` function uses `history.replaceState` when updating query parameters. 
Currently the function uses an empty object as "new state" which overrides existing state, this is an issues for router implementation.
This PR reuses the current state and title instead of overwriting it with pseudo content.
---
=> fix(useUrlSearchParams): preserve history state when updating query

packages/core/unrefElement/index.test.ts, packages/core/unrefElement/index.ts
When using `unrefElement` on a template ref of a Vue component which exposes a custom `$el` ([HeadlessUI](https://github.com/tailwindlabs/headlessui)]) that points to a not rendered inner ref (`v-if="false"`), `unrefElement` returns the Vue instance object with `{ $el: null }`. It should return `null` as it should unref the Vue instance ref.
The cause of this bug is how `plain` is checked to be a `VueInstance`. Rather than using the value of `$el`, it should check if it has a property named `$el`.
---
---
_Update 1: added tests_
=> fix(unrefElement): don't return the Vue instance when `$el` is `null`/`undefined`

packages/integrations/useAsyncValidator/index.ts
support [validate options](https://github.com/yiminghe/async-validator#options)
---
=> feat(useAsyncValidator): new options

packages/core/useFileSystemAccess/index.ts
The useFileSystemAccess documentation comment was pointing to incorrect URL (useElementByPoint) instead of useFileSystemAccess
=> Fixed incorrect documentation reference

packages/shared/computedWithControl/index.ts
`source` parameter of `computedWithControl` should match the [vue `watch` api](https://vuejs.org/api/reactivity-core.html#watch). Currently it couldn't accept array of `WatchSource` as parameter in ts. 🤣
---
=> fix(computedWithControl): source type match `watch`

packages/core/useTitle/index.md
Fix markdown syntax of link in `useTitle` documentation page.
---
=> docs(useTitle): fix link

packages/core/useManualRefHistory/index.md, packages/core/useRefHistory/index.md
Add [strucutedClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) as a deep clone implementation in appropriate documentations.
---
=> docs(useRefHistory): Suggest structuredClone as deep clone implementation

packages/shared/reactiveOmit/index.ts, packages/shared/reactivePick/index.ts, packages/shared/utils/types.ts
Fixed reactiveOmit and reactivePick parameter types not supporting passed arrays
---
=> fix(types): `reactiveOmit` and `reactivePick` support array as second arg

packages/integrations/useDrauu/index.ts
to fix [#1749](https://github.com/vueuse/vueuse/issues/1749#issue-1294283413)
no
---
=> fix(useDrauu): fix Eraser does not work

packages/core/onLongPress/directive.ts, packages/core/onLongPress/index.md, packages/core/onLongPress/index.test.ts, packages/core/onLongPress/index.ts
Added event modifiers for onLongPress
closes #1717
---
=> feat(onLongPress): added modifiers

packages/core/useCssVar/index.ts
fix #1738
When I define a css variable, `useCssVar` contains spaces in variable value. 
e.g.
In body: 
```css
body {
--my-aaa:bold ;
--my-bbb: bold;
}
```
```ts
const aaa = useCssVar('--my-aaa', document.body);
console.log(aaa.value) // `bold ` note: `bold` has a space after.
const bbb = useCssVar('--my-bbb', document.body);
console.log(bbb.value) // ` bold` note: `bold` has a space before.
```
So we maybe need remove spaces at both ends for ensure the correct value .
---
=> fix(useCssVar): remove spaces at both ends

packages/core/useColorMode/component.ts, packages/core/useColorMode/demo.vue, packages/core/useColorMode/index.md, packages/core/useColorMode/index.test.ts, packages/core/useColorMode/index.ts
Some applications need to know if the preferred color mode was used, e.g. when showing a dropdown menu with the three options `light`, `dark` or `system`. With the current implementation, there is no way to figure out if the user selected `auto` mode. That means it's not possible to highlight the `system` option in the dropdown as active.
I added an option `emitAuto` which defaults to `false`. When enabled, it includes the `auto` mode in the returned state variable.
=> feat(useColorMode): add option to return `auto` mode

packages/core/useMediaQuery/index.ts
The `useMediaQuery` recently got updated to perform a more strict check for browser support. However, a small mistake slipped in where `typeof 'matchMedia' === 'function'` instead of `typeof window!.matchMedia === 'function'` was checked. The wrong implementation results always in `'string' === 'function'`, so it never supports media queries.
---
=> fix(useMediaQuery): check if window.matchMedia is a function

packages/core/useMagicKeys/index.ts
`current` now contains keys instead of key codes. It's now compatible with the example from docs.
fixes #1503 
---
=> fix(useMagicKeys)!: store `key` instead of `keyCode` in `current`

packages/core/useColorMode/index.ts
I recently added the `emitAuto` option to `useColorMode` (#1627).
Now I discovered a bug with that. The HTML class attribute is now being updated with `auto` class, which is wrong. Even if the `emitAuto` option is enabled and the value `auto` is emitted to the user of the composable, we still need to resolve that in either `light` or `dark` internally.
How to reproduce the bug:
1. Set your system into light mode
2. Visit https://vueuse.org/core/usecolormode/
3. The page should render in light mode
4. Set your system into dark mode
5.  The page should render in dark mode
6. Press the green button until it displays `Auto` again
7. The page renders in light mode, which is wrong
With this fix, the page correctly renders in dark for step 7).
Note: Fix only works with this other fix for …
=> fix(useColorMode): resolve auto to preferred mode internally

packages/core/useMagicKeys/index.ts
On macos when some keys are pressed in combo(cmd+p for example) open a dialog and the keyup is not triggered and the refs keep a wrong state.
I add a blur event listener so when the target lost the focus, the key refs are resetted to false.
fixes #1350 
- [x ] Bug fix
=> fix(useMagicKeys): reset refs on target blur

packages/core/useAsyncState/index.ts, packages/core/useImage/index.ts
=> fix(useAsyncState)!: rename type `AsyncStateOptions` to `UseAsyncStateOptions`

packages/math/useCeil/index.md, packages/math/useCeil/index.test.ts, packages/math/useCeil/index.ts
=> feat(useCeil): new function

packages/core/useTextSelection/demo.vue
This PR aims to improve the [usetextselection's demo](https://vueuse.org/core/usetextselection/#demo) by addressing its layout issues.
This PR aims to 
Currently when the user selects something on the page, the "Selected rects" section of the demo overflows:
also, the "Selected text" label is far away from the text that it describes:
After this PR:
Let me know what you think about these changes
---
=> docs(useTextSelection): fix layout issues in the demo

packages/core/useColorMode/index.ts, packages/core/useLocalStorage/index.ts, packages/core/useSessionStorage/index.ts, packages/core/useStorage/index.ts, packages/core/useStorageAsync/index.ts
rename type `StorageOptions` to `UseStorageOptions`
---
=> fix(useStorage)!: rename type `StorageOptions` to `UseStorageOptions`

packages/core/useIntersectionObserver/directive.test.ts, packages/core/useIntersectionObserver/directive.ts, packages/core/useIntersectionObserver/index.ts
rename type `IntersectionObserverOptions` to `UseIntersectionObserverOptions`
---
=> fix(useIntersectionObserver)!: rename type `IntersectionObserverOptions` to `UseIntersectionObserverOptions`

packages/core/useMemoize/index.ts
rename type `UseMemoizedFn` to `UseMemoizeReturn` and new type `UseMemoizeOptions`
---
=> fix(useMemoize)!: rename type `UseMemoizedFn` to `UseMemoizeReturn` and new type `UseMemoizeOptions`

packages/core/useKeyModifier/index.ts
rename type `ModifierOptions` to `UseModifierOptions`
---
=> fix(useKeyModifier)!: rename type `ModifierOptions` to `UseModifierOptions`

packages/core/usePointerSwipe/index.test.ts, packages/core/usePointerSwipe/index.ts
rename type `PointerSwipeOptions` to `UsePointerSwipeOptions` and `PointerSwipeReturn` to `UsePointerSwipeReturn`
---
=> fix(usePointerSwipe)!: rename type `PointerSwipeOptions` to `UsePointerSwipeOptions` and `PointerSwipeReturn` to `UsePointerSwipeReturn`

packages/core/useSwipe/index.ts
rename type `SwipeOptions` to `UseSwipeOptions` and `SwipeReturn` to `UseSwipeReturn`
---
=> fix(useSwipe)!: rename type `SwipeOptions` to `UseSwipeOptions` and `SwipeReturn` to `UseSwipeReturn`

packages/.vitepress/theme/components/TeamMember.vue, packages/contributors.ts
=> docs: fix function link

packages/core/useDropZone/index.md
Corrects the `onDrop()` signature in the example code.
---
=> docs(useDropZone): fix `onDrop()` signature in example

packages/core/useSpeechSynthesis/demo.vue, packages/core/useSpeechSynthesis/index.ts
[useSpeechSynthesis ](https://vueuse.org/core/usespeechsynthesis/) demo is not playing the right voice when multiple voices are available for the same language, because we are passing language code instead of a `SpeechSynthesisVoice` object. It wouldn't work even if we pass it as `voice` option, because `voice` option is static. I changed it to `MaybeRef` and this required me to make `voiceInfo` a `ref`, and this was a breaking change. Then I thought it was pointless to return the same input that we received from users. So, I removed it.
---
=> refactor(useSpeechSynthesis)!: remove `voiceInfo`, allow `voice` as ref

packages/core/useVModel/index.ts
Fixed compatibility with Vue 2.7
```js
console.log(vm?.proxy?.emit) // undefined
```
Close https://github.com/vueuse/vueuse/issues/1745 (again)
---
=> fix(useVModel): fix compact with 2.7, fix #1745

packages/core/useFileDialog/index.ts
```ts
/// <reference types="node" />
export interface UseFileDialogOptions extends ConfigurableDocument {
/**
* @default true
*/
multiple?: boolean
/**
* @default '*'
*/
accept?: string
/**
* Select the input source for the capture file.
* @see [HTMLInputElement Capture](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture)
*/
capture?: string
}
/**
* Open file dialog with ease.
*
* @see https://vueuse.org/useFileDialog
* @param options
*/
export declare function useFileDialog(options?: UseFileDialogOptions): {
files: Readonly<
Ref<{
readonly [x: number]: {
readonly lastModified: number
readonly name: string
readonly webkitRelativePath: string
readonly path: string
readonly size: number
readonly type: string
readonly arrayBuffer: {
(): Promise<ArrayBuffer>
(): …
```
=> fix(useFileDialog): type UseFileDialogReturn

packages/core/useDropZone/demo.vue, packages/core/useDropZone/index.md, packages/core/useDropZone/index.ts
```vue
import { useDropZone } from '@vueuse/core'
const dropZoneRef = ref<HTMLElement>()
function onDrop(files: File[] | null) {
// called when files are dropped on zone
}
const { isOverDropZone } = useDropZone(dropZoneRef, onDrop)
</script>
<template>
<div ref="dropZoneRef">
Drop files here
</div>
</template>
```
This code is a type error.
---
=> fix(useDropZone): improve argument type

packages/shared/useArrayFind/index.md, packages/shared/useArrayFind/index.test.ts, packages/shared/useArrayFind/index.ts
Reactively array find.
```js
import { useArrayFind } from '@vueuse/core'
const positive = useArrayFind([ref(1), ref(-1), ref(2)], val => val > 0)
// positive.value: 1
```
```js
import { useArrayFind } from '@vueuse/core'
const list = reactive([-1, -2])
const positive = useArrayFind(list, val => val > 0)
// positive.value: undefined
list.push(1)
// positive.value: 1
```
https://github.com/vueuse/vueuse/issues/1812#issuecomment-1181833793
---
=> feat(useArrayFind): new function

packages/math/useAbs/index.md, packages/math/useAbs/index.test.ts, packages/math/useAbs/index.ts
Reactively [Math.abs(value)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs).
```ts
import { useAbs } from '@vueuse/math'
const value = ref(-23)
const absValue = useAbs(value)
// absValue.value: 23
```
---
=> feat(useAbs): new function

packages/math/useMin/index.md, packages/math/useMin/index.test.ts, packages/math/useMin/index.ts
=> feat(useMin): new function

packages/math/useMath/index.md, packages/math/useMath/index.test.ts, packages/math/useMath/index.ts, packages/shared/utils/types.ts
Prior work: #1844 #1841
Thanks to @FrankFang @TwoKe945
=> feat(useMath): new function

packages/core/useSpeechSynthesis/demo.vue, packages/core/useSpeechSynthesis/index.ts
- Fixes wrongly merged demo
- Removes duplicated `onend` assignment
- Cancels speech if `voice` ref changes
---
=> fix(useSpeechSynthesis): cancel speech if `voice` ref changes

packages/core/useMemory/index.ts, packages/shared/useIntervalFn/index.ts
rename type `IntervalFnOptions` to `UseIntervalFnOptions`
---
=> fix(useIntervalFn)!: rename type `IntervalFnOptions` to `UseIntervalFnOptions`

packages/core/useTimeoutPoll/index.ts, packages/shared/useTimeout/index.ts, packages/shared/useTimeoutFn/index.ts
rename type `TimeoutOptions` to `UseTimeoutOptions` and `TimeoutFnOptions` to `UseTimeoutFnOptions`
---
=> fix(useTimeoutFn,useTimeout)!: rename type `TimeoutOptions` to `UseTimeoutOptions` and `TimeoutFnOptions` to `UseTimeoutFnOptions`

packages/core/useClipboard/index.md
Fix missing punctuation in `useClipboard` docs and add Permissions API link.
---
=> docs(useClipboard): fix missing punctuation and add Permissions API link

packages/.vitepress/theme/components/FunctionsList.vue, packages/.vitepress/theme/styles/main.css
Previously, when tabbing through elements on the page, the checkboxes would not change in appearance on focus. [Common web accessibility guidance](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html) typically says that elements like checkboxes should have some keyboard focus indicator.
This also changes the focus indicator to match the primary color.
These changes only affect when navigating through the VueUse docs with a keyboard. These particular changes probably don't make sense to contribute upstream to the Vitepress project because this PR is focused on primarily styling the checkboxes that are implemented only in the VueUse docs.
https://user-images.githubusercontent.com/3038600/180933187-8427c285-3e51-450f-900c-cd01762665ce.mov …
=> docs: add focus outline to checkboxes for accessibility

packages/shared/syncRef/index.md
The documentation for syncRef has an example with a **syncConverters** property defined in options. In the type definition, it is defined as **transform**. This PR changes syncConverters to transform.
---
- [X ] Documentation update
=> docs(syncRef): update docs

packages/firebase/useFirestore/index.md, packages/firebase/useFirestore/index.test.ts, packages/firebase/useFirestore/index.ts
Support `ref` of document reference.
You can use not reactive value as before.
We will be able to bind firestore data also when query is dynamic (e.g. date picker / pagination / infinite scroll)
This GIF shows the same impl custom composable works in my project.
[![Image from Gyazo](https://i.gyazo.com/e2c2a795b26ec04e3fbadb10351b90a4.gif)](https://gyazo.com/e2c2a795b26ec04e3fbadb10351b90a4)
---
=> feat(useFirestore): support reactive query

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
When useFetch has 3 arguments (`url`, `RequestInit`, and `UseFetchOptions`),
the `beforeFetch`, `afterFetch`, and `onFetchError` callbacks were not being
passed through. After this commit, they are.
Relevant unit tests are also added.
fix #2012
---
=> fix(useFetch): broken callbacks when RequestInit and UseFetchOptions are both passed in

packages/shared/useDateFormat/index.md, packages/shared/useDateFormat/index.test.ts, packages/shared/useDateFormat/index.ts
Support `dd`, `ddd` and `dddd` format. #1478
=> feat(useDateFormat): support dd, ddd and dddd formatter

packages/core/useColorMode/index.ts
When enabling the emitAuto option, the onChanged function does not trigger when the preferredMode changed, so I added a watch for preferredMode if emitAuto enabled.
Before:
After:
---
=> fix(useColorMode): when emitAuto is true, onChanged does not trigger when preferredMode changed

packages/core/useFocusWithin/index.md
Fix a couple of typos in useFocusWithin docs.
None.
---
=> docs(useFocusWithin): fix typos

packages/core/useScriptTag/index.ts
=> fix(useScriptTag): normalize `src` arg

packages/core/useFavicon/index.ts, packages/shared/utils/types.ts
=> fix(useFavicon): writable return type

packages/core/useOffsetPagination/index.test.ts, packages/core/useOffsetPagination/index.ts
This will fix the useOffsetPagination issue discussed [here](https://github.com/vueuse/vueuse/issues/1802).
I noticed while editing this composable, it's demo wasn't rendering IDK why 🤔
Moreover, I don't know how to test so please add test for `total` `0`.
---
=> fix(useOffsetPagination): min value for pageCount should be 1

packages/shared/useIntervalFn/index.ts
rename timer type `any `to `ReturnType<typeof setInterval> | null`
What Is the Correct TypeScript Return Type for JavaScript's setInterval() Function?
[link](https://www.designcise.com/web/tutorial/what-is-the-correct-typescript-return-type-for-javascripts-setinterval-function)
---
=> chore(useIntervalFn): improve internal types

packages/core/onKeyStroke/demo.vue
Previously, on the onKeyStroke demo page, the user could not type into
the search box because of a `preventDefault()` that was present in the
demo.
After this fix, the search box can be typed into on the onKeyStroke
demo page.
fix #1951
https://user-images.githubusercontent.com/3038600/183084586-d5a3cfa5-4129-447d-a037-65fa1a06eba0.mov
---
=> docs(onKeyStroke): allow typing into search on demo page

packages/core/useScroll/index.ts
Sometimes when zooming the page to sizes other than 100% and scrolling a
container all the way to the bottom right, the calculation for
`arrivedState.right` and `arrivedState.bottom` would incorrectly say
`false`. This is due to a [rounding error][] because `scrollTop` is a
non-rounded number, while `scrollHeight` and `clientHeight` are rounded.
Using the MDN documentation on `Element.scrollHeight` as guidance,
this commit factors in a 1px margin of error to more accurately
calculate `arrivedState.right` and `arrivedState.bottom`.
[rounding error]: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight#determine_if_an_element_has_been_totally_scrolled
fix #2047
---
=> fix(useScroll): account for rounding errors when calculating arrivedState

packages/.vitepress/config.ts
The last link of the [sidebar](https://vueuse.org/guide/) with the title `Currently Updated` is broken.
Replaced with a link to the function page and the updated sorting enabled. [[link](https://vueuse.org/functions.html#sort=updated)]
---
=> docs: replaces /recent-updated broken link

packages/core/useUrlSearchParams/index.ts
Avoid using global `location` variable in case it is not available. Instead access it as property on the global `window` object.
I might contribute an extended version of useURLSearchParams that provides reactive access to the complete URL path instead of just the search params. Soon™ 
---
=> fix(useURLSearchParams): avoid referencing to global `location`

packages/core/useElementHover/demo.vue, packages/core/useElementHover/index.ts
```ts
const dropZoneRef = ref<HTMLElement>()     // <-- when i set ref as a HTMLElement
function onDrop(files: File[] | null) {
if (!files)
return
const url = window.URL.createObjectURL(files[0])
gifUrl.value = url
}
const { isOverDropZone } = useDropZone(dropZoneRef, onDrop)
const isHovered = useElementHover(dropZoneRef) // <- it got a type error as follow
```
```html
<div ref="dropZoneRef">
xxx
</div>
```
> 类型“Ref<HTMLDivElement | undefined>”的参数不能赋给类型“MaybeComputedRef<EventTarget>”的参数。
不能将类型“Ref<HTMLDivElement | undefined>”分配给类型“Ref<EventTarget>”。
---
=> fix(useElementHover): support set el ref type

packages/core/useActiveElement/index.ts, packages/core/useCurrentElement/index.ts
instead of creating a pointless `counter` ref to do the `trigger` and `track`, \
this change is to reuse `computedWithControl` to trigger the `document.activeElement` update.
**no any functionality change, just a better approach.**
---
=> fix(useActiveElement): use `computedWithControl` instead of `counter` ref

packages/core/useEventListener/index.md
Add more information about unregistering listeners
Extra information about removing listeners. This piece of docs states how to manually remove a listener and not rely on self destroy.
---
- [x ] Documentation update
=> docs(useEventListener): improve docs

packages/core/useFavicon/index.test.ts, packages/core/useFavicon/index.ts
fix for issue #2118 
since `MaybeReadonlyRef` is declared as `fn or computed` 
I think the no param construct should be include in the other overload.
---
=> fix(useFavicon): improve type overload

packages/integrations/useAxios/index.md, packages/integrations/useAxios/index.test.ts, packages/integrations/useAxios/index.ts
related issue: #2149
https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/index.test.ts#L109
This is a little bit strange.
Make some type improve for using execute smoothly.(keep url as same and change request param etc.)
---
=> feat(useAxios): support RequestConfig for `execute`

packages/core/useWindowSize/index.test.ts, packages/core/useWindowSize/index.ts
scrollbar size is included in `window.innerWidth / window.innerHeight`, we don't want it in some cases. \
For example,  to calculate the `top/left/right/bottom` offset for a `position: fixed` element.
---
=> feat(useWindowSize): support `includeScrollbar`

packages/core/useBreakpoints/demo.vue, packages/core/useBreakpoints/index.md, packages/core/useBreakpoints/index.ts
=> feat(useBreakpoints): support `greaterOrEqual` etc.

packages/shared/useArrayMap/index.test.ts, packages/shared/useArrayMap/index.ts
fix [#2159](https://github.com/vueuse/vueuse/issues/2159)
fix [#2159](https://github.com/vueuse/vueuse/issues/2159)
let the `useArrayMap()` function to take the second generics argument, which should be used in the return type
---
=> fix(useArrayMap): allow return type matches the mapper function

packages/core/useElementVisibility/index.ts
relate #2160
Cannot get the real HTMLElement, we should use `unrefElement`.
Also, if `element` is changed, it should also be updated.
---
=> feat(useElementVisibility): support watch the real element

packages/core/ssr-handlers.ts, packages/nuxt/index.ts, packages/nuxt/package.json, pnpm-lock.yaml
This PR updates deprecated Nuxt hook (`autoImports:sources` to `imports:sources`) and bumps `@nuxt/kit` and `@nuxt/schema` to `3.0.0-rc.9`.
---
=> fix!: bump Nuxt support to RC.9, update `autoImports:sources` hook

packages/core/useElementSize/demo.vue, packages/core/useElementSize/index.ts, packages/core/useResizeObserver/index.ts
closes #2158 
Currently, it only returns the `content-box` size, which the `padding` & `border` is not included. Even if the `box` option is configured as `border-box`.
---
=> feat(useElementSize): support `box` sizing

packages/core/useDevicePixelRatio/demo.vue, packages/core/useDevicePixelRatio/index.md, packages/core/useDevicePixelRatio/index.ts
I implemented a more efficient mechanism for the `useDevicePixelRatio` function that inspired by [this example](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#monitoring_screen_resolution_or_zoom_level_changes)
Currently the `useDevicePixelRatio` function create 12*2 watchers/eventListeners (+1 window resize) to achieve the same goal, this mechanism use only 1 event listener to check if the current `resolution` changed (once) then update the value and recursively check the new value
---
=> fix(useDevicePixelRatio): more efficient mechanism

packages/.vitepress/plugins/markdownTransform.ts
When using algolia search(in `dev`) to jump to the specific function page, `demo` and other markdown details were disappeared, but everything works fine by manually clicking on the right nav-bar of the function.
because function name in `url` returned from algolia is in lowercase, but it's uppercase in generated `packages/metadata/index.json`.
This only happens in dev mode.
---
=> docs: fix function name matching

packages/core/templateRef/index.test.ts, packages/core/templateRef/index.ts
CC: @murongg
Fixes https://github.com/vueuse/vueuse/issues/1757, replace PR #1760
Allow `templateRef` to support vue component type
This replaces PR #1760 by rebasing the latest main branch, then add a test case for the new use case for templateRef function.
---
=> fix(templateRef): add Component type

packages/core/onClickOutside/index.ts
fix #2196 
put ignore logic on `pointerdown` event, making sure the proper behavior.
---
=> fix(onClickOutside): put ignore logic on `pointerdown` event

packages/core/onKeyStroke/directive.ts, packages/core/onKeyStroke/index.md, packages/core/onKeyStroke/index.test.ts, packages/core/onKeyStroke/index.ts
linked issue: #2195 
null/undifined is not necessary here. Also () => false as well.
Add a overload for better usage and fix directive.
---
=> feat(onKeyStroke): support capture all handler

packages/core/onClickOutside/demo.vue, packages/core/onClickOutside/directive.ts, packages/core/onClickOutside/index.ts
Related #2181, #1405, https://github.com/vueuse/vueuse/issues/1405#issuecomment-1240672606
Solves #1366 in a better way to make it work with this feature.
```html
<button @click.stop="modal = !modal">
Toggle Modal
</button>
<div v-if="modal" v-on-click-outside.bubble="() => modal = false">
Hello World
</div>
```
---
=> feat(onClickOutside): add `bubble` modifier to directive

packages/core/useCached/index.test.ts, packages/core/useColorMode/index.test.ts, packages/core/useFetch/index.test.ts, packages/core/useFocusWithin/index.test.ts, packages/core/useStepper/index.test.ts, packages/shared/computedWithControl/index.test.ts
This is a long-term branch. All PRs from this branch intend to increase UT coverage and optimize vueuse source code. I will continuously commit test code to this branch. 
All commits in this branch are atomic, feel free to merge PR at any time.@antfu 
|api|statements|branches|functions|lines
|-----|------|------|-----|-----|
|useColorMode|100% ⬆️|100% ⬆️|100% ⬆️|  100% ⬆️
|useCached|100%  |100% |100% ⬆️ | 100%
|useFocusWithin|100%  |100% ⬆️ |100%  | 100%
|computedWithControl|100%  |100% |100% ⬆️ | 100%
|useStepper|100% ⬆️|100% ⬆️|100% |  100% ⬆️
|useFetch|100% ⬆️|100% ⬆️|100% ⬆️|  100% ⬆️
=> test: impove test coverage

package.json, pnpm-lock.yaml
=> chore: downgrade vite-plugin-inspect

packages/integrations/useAxios/index.ts
Perhaps there should be more options for data than just shallowRef, which may not be sufficient in certain scenarios
closes #2250
---
=> feat(useAxios): add option for choosing shallowRef or ref

packages/core/useScroll/demo.vue, packages/core/useScroll/index.md, packages/core/useScroll/index.ts
feat(useScroll): support setting scroll position and toggling smooth scrolling
Add ability to set scroll values and turn on or off smooth scrolling.
fix #1978
https://user-images.githubusercontent.com/3038600/183017273-8662c796-0ea0-42a7-9660-ce6f59bcc8f1.mov
---
=> feat(useScroll): support setting scroll position and toggling smooth scrolling

packages/firebase/useFirestore/index.md, packages/firebase/useFirestore/index.test.ts, packages/firebase/useFirestore/index.ts
Enable to use the boolean value to tell a query when it is ready to run.
```typescript
const userId = ref('')
const docRef = computed(() => !!userId.value && doc(db, 'users', userId.value))
const userData = useFirestore(docRef, null)
userId.value = 'userId' // start querying
```
Fixes https://github.com/vueuse/vueuse/issues/2018 @smakinson
You can avoid invalid segment error of firestore path.
Similar interface of https://github.com/Kong/swrv#dependent-fetching
---
=> feat(useFirestore): support dependent queries

packages/core/useDark/index.md
This PR clarifies the default behavior of the isDark composable, which persists the current value to localStorage under the key `vueuse-color-scheme`, and fixes a few grammatical points in the remainder of the page for clarity.
While the docs say that this composable reads "the value from localStorage/sessionStorage (the key is configurable) to see if there is a user configured color scheme," it's not illustrated how this key can be configured. I'm not sure how that is done, so I just added information about the default behavior.
---
=> docs(useDark): not about default localStorage key

packages/core/useTimeAgo/index.test.ts, packages/core/useTimeAgo/index.ts
=> feat(useTimeAgo): new `showSecond` option

packages/shared/until/index.test.ts, packages/shared/until/index.ts
=> fix(until): `.not` returns new instance

packages/core/useTimestamp/index.ts, packages/shared/useInterval/index.ts, packages/shared/useTimeout/index.ts
Added optional callback for `useInterval`, `useTimeout` & `useTimestamp` functions
---
=> feat: optional callback for useInterval, useTimeout & useTimestamp 

packages/.vitepress/theme/composables/dark.ts
Refs: 
Vitepress uses [`vitepress-theme-appearance`](https://github.com/vuejs/vitepress/blob/ee37eaa27191faad03c04d60fb3ca8ffbb887fbe/src/shared/shared.ts#L21) as theme `storageKey` and VueUse uses [`vue-theme-appearance`](https://github.com/vueuse/vueuse/blob/2419803235e55e5e19057c4225c30edc571ee4b1/packages/.vitepress/theme/composables/dark.ts#L4). 
Repro the issue:
1. Switch color-scheme to dark
2. Go to [https://vueuse.org/core/useDark/](https://vueuse.org/core/useDark/), color-scheme changed to `light` . Reload the browser you will see it changed to `dark` and then changed to `light`.
3. Go to other route and reload the browser,  color-scheme changed to `dark` again.
---
=> docs: fix theme storage key

packages/rxjs/from/index.ts
Hi, thanks to `@vueuse` and `@vueuse/rxjs`，I can use rxjs in vue easily.
The `fromEvent` function support `Ref<HTMLElement>`, and code:
```
import { fromEvent } from '@vueuse/rxjs'
import { fromEvent as fromEventRx } from "rxjs";
const mousedown$ = fromEvent(resizeAnchorRef!, 'mousedown');
const mouseup$ = fromEventRx(document.body, 'mouseup');
const mousemove$ = fromEventRx(document.body, 'mousemove');
```
Expect `fromEvent` can also support `HTMLElement`, so I can use like this:
```
import { fromEvent } from '@vueuse/rxjs'
const mousedown$ = fromEvent(resizeAnchorRef!, 'mousedown');
const mouseup$ = fromEvent(document.body, 'mouseup');
const mousemove$ = fromEvent(document.body, 'mousemove');
```
---
=> feat(fromEvent): support HTMLElement

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
fixes #2225, #1310 
~~Like @imaverickk metioned in #2225, there's another solution: use `Promise.all()`. I'm not sure which one is better~~
> Transforming for-await loops to the configured target environment ("es2017") is not supported yet. Thus `Promise.all()` seems to be the only solution?
---
=> fix(useFetch): fix incorrect `chainCallbacks` behavior

packages/integrations/useFocusTrap/index.md, packages/integrations/useNProgress/index.md
Even though `useFocusTrap` is categorized as an integration and described to be a "reactive wrapper for [focus-trap](https://github.com/focus-trap/focus-trap).", I think it'd be better to specify that you need to install `focus-trap` as a dependency.
Also, other integrations do this, just before the "Usage" section.
=> docs(useFocusTrap): improve the documentation

packages/nuxt/ssr-plugin.mjs
When using the `nuxt` package, the console outputs the warning:
```bash
[warn] [nuxt] You are using a plugin that has not been wrapped in `defineNuxtPlugin`. It is advised to wrap your plugins as in the future this may enable enhancements: () => { }
```
This pull request simply wraps the ssr-plugin file export with `defineNuxtPlugin`
---
=> fix(nuxt): wrap ssr plugin in defineNuxtPlugin

packages/integrations/useFocusTrap/component.ts, packages/integrations/useFocusTrap/index.md
=> feat(useFocusTrap): enable options in component

packages/firebase/useFirestore/index.ts
As we say in #2276, until we figure out how we will make the new autodispose option it's need to at least enable back the auto dispose of documents.
---
- [] Ideally, include relevant tests that fail without this PR but pass with it.
=> fix(useFirestore): auto dispose documents

packages/shared/useToggle/index.md
This adds a small note in the docs for `useToggle` to be wary of binding directly to a button click, as this will almost definitely result in unintended behavior because of how browsers handle click handlers.
Example of accidental  misbehavior here: https://codesandbox.io/s/objective-tesla-zmpitb?file=/src/App.vue
=> docs(useToggle): note about events in template

packages/router/useRouteHash/index.ts, packages/router/useRouteParams/index.ts, packages/router/useRouteQuery/index.ts
When changing route hash using `useRouteHash`, it resets existing route query if exists. same for all three functions.
The change is pretty simple and is spreading the current route instance (defaults or given)
---
=> fix(useRouteHash, useRouteParams, useRouteQuery): override only selected route param

packages/core/useClipboard/index.ts
Add `legacy: boolean` option. 
It will fallback to legacy methods `document.execCommand('copy')` if ClipboardApi is not allowed, for scenes like hosting website with IP adress, especially during development.
Relate to #1276
---
=> feat(useClipboard): support legacy copy

packages/core/useEventListener/index.test.ts, packages/core/useNow/index.test.ts, packages/core/useTimestamp/index.test.ts, packages/shared/createEventHook/index.test.ts, packages/shared/watchDebounced/index.test.ts, packages/shared/watchThrottled/index.test.ts
All PRs from this branch intend to increase UT coverage and optimize vueuse source code. I will continuously commit test code to this branch. 
All commits in this branch are atomic, feel free to merge PR at any time.@antfu 
History PRs: 
- https://github.com/vueuse/vueuse/pull/2185
- https://github.com/vueuse/vueuse/pull/2233
- https://github.com/vueuse/vueuse/pull/2256
- https://github.com/vueuse/vueuse/pull/2300
|api|statements|branches|functions|lines
|-----|------|------|-----|-----|
|createEventHook|100% ⬆️|100%  |100% ⬆️  |  100% ⬆️
|useTimestamp|100% ⬆️|100% ⬆️  |100% ⬆️  |  100% ⬆️
|useNow|100% ⬆️|100% ⬆️  |100% ⬆️  |  100% ⬆️
|useEventListener|100% ⬆️|100% ⬆️  |100%   |  100% ⬆️
|watchThrottled|100% ⬆️|100%   |100% ⬆️  |  100% ⬆️
|watchDebounced|100% ⬆️|100%   |100% ⬆️  |  100% …
=> test: improve test coverage

packages/core/useWebSocket/index.ts
The call `clearTimeout(undefined)` was dominating my program runtime, even though I didn't enable heartbeats. Skip this call when heartbeats disabled.
---
=> chore(useWebSocket): skip call to clearTimeout when heartbeat disabled

packages/core/useWebSocket/index.ts
=> fix(useWebSocket): don't reconnect WebSocket if `close` issued between retries

packages/core/useFetch/index.md, packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
Allow to configure the lifecycle handler behavior before `createFetch` and `useFetch`.
Address my https://github.com/vueuse/vueuse/pull/1545#issuecomment-1118193827
---
=> feat(useFetch): allow configure lifecycle handler behavior

tsconfig.json
There is no diff between "\*\*/\*\*/\*.md" and "\*\*/\*.md".For avoid confusion, change it.
=> chore: simplify tsconfig.json

packages/core/computedAsync/index.md
The Evaluation State description of the document computedAsync should end with "."
=> docs(computedAsync): adjust punctuation

packages/core/useScroll/index.ts
I first ran into this problem when using the `useInfiniteScroll` function, which caused the list to not load more contents once it was scrolled to the bottom.
The reason for this bug is that the `useThrottleFn` used in `useScroll` is not configured properly with: `[trailing=true]` and `[leading=false]`,where it ensures that the function must be executed once after the scrolling ends.
https://user-images.githubusercontent.com/19204772/199266546-7594cf50-0fee-4a61-9e9f-4d04f013875a.mov
---
=> fix(useScroll): the expected result cannot be returned after setting the throttle parameter

packages/core/useStorage/guess.ts
`typeof []` is always `'object'`,  so L16-L17 below is unreachable
https://github.com/vueuse/vueuse/blob/24747b636c61d23fa9c14474ba1a5ce78956dae1/packages/core/useStorage/guess.ts#L14-L17
---
=> refactor(useStorage): reduce redundant type guess

packages/core/usePointerSwipe/index.ts
Fix issue where a secondary click (the right button on a right-handed mouse) on an element using usePointerSwipe() is treated as if the primary button (left click on a right-handed mouse) has started a drag.
- Rename filterEvent() to eventIsAllowed() for better clarity
- Fix typo in docs and make punctuation consistent
Fixes #2338
1. Right click on the button
2. Hit the Escape key to dismiss the context menu
3. Without clicking, move the mouse around over the button. The button behaves as if it is being dragged.
A right click does nothing other than open the context menu as usual.
=> fix(usePointerSwipe): handle secondary clicks properly

packages/core/useTimeAgo/index.ts
=> refactor(getTimeAgo): rename `getTimeago` to `getTimeAgo`

packages/firebase/useFirestore/index.md, packages/firebase/useFirestore/index.ts
Now you can use only `false` value for dependent query, so I added `Falsy` type.
Also fixed to use `null` value to initial value.
---
=> fix(useFirestore): fix falsy type error

packages/core/onClickOutside/index.ts
Reproduction: https://vueuse.org/core/onclickoutside/
1. Click "Open Modal"
2. Press `Tab`, your focus is now on "Toggle Dropdown" button
3. Press Space. Dropdown opens but Modal is still there, it should be closed since a `click` event is fired outside the modal.
Try the same thing by clicking "Toggle Dropdown" first. It works as expected. This PR fixes that inconsistency.
---
=> fix(onClickOutside): call handler if `click` event is fired by a keypress

packages/integrations/useIDBKeyval/index.test.ts, packages/integrations/useIDBKeyval/index.ts
`useIDBKeyval` has some problems in L58-L59. This PR purpose is to solve these problems below.
-  Only `undefined` and `null`  `rawInit` should be ignored to set
- Since `set` is an async method, it is unsafe without `await`(L65-L67 can't catch error when `set` error). 
https://github.com/vueuse/vueuse/blob/0a49ea4dacbd98cdeb6e4be1bba3bc9347a8845a/packages/integrations/useIDBKeyval/index.ts#L54-L70
Unit test covered.
---
=> fix(useIDBKeyval): incorrect value init set

packages/nuxt/ssr-plugin.mjs
There is no `useMeta`
Breaks Nuxt3 RC.14
---
=> fix(ssr-plugin): use useHead instead of useMeta

packages/core/useStyleTag/demo.vue, packages/core/useStyleTag/index.ts
The current implementation of `useStyleTag` uses `el.innerText` to set the `<style>` elements content. As per the spec, this `innerText` method [replaces line-breaks with `<br>` tags](https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute) on set, which prevents `useStyleTag` from supporting multi-line CSS as the injected `<br>` will break the CSS parsing.
From the [spec](https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute):
> element.[innerText](https://html.spec.whatwg.org/multipage/dom.html#dom-innertext) [ = value ]
Returns the element's text content "as rendered".
>
> Can be set, to replace the element's children with the given value, **but with line breaks converted to [br](https://html.spec.whatwg.org/multipage/text-level-semantics.html#t …
=> fix(useStyleTag): allow multiline CSS

packages/core/useTimeAgo/component.ts
The `showSecond` option added in PR #2209 is missing from the UseTimeAgo component.
---
=> fix(useTimeAgo): add `showSecond` prop to component

packages/core/useTimeAgo/index.ts
The value is always rounded on format calculation.
closes #2542
---
=> feat(useTimeAgo): add `floor` and `ceil` value calculation

packages/core/useMagicKeys/index.ts
On macos when some keys are pressed in combo(cmd+p) open a dialog and the keyup is not triggered and the _current_ keep a wrong state.
This fix now also clears the `current: Set<string>` with the existing `reset()` function (added in prior https://github.com/vueuse/vueuse/pull/1755).
fixes https://github.com/vueuse/vueuse/issues/1350
ref: https://github.com/vueuse/vueuse/pull/1755
Testing / Reproduction, see description of https://github.com/vueuse/vueuse/issues/1350...
---
=> fix(useMagicKeys): also clear 'current' on @focus|@blur

packages/core/useActiveElement/index.ts
If a blur event has a `relatedTarget` [that element will receive focus](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget). For the short time between blur and focus the `document.activeElement` will be the body element. By ignoring the blur event here we simply wait for the computedWithControl to be triggered by the focus event that will follow as we know. By then the new element will have focus.
By doing this we prevent e.g. that stuff will be triggered that depends on the activeElement being inside a specific element. E.g. `useFocusWithin` will profit from this, since the focus will not be reset to `<body>` in between.
---
=> fix(useActiveElement): ignore blur for relatedTarget

packages/shared/useIntervalFn/index.ts
`useIntervalFn`'s `interval` option has the ability to be watched to dynamically change the interval. However, the check to add the watcher uses `isRef`, even though `interval` is of type `MaybeComputedRef`, which allows it to be a function, which is a valid watch value.
This pull request changes the check to ensure `interval` is either a `Ref` or a `Function`, so the following is also valid:
```ts
const $props = defineProps<{
interval?: number
}>()
useIntervalFn(() => { /** ... **/ }, () => $props.interval ?? 5000)
```
=> fix(useIntervalFn): watch computed refs instead of just refs

packages/core/useTextareaAutosize/index.ts
If the size of a textarea is changed by other stuff than the window width `useTextareaAutosize` currently breaks. By watching the textarea via useResizeObserver we make sure a change in width is accounted for.
---
=> fix(useTextareaAutosize): support changes of element width

packages/shared/createEventHook/index.ts
call off function onScopeDispose
Improve createEventHook by calling off function in onScopeDispose hook
---
- [ X] Other
=> feat(createEeventHook): auto dispose

packages/core/useRafFn/index.ts
This pull requests adds an object containing the `delta` and `timestamp` of the current `requestAnimationFrame` to the callback function of `useRafFn`.
The `requestAnimationFrame` method is most useful when used in conjunction with its given timestamp, and the delta with the previous frame. One example is to make animations.
---
=> feat(useRafFn): add `delta` and `timestamp`

packages/core/useWindowScroll/index.ts
makes `useWindowScroll` use the given window for the scroll listener.
fixes #2544 
---
=> fix(useWindowScroll): use configured window onScroll

packages/core/onClickOutside/index.ts
=> fix(onClickOutside): apply ignore list on keyboard clicks

packages/core/useTimeAgo/index.ts
Typo in function name, it's now equal to documentation mentioning `formatTimeAgo`.
---
=> fix(formatTimeAgo): typo `foramtTimeAgo` -> `formatTimeAgo`

packages/core/useAsyncState/index.ts
Add an onSuccess callback in useAsyncState
issues [2560](https://github.com/vueuse/vueuse/issues/2560)
=> feat(useAsyncState): add onSuccess callbacks

packages/core/useFetch/index.ts
Fixes #1734.
Content-Type should not be set for payload of formData type,  leave alone and let the browser do.
reference: [Automatic Content-Type for FormData uploads](https://github.com/axios/axios/commit/2f4d0b8b45dbb766a3348200fdff02ee00d9d6c0)
---
=> fix(useFetch): doesn't work with formData payload

packages/core/useElementBounding/index.ts
Closes #2319, The Scrolling of useElementBounding didn't work when a div gets scrolled, only when the window was scrolled. Now it works.
=> fix(useElementBounding): update on scroll

packages/nuxt/index.ts
=> fix(nuxt): disable useImage in the Nuxt package for auto imports

packages/core/useVirtualList/component.ts, packages/core/useVirtualList/index.md
Expose `scrollTo` in the virtual list component. So far, this feature wasn't accessible in the component version of virtual lists.
---
=> feat(useVirutalList): expose `scrollTo` in component

packages/core/_configurable.ts, packages/core/useActiveElement/index.test.ts, packages/core/useActiveElement/index.ts, packages/core/useEventListener/index.ts
Assuming you have a DOM structure like so:
```
body
my-element
#shadow-root
input
```
When the `input` becomes active, the outer document's `activeElement` will actually be `my-element`, _not_ the input.
Each shadow root has its own `activeElement` in case you want to get hold of the inner element in these cases.
This adds support to `useActiveElement` such that you can pass a shadow root as the document to observe the active element of.
---
---
let me know if there's some reason you wouldn't want this or it needs doing differently and ill update.
=> feat(useActiveElement): support shadow roots

packages/core/useDraggable/component.ts
Fixed a bug that "UseDraggable component" does not write to storage even if storage-key and storage-type are passed.
**before**
In the video example, the position has reverted to (860, 199)  after the page change.
<details>
<summary>before video</summary>
https://user-images.githubusercontent.com/7263054/209443102-b21055e0-b628-4c03-bc9b-b0e022409b2a.mp4
</details>
**after**
The position is persistent even after page change.
<details>
<summary>after video</summary>
https://user-images.githubusercontent.com/7263054/209443232-45c0aef2-40d4-4a51-bf74-b0ea7e0510ae.mp4
</details>
---
=> fix(useDraggable): write to useStorage

packages/core/computedAsync/index.md, packages/core/computedAsync/index.ts
Use `shallowRef` and mark the return value as `readonly` to conform to the `computed` ideas.
issues #2117 
---
=> feat(computedAsync): introduce `shadow` option

packages/firebase/useAuth/index.md
Fixed documentation to correct Firebase's signInWithPopup() method to take the required 'auth' parameter. 
---
=> docs(useAuth): fixed signInWithPopup() example in docs

packages/shared/useTimeoutFn/index.md
https://vueuse.org/shared/useTimeoutFn/
From the figure above, we can see that the location of the `Demo` and `useTimeoutFn` is wrong.
=> docs:  useTimeoutFn miss Usage title

packages/core/useScroll/index.md
In the example it should import `useScroll` instead of `useWindowScroll`.
---
=> docs: fix typo

packages/core/onStartTyping/demo.vue
`HTMLInputElement` has no `active` attribute
onStartTyping
---
=> docs(onStartTyping): fix demo

packages/shared/useThrottleFn/index.test.ts
add test cases
useThrottleFn
---
=> feat(useThrottleFn): add test cases

packages/core/useVirtualList/index.md, packages/core/useVirtualList/index.ts
Virtual scroll is difficult to get right and comes with many complexities. It seems that it is outside the scope of VueUse and we should suggest users to use more complete and battle tested libraries for this. Currently the best library for this is https://github.com/Akryum/vue-virtual-scroller 
---
=> refactor(useVirtualList): deprecate in favor of vue-virtual-scroller

packages/math/usePrecision/index.ts
Return type of `usePrecision` was `ComputedRef<number | string>` instead of `ComputedRef<number>`, which was causing typing annoyance.
---
=> fix(usePrecision): fix return type

packages/core/useMediaControls/index.ts
When the media element ends playing, the ``ended`` status is set to true. However, if the media element status change, changing the ``ended`` status variable is not taken into consideration.
---
=> fix(useMediaControls): ended status not updating

packages/core/useElementSize/index.md, packages/core/useFocus/index.md, packages/core/useMousePressed/index.md
I've checked all markdown files in search of extra close parentheses and found 3 more.
---
=> docs: remove extra close parentheses.

packages/shared/useTimeoutFn/index.ts, packages/shared/utils/types.ts
fixes #2691
On L62 of useTimeoutFn, `start()` is used without any parameters. What if user defines a callback that requires arguments to work? Maybe a new option like `defaultArguments` could be introduced?
---
=> fix(useTimeoutFn): respect callback parameters in start function

packages/core/useRafFn/index.ts, packages/shared/useIntervalFn/index.ts, packages/shared/useTimeoutFn/index.test.ts, packages/shared/useTimeoutFn/index.ts, packages/shared/utils/filters.ts, packages/shared/utils/types.ts
1. isPending / isActive is now read-only, so they are not seen as an alternative to the pause/start/result/stop functions.
2. Minor fixes for type correctness.
---
=> feat(useRafFn, useIntervalFn, useTimeoutFn): make status readonly

packages/core/useElementSize/index.ts
fix [#2084](https://github.com/vueuse/vueuse/issues/2084)
fix incorrect size on SVG element, due to https://www.w3.org/TR/resize-observer/#calculate-box-size
=> fix(useElementSize): fix incorrect element size on SVG

packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.ts
I want to have a a global WebSocket in my app. Since the introduction of ref passing to useWebSocket, useWebSocket is much more useful for scenarios where you change between servers, since I can always expect the WebSocket to work and be up to date without any manual handling from our side. Everything works thanks to vue ``computed`` (to construct the webSocket url) and a ref to an object which contains the server URL.
However, expecting only URLs or strings makes it really difficult to have that webSocket always globally: there are situations in my app where no server is defined. Without this PR, I need to have a watcher and then instantiate the socket using ``useWebSocket``. This PR solves all this logic.
I also fixed the docs, which were with outdated types
---
* #2200 is very similar …
=> feat(useWebSocket): allow undefined ref for url

packages/shared/watchThrottled/index.test.ts
Fix the problem that the number of function calls caused by short waiting time is not accurate, this problem occurs in the check of #2706 
watchThrottled
---
=> chore: improve test

packages/core/useConfirmDialog/index.md, packages/shared/useDateFormat/index.md
These imports are not used
useConfirmDialog useDateFormat
---
=> docs(useConfirmDialog,useDateFormat): remove useless imports

packages/core/useSwipe/demo.vue
The height attribute does not carry a unit, and it does not take effect in the style.
useSwipe
---
=> docs(useSwipe): remove invalid styles

packages/core/useInfiniteScroll/index.md
Removed unused toRefs in useInfiniteScroll
just removal of unnecessary toRefs was being used in the example of useInfiniteScroll 
---
- [] Ideally, include relevant tests that fail without this PR but pass with it.
=> docs(useInfiniteScroll): remove unused toRefs

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
closes #2677 
When executing requests continuously or monitoring url ref changes, the previous request will be automatically terminated to ensure that the obtained data is the most current requested data.
useFetch
---
=> feat(useFetch): cancel previous request

packages/core/useVirtualList/index.md, packages/core/useVirtualList/index.ts
Remove the `deprecated` tag and link out to `vue-virtual-scroller` as discussed in this topic #2683 .
---
=> refactor(useVirtualList): remove deprecated tag

packages/core/useMagicKeys/index.md
'and' is now available as 'logicAnd' in '@vueuse/math'.
The Conditionally Disable example is broken due to `and` not existing in `@vueuse/core`. `and` is now available as `logicAnd` in `@vueuse/math`.
This PR fixes the "Conditionally Disable" example.
---
=> docs(useMagicKeys): fix 'and' in demo

packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
Fixes #2605 
Fixes #2567 
Basically when you introduced a fix to update instances on the same window using the same store (800f74f), you did this by dispatching a `StorageEvent` (such that the already existent listener would catch it and update the value as needed).
This caused a breaking change in that things like pinia stores would no longer work with it.
The reason for that is that you can only construct a `StorageEvent` if the storage area is built-in pretty much (e.g. local storage, session storage, etc). You definitely _cannot_ construct one with a custom storage area such as pinia (anything that conforms to your `StorageLike` interface).
All of the `useStorage` tests were throwing an exception because of this, which was being eaten up by the `onError` handler (which the tests don't …
=> fix(useStorage): emit a custom event to support custom storage areas

packages/core/useAsyncState/index.ts
Add a generic parameter to obtain the type definition of the argument passed to a Promise function.
---
=> feat(useAsyncState): get a promise function parameter type declaration

packages/integrations/useFocusTrap/index.md
Update to documentation for useFocusTrap to include a solution for handling focus on conditional rendered elements that can be done entirely in code, without a component.
Originally, the only documented way this was possible was by using the component.
---
=> docs(useFocusTrap): added non-component solution for conditional rendering

packages/core/useWindowScroll/index.md, packages/core/useWindowScroll/index.ts
=> fix(useWindowScroll): use `scrollX` instead of `pageXOffset`

packages/shared/utils/filters.ts
fixes #2618 
caused by a **BIG** negative timeout. Exists in the past versions as well, but only occurs at the first call.
```js
const printHello = () => console.log('hello')
// will not print `hello`
setTimeout(printHello, -1672930567173)
// will print `hello`
setTimeout(printHello, -167293056)
```
---
=> fix(useThrottleFn): check negative timeout

packages/core/useScroll/index.ts
Better scroll end event detection using native `scrollend` event.
See [Scrollend, a new JavaScript event](https://developer.chrome.com/blog/scrollend-a-new-javascript-event/), now shipped in Firefox 109.
---
=> feat(useScroll): support scrollend event

packages/core/useElementHover/demo.vue, packages/core/useElementHover/index.ts
Give useElementHover hook delay properties,I have done the test myself ~ @Alfred-Skyblue 
---
- [X ] Bug fix
- [√ ] New Feature
- [ X] Documentation update
- [ X] Other
- [√ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ √] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [√ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [√ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [√ ] Ideally, include relevant tests that fail without this PR but pass with it.
=> feat(useElementHover): introduce delay hooks

packages/core/useTitle/index.test.ts
When running vitest tests, there is a warning that is being displayed:
```
stderr | packages/core/useTitle/index.test.ts > useTitle > with readonly param > computed
Write operation failed: computed value is readonly
```
This warning is totally genuine, because setting value of a readonly computed value is a noop. Still, it clutters tests summary, and might give the impression that something is not right in the `useTitle` composable, whereas the warnings actually come from the tests themselves in order to verify typings.
I replaced these types verifications with tests, using the `isReactive` vue utility, to remove those warnings.
---
=> test(useTitle): remove unecessary warnings thrown during tests

packages/core/useScrollLock/index.ts
This PR adds a condition to the `checkOverflowScroll` function for elements that have an overflow value that is `auto`.
See: https://github.com/vueuse/vueuse/pull/2362#issuecomment-1383148124
---
=> fix(useScrollLock): detect parent with overflow auto

packages/integrations/useAsyncValidator/index.ts
I made a stupid mistake on #2761 😔, my solution is based on my comment on the issue https://github.com/vueuse/vueuse/issues/2497#issuecomment-1416852748. 
I try to get the constructor from the default attribute (it exists on SSR mode), if doesn't exist use Schema like before PR. 
Nothing broke because it didn't work before, but it is good to fix one. 
---
=> fix(useAsyncValidator): incorrect condition for choosing constructor

packages/core/onClickOutside/index.md
The section directive on the vueuse click-outside page mentions how to use directives, but does not specify how to set parameters of directives. This pr is to make up for this part of the example.
在 vueuse click-outside 页面 directive 章节中有提到如何使用指令，但并没有说明如何设置指令的参数，这个 pr 是为了补上这一部分示例。
https://vueuse.org/core/onClickOutside/#directive-usage
---
=> docs(onClickOutside): add the click outside sample code.

packages/core/useCssVar/index.test.ts, packages/core/useCssVar/index.ts, packages/core/usePointerSwipe/demo.vue
=> feat(useCssVar): introduce `observe` option

packages/.vitepress/plugins/markdownTransform.ts, packages/vite.config.ts, playgrounds/nuxt3/nuxt.config.mjs, playgrounds/vite/vite.config.ts, scripts/build.ts, scripts/export-size.ts, scripts/post-docs.ts, scripts/publish.ts, scripts/rollup.config.ts, scripts/utils.ts, vitest.config.ts
`
import path from 'path'
`
->
`
import path from 'node:path'
`
By theway, we can more clearly identify which modules were imported from Node
=> chore: use `node:` protocol when importing built-in modules

packages/core/useBrowserLocation/demo.vue, packages/core/useBrowserLocation/index.ts, packages/shared/utils/index.ts
closes #1125
Two-way binding of `window.location`. It's readonly before. After this PR, it can be changed by user.
I think the returning value of `useBrowserLocation` should be a ref map. But ATM let it be a reactive (maybe it can be refactored in the next major version.)
---
=> feat(useBrowserLocation): two-way binding

packages/integrations/useIDBKeyval/index.md, packages/integrations/useIDBKeyval/index.test.ts, packages/integrations/useIDBKeyval/index.ts
Adds an `isFinished` ref returned from `useIDBKeyval` to indicate if that data has finished loading from Indexed DB. Along with a new option `writeDefaults` which allows you to not write the default value to the indexedDb 
This is a breaking change, but I was looking to keep this consistent with other composable in the repo. An alternative is to create a `onSuccess` callback and manage this isLoading ref outside of vueuse. 
---
=> feat(useIDBKeyval)!: return format changed, add `isFinished`

packages/integrations/useAxios/index.test.ts, packages/integrations/useAxios/index.ts
=> fix(useAxios)!: `error` should return type `unknown`

packages/shared/createGlobalState/index.ts
[`createGlobalState`](https://vueuse.org/shared/createGlobalState/) is nice and I wanted to use it for configuring [Anu](https://anu-vue.netlify.app/) instance when vue uses it as a plugin. However, `createGlobalState` doesn't accepts any initial config for initializing global state based on provided config.
This is really simple change but don't forget to review it 👀 
---
=> feat(createGlobalState): allow passing initial args

packages/metadata/scripts/update.ts, packages/nuxt/index.ts, scripts/build.ts, scripts/publish.ts, scripts/release.ts
import assert from 'assert'
import { execSync } from 'child_process'
->
import assert from 'node:assert'
import { execSync } from 'node:child_process'
=> chore: use node: protocol when importing built-in modules

packages/core/useTransition/index.md, packages/core/useTransition/index.test.ts, packages/core/useTransition/index.ts
Expose underlying transition logic from `useTransition` to allow for manually transitioning a ref between values. See more information here https://github.com/vueuse/vueuse/issues/2689.
---
=> feat(useTransition): expose transition utility for manual control

packages/core/useCycleList/demo.vue, packages/core/useCycleList/index.md, packages/core/useCycleList/index.test.ts, packages/core/useCycleList/index.ts
Allow useCycleList to receive a "ref" list value, this will allow the cycle list to be reactive
This also adds unit tests for useCycleList
---
=> feat(useCycleList): allow receiving reactive list

packages/core/useFullscreen/index.ts
Apple uses a different webkit function to enter fullscreen. See [HTMLVideoElement](https://developer.apple.com/documentation/webkitjs/htmlvideoelement) and [webkitEnterFullScreen](https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1630649-webkitenterfullscreen) documentation.
=> fix(useFullscreen): handle Safari iOS

packages/core/useIdle/index.md, packages/core/useIdle/index.ts
Add a functionality to reset the timer in useIdle so it can trigger multiple times without user input.
Currently this behaviour can be mimicked by triggering a fake event in the DOM, but this requires knowledge of internals and may have side-effects.
'lastActive' intentionally left untouched when resetted.
Small example included in docs.
---
=> feat(useIdle): add `reset` capability

packages/integrations/useAxios/index.test.ts, packages/integrations/useAxios/index.ts
=> feat(useAxios): added `onFinish` callback

packages/core/useDark/index.ts
Sometimes you want to hook into the onChanged functionality when the mode is changed, but you still want the default handler to happen.  Currently that is not possible. 
An example of what I was trying to do that caused me to need this functionality:
```js
const isDark = useDark({
onChanged(dark?: boolean) {
cookies.set('darkmode', dark ? 1 : 0, { path: '/', sameSite: true });
},
});
```
Currently, this would cause dark mode to not function because the onChanged removes the default functionality of adding a class to the html tag.
Instead I had to do the following:
```js
const isDark = useDark({
onChanged(dark?: boolean) {
if (dark) {
document.querySelector('html')?.classList.add('dark');
} else {
document.querySelector('html')?.classList.remove('dark');
}
cookies.set('darkmode', dark ? 1 …
```
=> feat(useDark): passthrough default handler from `useColorSchema`

packages/shared/reactiveOmit/index.md, packages/shared/reactiveOmit/index.test.ts, packages/shared/reactiveOmit/index.ts
=> feat(reactiveOmit): add predicate parameter

packages/core/useIntersectionObserver/demo.vue, packages/core/useIntersectionObserver/index.ts
Sometimes we want to conditionally enable or disable `useIntersectionObserver`. In the past, we could only use a watch function to enable it when `enabled` is `true` and clean it up when `enabled` is `false`.
```vue
import { useIntersectionObserver } from '@vueuse/core';
import { computed, ref, watch } from 'vue';
const elRef = ref<HTMLElement>();
const enabled = computed(() => {
// Conditional
return true; // or false
});
let stop: ReturnType<typeof useIntersectionObserver>['stop'];
watch(enabled, enabled => {
if (!enabled) {
stop?.();
} else {
({ stop } = useIntersectionObserver(elRef, () => {
// Do something
}));
}
});
</script>
```
With the introduction of support for enabled: MaybeRef<boolean>, we can simplify our code:
```vue
import …
```
=> feat(useIntersectionObserver): support for `Pausable` interface

packages/core/createReusableTemplate/index.md, packages/core/createReusableTemplate/index.test.ts, packages/core/createReusableTemplate/index.ts, packages/core/index.ts
migrated from [vue-reuse-template](https://github.com/antfu/vue-reuse-template)
close https://github.com/antfu/vue-reuse-template/issues/2
=> feat(createReusableTemplate): new function

packages/core/useAsyncState/index.test.ts, packages/core/useAsyncState/index.ts
Add initialized in the [useAsyncState](https://vueuse.org/core/useAsyncState/).
Sometimes, using only `isReady` or `isLoading`  is not very convenient. 
For example, in scenarios where multiple events rely on state being triggered, and the `execute` may not have been completed yet.
We need to use `await initialized` to ensure that subsequent operations are executed only after the state has been initialized.
```vue
<script lang="ts" setup>
const { initialized, state } = useAsyncState(p1, 0, { immediate: true })
const eventA = async () => {
await initialized.value
// do something with the state...
}
const eventB = async () => {
await initialized.value
// do something with the state ...
}
</script>
```
=> feat(useAsyncState): add support directly await

packages/core/useEventSource/index.ts
feat(useEventSoure): allow optional satring | URL type for url arg
---
This MR allows the url arg type for useEventSource to be of type string or URL, allowing for backward compatibility and a light touch green field MR.
No other changes are needed, as `new EventSource()` accepts a string for URL type as the url arg.
=> feat(useEventSource): allow optional string | URL type for url arg

packages/shared/refAutoReset/index.test.ts, packages/shared/refAutoReset/index.ts
Now you can use MaybeRefOrGetter as the reset-to value.
```js
refAutoReset(() => 'default', 1000)
```
=> feat(refAutoReset): support maybe-ref as value

packages/core/useMouse/index.md
Remove duplicate text and code block in useMouse compsable documentation page. 
The following is displayed twice: 
"Touch is enabled by default. To only detect mouse changes, set touch to false. The dragover event is used to track mouse position while dragging."
"const { x, y } = useMouse({ touch: false })"
=> docs(useMouse): remove duplicate text on composable documentation

packages/integrations/useAxios/index.ts
When the `request aborted`, the `response `  is `undefined`, it causes Cannot read properties of undefined (reading '`data`')
=> fix(useAxios): bail out on request abort

packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
=> fix(useStorage): fix undefined defaults

packages/core/usePointerSwipe/demo.vue, packages/core/usePointerSwipe/index.ts
=> feat(usePointerSwipe): add `disableTextSelect` option 

packages/core/useOffsetPagination/index.ts
=> fix(useOffsetPagination): don't mutate props when it's readonly

packages/core/useInfiniteScroll/index.ts
=> feat(useInfiniteScroll): add the `canLoadMore` option

packages/core/useTitle/index.ts
- can pass stopOnUnmounted to stop watchers when the component unmount
fix #3568
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on …
=> feat(useTitle): restore title on unmounted

packages/core/onLongPress/index.test.ts, packages/core/onLongPress/index.ts
=> feat(onLongPress): add `distanceThreshold` option

packages/.vitepress/theme/styles/demo.css, packages/.vitepress/theme/styles/vars.css
The previous commit modified some CSS variables, causing the button's background to become transparent on hover. This commit applies appropriate CSS variables.
=> fix: vitepress style

packages/core/useVirtualList/component.ts
=> fix(useVirtualList): ensure component applies overflow style

packages/components/README.md, packages/electron/README.md, packages/firebase/README.md, packages/integrations/README.md, packages/math/README.md, packages/nuxt/README.md, packages/router/README.md, packages/rxjs/README.md
=> docs: fix install command code block

packages/core/useMouse/demo.vue
=> fix: handle Touch class compatibility for Firefox

packages/core/useDropZone/index.ts
=> fix(useDropZone): avoid circular reference

packages/core/useWebWorker/index.md
=> docs(useWebWorker): escape table divider

packages/core/useElementBounding/index.ts
=> fix(useElementBounding): trigger by css or style

packages/shared/computedEager/index.md, packages/shared/computedEager/index.test.ts, packages/shared/computedEager/index.ts
=> fix(computedEager): adapt to changes in vue3.4+

packages/.vitepress/config.ts
=> docs: include VP hashmap.json file in sw precache manifest

packages/core/useGamepad/index.ts
Ensures useGamepad explicitly exposes gamepads indexes.
Fixes #3652
=> fix(useGamepad): explicitly ensure gamepad index is available

packages/core/useGamepad/index.ts
Fix updating of gamePad data.
Tested with multiple controllers, both Xbox One and Stadia.
=> fix(useGamepad): improve data updating logic

packages/core/useFileSystemAccess/demo.vue, packages/core/useFileSystemAccess/index.ts
---
Fix the bug #3779 that prevent the content of a modified file to be updated in `useFileSystemAccess`.
Calling `updateData()` now succeeds and the modified file content is correctly exposed.
My first PR, be gentle :wink:
=> fix(useFileSystemAccess): updateData on modified file

packages/shared/utils/filters.ts, packages/shared/utils/index.test.ts
=> feat(throttleFilter): support object as argument

packages/core/useMutationObserver/index.test.ts, packages/core/useMutationObserver/index.ts
=> feat(useMutationObserver): allow multiple targets

packages/core/useAnimate/index.ts
=> fix(useAnimate): immediate option set false not working

packages/core/useCurrentElement/index.md, packages/core/useCurrentElement/index.test.ts, packages/core/useCurrentElement/index.ts
=> feat(useCurrentElement): Allow get current element from a specific component

packages/shared/syncRefs/index.md
=> docs(syncRefs): add example of multiple targets

packages/core/useEventSource/index.md, packages/core/useEventSource/index.ts
=> feat(useEventSource): add `autoReconnect` and `immediate` to options, update typings

packages/core/useMounted/index.ts
=> fix(useMounted): compatible with vue2.7

packages/integrations/useIDBKeyval/index.ts
=> fix(useIDBKeyval): use toRaw instead of overriding the original object

packages/core/useActiveElement/index.ts
=> fix(useActiveElement/useFocusWithin): replace computedWithControl with locally tracked ref

packages/core/useClipboard/index.ts
No, it's hard to simulate a browser like wechat browser
There are a lot of built-in browsers (Chinese app likes them), which does not implement permission api return value, for example on latest Wechat client  8.0.47, the demo of the usePermission page looks like this:
That is because when calling with `usePermission('xxx')`, these browsers return `undefined` (including the 'clipboard-write' and 'clipboard-read' used in `useClipboard`
When the value is undefined, we'd better treat it as `denied`, e.g. wechat browser just denied it with out any asking for security reasons:
The issue is included in https://github.com/vueuse/vueuse/pull/3379 as a feature for falling back to legacy if possible.
=> fix(useClipboard): fix issue when permission is not defined

packages/core/useMounted/index.ts
=> fix(useMounted): The second argument in vue2.7 should be `undefined`

packages/nuxt/ssr-plugin.mjs
=> fix: opt in to `import.meta.*` properties

packages/shared/useIntervalFn/index.ts
The documentation for the option `immediateCallback` in `useIntervalFn` was very misleading, making me search for a solution for a long time. Actually, `immediateCallback` already _was_ the solution, but the documentation made me think otherwise: `immediateCallback` decides whether the callback is called immediately **after `resume` is called**. The former documentation said "_Execute the callback immediate after calling this function_", leaving it unclear what is meant by "this function"  (I assumed it referred to the actual composable, `useIntervalFn`, but that's not the case).
Thank you for this absolutely lifesaving library :heart:
=> Clarify code documentation in useIntervalFn

packages/nuxt/index.ts
=> feat(nuxt): Add router addon to nuxt module

packages/core/useEventSource/index.ts
=> feat(useEventSource): return `lastEventId`

packages/core/useGamepad/index.md
=> docs(useGamepad): fix missing `.value` in example

packages/core/useElementSize/index.ts
=> fix(useElementSize): use getBoundingClientRect get element size on SVG

packages/core/useWebWorkerFn/index.md, packages/core/useWebWorkerFn/index.ts, packages/core/useWebWorkerFn/lib/createWorkerBlobUrl.ts, packages/core/useWebWorkerFn/lib/depsParser.ts
**Description**
This PR fixes #2005 and also addresses the issue with #3316 . The implementation provides a solution that deviates slightly from [alewin/useWorker](https://github.com/alewin/useWorker), due to a known issue with `isoworker`. Specifically, the localDependencies feature has been temporarily removed in their implementation. However, recognizing the high anticipation for this feature, I've introduced a simplified method inside`depsParser` to enable its functionality.
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become …
=> feat(useWebWorkerFn): support local function dependencies

packages/shared/createInjectionState/index.md, packages/shared/createInjectionState/index.ts
=> feat(createInjectionState): add defaultValue option

packages/core/useWebSocket/index.ts
=> fix(useWebSocket): urlRef changes were not being tracked

packages/router/useRouteParams/index.test.ts, packages/router/useRouteParams/index.ts
=> feat(useRouteParams): support optional params

packages/shared/useTimeout/index.test.ts, packages/shared/useTimeout/index.ts
=> feat(useTimeout): target support reactivity

packages/core/useScrollLock/index.ts
=> fix(useScrollLock): function unlock does not work

packages/core/useGamepad/index.ts
=> fix(useGamepad): avoid spread to fix gamepad state

packages/core/useFileDialog/index.ts
=> fix(useFileDialog): check if input value exists before trigger onChange

packages/core/useTextareaAutosize/index.ts
=> fix(useTextareaAutosize): onResize callback fires not only on resize

packages/shared/useThrottleFn/index.ts
adds default values into docs notation as they are not explicitly visible in docs web https://vueuse.org/shared/useThrottleFn/
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first …
=> docs: adds default values to useThrottleFn notation

packages/core/useDisplayMedia/index.ts
---
When the user stops sharing the screen, we need to stop the stream. Hence I've added an event listener to catch when the track ends, and call the stop function.
Steps to reproduce the bug:
1. Open Google Chrome (on mac).
2. Start sharing screen (select a window, not just a tab).
3. Look for the small notification that says "vueuse.org is sharing a window" (1. in the attachment).
4. Click "Stop sharing".
5. Before this fix the stream turns black, but is still in enabled state (2. in the attachment). After this fix it is properly stopped.
=> fix(useDisplayMedia): stop stream when screen is not shared anymore

packages/core/useScroll/index.ts
=> fix(useScroll): sync scroll val to internal state #3809

packages/core/useVirtualList/index.ts
=> fix(useVirtualList): add containerRef to watch list

packages/core/useEventListener/index.test.ts, packages/core/useFetch/index.test.ts
type `SpyInstance ` is deprecated
docs: https://vitest.dev/guide/migration#mock-types-4400
=> types(vitest): modify `SpyInstance` to `MockInstance`

packages/core/useMutationObserver/index.ts
=> fix(useMutationObserver): stop watching before cleaning up

packages/.vitepress/theme/components/HomeTeam.vue
=> docs: improve the team member layout style

packages/core/useGamepad/components/Gamepad.vue
there may be cases where hapticActuators is not present, which would cause an error in this code.
=> fix(useGamepad): handle case where hapticActuators is not present

packages/core/useMouseInElement/index.ts
=> fix(useMouseInElement): el.getBoundingClientRect is not a function

packages/core/useCssVar/index.test.ts, packages/core/useCssVar/index.ts
=> feat(useCssVars): remove property on null/undefined

packages/core/useSpeechRecognition/index.ts
fix [#4065](https://github.com/vueuse/vueuse/issues/4065)
=> feat(useSpeechRecognition): support `maxAlternatives` option

packages/core/useIntersectionObserver/index.ts
resolve #2184
According to the [MDN documentation on the IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#threshold), the default value of `threshold` should be 0. In #115, I did not find any discussion regarding `threshold` defaulting to 0.1. Should we maintain consistency with the IntersectionObserver API's default value? However, this would be a breaking change.
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#threshold
=> fix(useIntersectionObserver)!: update the `threshold` default to 0

packages/core/useDraggable/component.ts, packages/core/useDraggable/index.ts
=> feat(useDraggable): add `buttons` option

packages/core/useEventListener/index.ts
=> fix(useEventListener): event target can be an empty ref/getter

packages/core/useStorage/index.ts
=> feat(useStorage): conditionally use event based on the used storage backend

packages/shared/until/index.ts
=> fix(until): cleanup at next tick to avoid memory leak

packages/core/useWindowSize/index.test.ts, packages/core/useWindowSize/index.ts
=> feat(useWindowSize): add ability to get outer sizes of the window

packages/core/useElementBounding/index.ts
=> feat(useElementBounding): add `updateTiming` option

packages/shared/isDefined/index.ts
- TS matches overloads by finding the topmost signature that's compatible with the parameters
- instances of `ComputedRef` were matching to the overload with the `Ref` parameter rather than `ComputedRef`
- later in the scope where `isDefined` was used, the type was still narrowed, but to something that Typescript might find hard to resolve in reasonable time: `ComputedRef<SomeType | null> & Ref<SomeType>` rather than `ComputedRef<SomeType>`
- this made it difficult for `get` to resolve the types starting in v10.11.1 with [this change](https://github.com/vueuse/vueuse/commit/19f2ad34e938b6a0d03fc227bf817dc5f41f25cc).
- something to do with `get` asking for `MaybeRef`
- Sorry for no reproduction, there's no TS StackBlitz for VueUse, otherwise I would've forked off of it!
=> fix(isDefined): moves most specific overload to the top

packages/integrations/useChangeCase/index.ts
**changeCaseTransforms** will return a null object of funcions becasue on the non-dev build the functions names comes minified/mangles, 
```
changeCase VALUES 
(14) [ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ]
ƒ ir(t,e)
ƒ yt(t,e)
ƒ lr(t,e)
ƒ sr(t,e)
ƒ ur(t,e)
ƒ Oe(t,e)
ƒ or(t,e)
ƒ ar(t,e)
ƒ cr(t,e)
ƒ dr(t,e)
ƒ fr(t,e)
ƒ Et(t)
ƒ Kt(t)
ƒ hr(t,e)
```
making the v.name.endsWith('Case') never maching.
Not sure this is the best aproach to fix. changed Object.values to use Object.entries in other to be able to use theyh object key instead of the function name.
Issue: https://github.com/vueuse/vueuse/issues/4139
Duplicate PR: https://github.com/vueuse/vueuse/pull/4140
=> fix(useChangeCase): use the exported key for filter

packages/router/useRouteHash/index.test.ts, packages/router/useRouteHash/index.ts, packages/router/useRouteParams/index.test.ts, packages/router/useRouteParams/index.ts, packages/router/useRouteQuery/index.test.ts, packages/router/useRouteQuery/index.ts
Resolves #4112.
<details>
<br>
> …
=> fix(useRouteHash, useRouteParams, useRouteQuery): fix effect triggering multiple times

packages/shared/computedWithControl/index.test.ts, packages/shared/computedWithControl/index.ts
---
Since vue 3.4, [`computedGetter`](https://vuejs.org/api/reactivity-core.html#computed) is of type `(oldValue?) => T`. Similar behavior could be easily implemented for `computedWithControl`. Related: https://github.com/vuejs/rfcs/discussions/594
=> fix(computedWithControl): allow optional oldValue parameter in computedWithControl getter

packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
=> fix(useStorage): sync within the same document

packages/core/usePermission/index.ts
=> fix(usePermission): state setting

packages/core/useDropZone/index.ts
=> fix(useDropZone): ensure files ref is updated even without onDrop callback

packages/core/useCssVar/index.ts
=> fix(useCssVar): Replace getComputedStyle with direct style property access

packages/core/useWebSocket/index.ts
This PR addresses issue #4160.
It verifies when doing an autoReconnect that the ws and wsRef are pointing to the same object.
If the wsRef is pointing to something new, we should not try and reconnect the ws WebSocket, since it is considered stale.
=> fix(useWebSocket): only reconnect if is the current ws socket

packages/core/useWebSocket/index.ts
This ticket is a PR for  issue #4163
autoReconnect should reset retries once a connection is successfully established and the guard you be checked before increasing retried count.
=> fix(useWebSocket): should reset retry count when connection is established

packages/core/computedAsync/index.test.ts, packages/core/computedAsync/index.ts
---
When no initial value is provided, the return type was `Ref<T>` instead of `Ref<T | undefined>`.
=> fix(computedAsync): type signature

packages/core/useMouseInElement/index.ts
=> fix(useMouseInElement): allow `el` to be instanceof Element

packages/core/onClickOutside/index.ts
=> fix(onClickOutside): make `ignore` accept reactive values

packages/core/useDropZone/index.md, packages/core/useDropZone/index.ts
=> feat(useDropZone): add multiple prop to control multi-file drop

packages/shared/useArrayFilter/index.test.ts, packages/shared/useArrayFilter/index.ts
=> fix(useArrayFilter): match type to Array.prototype.filter

packages/shared/computedEager/index.md
---
The wording of the note regarding `computedEager` vs `computed` in Vue v3.4 can be improved
=> docs: wording

packages/shared/watchImmediate/index.md
Small PR to correct a typo in the docs for this file. `nestedObject` should be `obj` in the watchImmediate docs example code snippet.
=> docs(watchImmediate): corrected variable name in example

packages/core/useMediaControls/index.ts
=> feat(useMediaControls): add playback error event 

packages/core/useDevicesList/index.ts
In Safari the reject/not allowed action throws an NotAllowedError in the `navigator.mediaDevices.getUserMedia(constraints)`.
This also happens if you press the x on Chrome and you get an `NotAllowedError: Permission dismissed`.
This is not handled within the `ensurePermissions()` function, so added a try catch to collect and set always `false` on error.
=> fix(useDevicesList): handle NotAllowedError on reject/close

packages/core/useBreakpoints/breakpoints.ts, packages/core/useBreakpoints/index.md
=> feat(useBreakpoints): add breakpoints for ElementUI/ElementPlus

packages/core/useDropZone/index.ts
fixes: #4302 
<details>
<br>
> …
=> fix(useDropZone): remove file kind restriction

packages/nuxt/README.md
=> docs: update nuxt readme to show all disabled functions

packages/core/useMouse/index.ts
Once the mousemove updates the values of x and y, it implies that the current page scroll position will also be recorded to serve as the initial value for the next scrolling calculation.
fix: [#4180 ](https://github.com/vueuse/vueuse/issues/4180)
=> fix(useMouse): record the previous scroll value

packages/core/useFetch/index.ts
When I call `createFetch` with a `baseUrl` that ends with a slash, and call `useFetch` with a path that starts with a slash, it will send a request like `https://example.com//api/something`.
This PR resolves this problem by checking if both the start and end have slashes, and removing the starting slash.
```javscript
function joinPaths(start: string, end: string): string {
if (!start.endsWith('/') && !end.startsWith('/')) {
return `${start}/${end}`
}
if (start.endsWith('/') && end.startsWith('/')) {
return `${start.slice(0, start.length - 1)}${end}`
}
return `${start}${end}`
}
```
=> fix(useFetch): ensure single slash

packages/router/useRouteParams/index.test.ts, packages/router/useRouteParams/index.ts, packages/router/useRouteQuery/index.test.ts, packages/router/useRouteQuery/index.ts
Resolves https://github.com/vueuse/vueuse/issues/4281
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and …
=> fix(useRouteParams, useRouteQuery): effect triggers twice with object getter as watch source

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
=> feat(useFetch): infer 'json' type for array payloads

packages/core/useSwipe/index.ts
=> fix(useSwipe): allow vertical scrolling during swipe

packages/core/onClickOutside/index.ts
=> feat(OnClickOutside): support component with fragments

packages/integrations/useSortable/index.md, packages/integrations/useSortable/index.ts
fix: #4222 #3724 
<details>
<br>
> …
=> fix(useSortable): wrong order of elements

packages/core/useIntersectionObserver/demo.vue, packages/core/useIntersectionObserver/index.md
- [vueuse issue](https://github.com/vueuse/vueuse/issues/4172) :bug: 
- [Nuxt v4 issue](https://github.com/nuxt/nuxt/issues/28694)
---
Due to stricter types planned on the upcoming v4 of Nuxt, the demo example needs to be updated.
You can [look at this Nuxt issue](https://github.com/nuxt/nuxt/issues/28694) for reference.
The Typescript issue occurs when `future: { compatibilityVersion: 4 },` is applied in the `nuxt.config.ts` file.
The change is not Nuxt related though, it concerns anyone.
It's simply applying an extra check on the `IntersectionObserverCallback` argument to ensure we handle the possibility of having an `entry` being `undefined` instead of immediately de-structuring.
[Reproduction link of the issue](https://stackblitz.com/edit/nuxt-3-vueuse-motion-pmteh2?file=client%2Fapp.v …
=> docs(useIntersectionObserver): update syntax to handle stricter types

packages/core/useWebSocket/index.test.ts
Adds a few tests for `useWebSocket`.
Unfortunately, this creates a mock `WebSocket` for now. We could possibly use something like MSW in future.
I know we have a _lot_ of PRs to review right now, so this is ofc **a low priority PR**. feel free to ignore it for a while! I've also not contributed to this codebase in a long time, so its possible much of this is nonsense - let me know if it is
=> test: add useWebSocket tests

packages/core/useClipboardItems/index.md
Fixed an error in the usage of the Blob constructor when creating a ClipboardItem. 
The original code nested `{ type: mime }` in Array, which resulted in improperly generated Blob content.
modify
```javascript
new ClipboardItem({
[mime]: new Blob(['\'<b>HTML content</b>\'', { type: mime }]),
})
```
to
```javascript
new ClipboardItem({
[mime]: new Blob([`<b>HTML content</b>`], { type: mime }),
})
```
=> docs(useClipboardItems): fix example

packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.test.ts, packages/core/useWebSocket/index.ts
=> feat(useWebSocket): introduce `autoConnect` options to control auto connections on url changes

packages/core/useDropZone/index.ts
=> fix(useDropZone): update type to allow readonly array param

packages/.vitepress/config.ts, packages/.vitepress/theme/components/TeamMember.vue, packages/contributors.ts
=> docs: add bluesky and replace twitter with x branding

packages/core/useWebSocket/index.ts
Allow to close web-socket connection inside web-worker.  The condition is basically the same as in open() function
=> fix(useWebSocket): close socket connection inside webworker fix

packages/core/useFetch/index.ts
=> fix(useFetch): handle empty payload

packages/core/useTextDirection/index.test.ts, vitest.config.ts
=> test(useTextDirection): add basic test suits

packages/core/usePermission/demo.vue
---
Just a small documentation style change. 
As a common use-case of permissions API, I thought it would make sense to include it in the demo component
=> docs(usePermission): add `geolocation` to demo

packages/core/useDraggable/index.md, packages/core/useDraggable/index.ts
resolves #3755
<details>
<br>
> …
=> docs(useDraggable): example for `preventDefault: true`

packages/core/useDropZone/demo.vue, packages/core/useDropZone/index.md, packages/core/useDropZone/index.ts
=> fix(useDropZone): validate all file types individually when dropping multiple files

packages/core/useClipboard/index.ts, packages/core/useClipboardItems/index.ts
Currently calling `useClipboard()` will immediately start timer intended for resetting `copied` value. This pull request aims avoid doing that as it can be somewhat costly during init when composable is extensively used.
I believe there is still room for improvement by making all `useClipboard` instances share common `usePermission` states. As I understand currently new ones are created for every `useClipboard` call, but I could also be mistaken. Any thoughts or guidance on this would be appreciated.
=> fix(useClipboard,useClipboardItems): avoid running "copied" timeout during initialization

packages/core/useFocusWithin/index.test.ts, packages/core/useFocusWithin/index.ts
=> fix(useFocusWithin): correctly track the state when switching the focus of elements in the same container

packages/.vitepress/config.ts, packages/.vitepress/theme/components/Home.vue, packages/.vitepress/theme/components/HomeContributors.vue, packages/.vitepress/theme/components/HomeSection.vue, packages/.vitepress/theme/components/HomeSponsors.vue, packages/.vitepress/theme/components/HomeTeam.vue, packages/.vitepress/theme/components/TeamMember.vue, packages/.vitepress/theme/components/TeamMembersGrid.vue, packages/contributors.ts, packages/team.md
The new team page is under `/team`. I also introduced Team Emeriti for inactive team members. 
I picked members who didn't contribute in the past year. Please feel free to let me know if you have any questions or doubts. Moving to "Team Emeriti" doesn't change anything other than better communication with the community. You are more than welcome to come back anytime to help with VueUse. We sincerely appreciate your previous contributions to the team and projects.
/cc Emeriti Candiates:
- @egoist 
- @webfansplz
- @anteriovieira 
- @cawa-93 
- @scottbedard 
- @sibbng (close #4431)
- @okxiaoliang4 
- @lstoeferle
=> docs: new team page, introduce Team Emeriti

packages/core/useInfiniteScroll/demo.vue, packages/core/useInfiniteScroll/index.md
See #4000
- [-] Ideally, include relevant tests that fail without this PR but pass with it.
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, …
=> docs(useInfiniteScroll): add warning and examples for `canLoadMore`

packages/core/useCloned/index.md, packages/core/useCloned/index.test.ts, packages/core/useCloned/index.ts
reference: #4393 
Add a new `isModifed` feature to `useCloned`. This reactive attribute tracks whether the cloned value has been modified.
=> feat(useCloned): return `isModified`

packages/core/useMediaControls/index.md
`useTemplateRef` is the preferred approach for direct DOM access, as recommended in the [Vue.js documentation](https://vuejs.org/guide/essentials/template-refs.html)
=> docs(useMediaControls): use useTemplateRef instead of ref

packages/core/useLocalStorage/index.ts, packages/core/useSessionStorage/index.ts, packages/core/useStorage/index.md, packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
=> feat(useStorage): make storage key reactive

packages/core/useDevicePixelRatio/index.ts
=> refactor(useDevicePixelRatio): use `useMediaQuery`

packages/core/useEventListener/index.test.ts, packages/core/useEventListener/index.ts
=> feat(useEventListener): make all parameters arrayable and reactive

packages/core/onClickOutside/index.ts, packages/core/useBluetooth/index.md, packages/core/useBluetooth/index.ts, packages/core/useBroadcastChannel/index.ts, packages/core/useDisplayMedia/index.ts, packages/core/useMediaControls/index.ts, packages/core/useMediaQuery/index.ts, packages/core/useScriptTag/index.ts, packages/guidelines.md, packages/shared/useDebounceFn/index.md, packages/shared/useThrottleFn/index.md
=> feat: use `useEventListener` where it was not being used

packages/integrations/useAsyncValidator/index.test.ts, packages/rxjs/watchExtractedObservable/index.test.ts, packages/shared/utils/index.test.ts
Three things in tests:
- Very minor, but a couple of tests were logging out to `stdout`. This simply changes them to no longer do so.
- Stubs out `console.warn` through `vi.spyOn` rather than an assignment. This allows `vi.restoreAllMocks()` to restore it later
- Passes a vitest options as 2nd arg in `it`. passing it as the third arg is deprecated and will stop working at some point
=> test(core): suppress some output in test runs

packages/core/useFileDialog/index.test.ts, packages/core/useFileDialog/index.ts
=> feat(useFileDialog): add initialFiles option

packages/core/useVirtualList/index.test.ts, packages/core/useVirtualList/index.ts
=> fix(useVirtualList): allow readonly arrays as input

packages/core/useClipboard/index.browser.test.ts, packages/core/useClipboard/index.test.ts, packages/core/useClipboard/index.ts
fixes https://github.com/vueuse/vueuse/issues/3813
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and …
=> feat(useClipboard): should fall back to legacy clipboard when read/write fails

pnpm-lock.yaml, pnpm-workspace.yaml
CI is failing at the minute because `nlx playwright install` will install the _latest_ playwright browsers. These then mismatch the version of playwright we have installed (which tries to resolve older browser versions).
For now, this upgrades playwright to use the same version.
Later, we should investigate how to constrain `nlx playwright install` to the same version so it has to be manually updated in future.
=> chore: upgrade playwright

.github/workflows/ci.yml
Uses `pnpm exec` so we always call the same playwright version being used in the tests.
=> chore: use local playwright

packages/core/createReusableTemplate/index.md, packages/core/createReusableTemplate/index.ts
Before this PR, `createReusableTemplate` always treated all props as attributes and made the props appear on the DOM. In some cases, it might not be desired. This PR allows explicit provide the props to prevent those props to be leaking on the DOM.
=> feat(createReusableTemplate): explicit props

packages/core/useFullscreen/index.ts
=> refactor(useFullscreen): use documentElement directly

packages/core/useElementVisibility/index.md
Hey there,
This fixes the documentation for the new `rootMargin` option in `useElementVisibility`.
=> docs(useElementVisibility): Fix rootMargin docs

packages/core/useSpeechRecognition/index.ts
=> fix(useSpeechRecognition): improve start and stop method behavior

packages/nuxt/index.ts
=> fix(nuxt): check if packages exist in any layer

packages/core/useTimeoutPoll/index.test.ts, packages/core/useTimeoutPoll/index.ts, packages/shared/useTimeoutFn/index.test.ts, packages/shared/useTimeoutFn/index.ts
=> feat(useTimtoutFn,useTimeoutPoll): align behavior

packages/.vitepress/plugins/markdownTransform.ts
=> docs: preserve character after function names when linkifying

packages/core/useCssVar/index.test.ts, packages/core/useCssVar/index.ts
resolves #4493 
<details>
<br>
> …
=> fix(useCssVar): new Behavior

packages/shared/useDateFormat/index.md, packages/shared/useDateFormat/index.test.ts, packages/shared/useDateFormat/index.ts, vitest.config.ts
=> feat(useDateFormat): add `z...zzzz` for timezone information

packages/core/useElementVisibility/index.test.ts, packages/core/useElementVisibility/index.ts
Implement: #4007
<details>
<br>
> …
=> feat(useElementVisibility): add `once` options

packages/core/useRafFn/index.test.ts, packages/core/useRafFn/index.ts
=> feat(useRafFn): add `once` option

packages/core/useTitle/index.ts
One of the tasks in #4548:  
This PR replaces [`tryOnBeforeUnmount`](https://vueuse.org/shared/tryOnBeforeUnmount) with [`tryOnScopeDispose`](https://vueuse.org/shared/tryOnScopeDispose).
=> refactor: replace `tryOnBeforeUnmount` with `tryOnScopeDispose`

packages/shared/createInjectionState/index.test.ts, packages/shared/isDefined/index.test.ts, packages/shared/reactify/index.test.ts, packages/shared/syncRef/index.test.ts, packages/shared/until/index.test.ts, packages/shared/useLastChanged/index.ts, packages/shared/watchTriggerable/index.test.ts, packages/shared/whenever/index.test.ts
This switches various tests and `useLastChanged` to use a `shallowRef` rather than a `deepRef` on primitive values (such as numbers).
Achieved through `npx eslint --fix packages/shared`, using the `no-primitive-shallow` lint rule (currently on a branch).
=> refactor: move to `shallowRef` in shared utilities

packages/core/useDocumentVisibility/index.ts
Uses `shallowRef` for `visibilityState` since it is a string.
=> refactor(useDocumentVisibility): use `shallowRef` for primitives

packages/core/useCloned/index.ts
Switches to `shallowRef` for `isModified`, since it is a boolean.
=> refactor(useCloned): use `shallowRef` for primitives

packages/core/useFetch/index.ts
Uses `shallowRef` for status codes (nullable numbers).
=> refactor(useFetch): use `shallowRef` for status codes

packages/core/useElementSize/index.ts
Uses `shallowRef` for the element `height` and `width` (numbers).
=> refactor(useElementSize): use `shallowRef` for height and width

.vscode/settings.json
The experimental prefix is no longer needed as useFlatConfig is now officially supported in ESLint. This update ensures that the latest VSCode + ESLint environment applies the correct settings.
=> chore: remove 'experimental' from 'eslint.experimental.useFlatConfig' in VSCode settings

packages/core/useAnimate/index.browser.test.ts
Adds a test for asserting that keyframes can be passed as a ref and will trigger an update when they change.
Depends on #4619
=> test(useAnimate): add test for keyframe reactivity

packages/core/useClipboard/index.ts
Fallback to document.getSelection() on read permission prompt as intended instead of consuming NotAllowedError
---
When `options.read === true` and the `'clipboard-read'` permission value is `'prompt'`, thus `isAllowed()` returns `true` and an attempt to use the Clipboard API is made, before the user can press either Allow or Deny, the `Promise` returned by `navigator.clipboard.readText()` can be rejected with a `NotAllowedError`. This was covered in #4512, but a wrong syntax combination was used, consequently, the **fallback to `legacyRead()` didn't happen**, and an **unhandled rejection with a NotAllowedError was generated** in the console. This PR handles the rejection by falling back as intended.
See [reply](https://github.com/vueuse/vueuse/pull/4512/files#r1962169204) to where this …
=> fix(useClipboard): unhandled rejection on read permission prompt

packages/core/onStartTyping/index.test.ts, packages/core/onStartTyping/index.ts
---
This PR fixes the characters which are accepted when using onStartTyping. Specifically, it adds back the ability for users to start typing with Numpad0 to focus on the connected element (#4614, related: #2932).
Should more characters be accepted or are just the basic letters and numbers enough?
=> fix(onStartTyping): Incorrect accepted valid characters

packages/core/useEventSource/index.ts
Uses `shallowRef` for the event names as they are always strings.
Uses `deepRef` for the event data as it could be anything.
This also raised that the `data` is currently typed as `string | null`, but event source events can actually pass data of any type. This compiled successfully in the past because a `MessageEvent` defaults to `MessageEvent<any>` (i.e. `{data: any}`).
For now, i have introduced a `Data` type parameter which defaults to `any` to keep backwards compat.
In future, we should default this to `unknown`.
=> refactor(useEventSource): use `shallowRef` for event & allow any data

packages/core/useWebNotification/index.md
=> docs(useWebNotification): add permission tip and update example

packages/shared/refDebounced/index.md, packages/shared/refThrottled/index.md, packages/shared/useDebounceFn/index.md, packages/shared/useThrottleFn/index.md
This PR fixes some broken links to a really good blog post. It seems like the domain was moved from `redd.one` to `kettanaito.com`.
=> fix(docs): blog moved to different domain

package.json, packages/.vitepress/plugins/utils.ts, packages/.vitepress/vite.config.ts, packages/core/useAsyncState/demo.vue, packages/core/useMediaQuery/demo.vue, packages/core/useParallax/demo.vue, packages/core/usePermission/demo.vue, pnpm-lock.yaml, pnpm-workspace.yaml, scripts/utils.ts, test/exports.test.ts
Switches to the `yaml` package for tests, since `js-yaml` is no longer maintained and does not support the latest yaml spec.
Note this is low priority since we only use it in tests, but we may as well do the clean up still.
=> chore: switch to yaml for tests

packages/core/useDropZone/index.ts
If one wants to drop files on the entire page, they need to pass ` document` as the target:
```typescript
useDropZone(window.document, {
onDrop: (files) => console.log('Dropped files:', files),
})
```
This PR fixes the TypeScript type to allow `Document` usage.
=> fix(useDropZone): Allow passing `document` as target

packages/core/useAnimate/index.browser.test.ts, packages/core/useAnimate/index.test.ts, packages/core/useCurrentElement/index.test.ts
If you call `mount` with a plain object, the `vm` types are not inferred correctly.
For example:
```ts
const wrapper = mount({
template: '<div></div>',
setup() {
return { foo: 303 };
}
});
wrapper.vm.foo; // `never`
```
This seems to be solved by using `defineComponent`, so `vm.foo` is now `number`.
=> test: fix types of some mount calls

packages/.vitepress/theme/styles/demo.css, packages/core/useTextareaAutosize/demo.vue
=> docs: add responsive styles for textarea in small screens

packages/shared/tryOnMounted/index.ts
- [ x ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ x ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ x ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ x ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly …
=> fix(tryOnMounted): pass target to getLifeCycleTarget

packages/shared/useArrayFind/index.ts
=> fix(UseArrayFindReturn): Missing template type

packages/core/useStorage/index.ts
This is _yet another_ possible fix for the various `useStorage` scope issues.
Basically, `onMounted` will _always_ run in the scope of the _component_. This means the event listener will not be torn down unless the element itself is. When the various effect scopes we use are torn down, the listener will remain and cause various memory leaks.
We can solve this by moving the event listeners _outside_ the `onMounted` callback, as they will then teardown when the scope they're in disposes.
However, this then means the event listener could run before the component has mounted, when `initOnMount` is true. To solve this, we check in the event handler and do nothing if it isn't mounted yet.
We only care about the _first_ mount, since all others will have already gone through at least one `update` …
=> fix: always mount listeners in useStorage

packages/core/onClickOutside/index.ts
---
Fixes https://github.com/vueuse/vueuse/issues/4724
However, it's useful to note that `pointerdown` event doesn't need this workaround. However, [it's supported since Safari 13](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event#browser_compatibility) where our baseline (Vue's 3 requirements) are [Safari 10](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#browser_compatibility)
Perhaps I should add a TODO comment about this so it can be reviewed at a later time if we change our browser support baseline?
=> fix(onClickOutside): workaround for iOS

packages/shared/watchPausable/index.md
=> docs(pausableWatch): suggest to use Vue's native since 3.5

packages/shared/watchOnce/index.md
=> docs(watchOnce): suggest to use Vue's native feature since 3.4

packages/core/computedAsync/index.ts
=> feat(computedAsync): add option to control watcher's flush timing

packages/core/computedAsync/index.test.ts, packages/core/computedAsync/index.ts
=> fix(computedAsync): return `ComputedRef<T>` type when `lazy: true`

packages/shared/watchOnce/index.md, packages/shared/watchOnce/index.ts
=> feat(watchOnce): use vue's native once behaviour

packages/core/useScroll/demo.vue, packages/core/useScroll/index.md
=> feat(useScroll): add missing measure documentation

packages/core/useStyleTag/index.ts
=> feat(useStyleTag): support passing `nonce`

packages/core/useMagicKeys/index.ts
=> fix(useMagicKeys): correctly clear current pressed keys when releasing Shift

packages/core/onClickOutside/directive.ts
optimize the vOnClickOutside method , remove handler form element and save handle to weak map. 
This can prevent external operations on the methods mounted on the element, thereby avoiding some unexpected behaviors
=> refactor(vOnClickOutside): use weakMap for stop function instead of mutating element

packages/core/useNow/index.test.ts, packages/core/useNow/index.ts
=> feat(useNow): expose immediate option

packages/integrations/useSortable/index.ts
=> fix(useSortable): fix type misalignment

.gitignore, packages/.vitepress/config.ts, packages/.vitepress/plugins/pwa-virtual.ts, packages/.vitepress/shims.d.ts, packages/.vitepress/sw.ts, packages/.vitepress/vite.config.ts
---
When using Algolia search, the links are lower case, this PR adds an `urlManipulation` callback to the service worker precache handler to serve the real page/assets.
This PR also adds a new Vite plugin to generate the function names with the package and the search:
- the plugin `packages/.vitepress/plugins/pwa-virtual.ts` for the virtual
- updated Vite configuration file to include the plugin in dev
- updated VitePress configuration to include the plugin at build in the `injectManifest` PWA option
- added `packages/.vitepress/shims.d.ts` for the virtual
- updated `.gitignore` to exclude `packages/.vitepress/shims.d.ts`, we need the module augmentation (not yet here, I'll push it in 1 min. **DONE** ✅ )
resolves #4309
_workbox precaching serving existing asset_
_page resolved correctly_
=> docs(pwa): fix 404 navigation errors when using search

packages/core/useAsyncState/index.md, packages/core/useAsyncState/index.test.ts, packages/core/useAsyncState/index.ts
=> feat(useAsyncState): add executeImmediate with the same type as the promise fn

packages/core/onLongPress/index.ts, packages/core/useElementHover/index.ts, packages/core/useIdle/index.ts, packages/core/useWebSocket/index.ts, packages/shared/refAutoReset/index.ts, packages/shared/useTimeoutFn/index.ts, packages/shared/utils/filters.ts, packages/shared/utils/types.ts
=> feat(shared): Introduce `TimerHandle` for setTimeout type

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
=> feat(useFetch): support for custom abort reason

packages/core/computedInject/index.test.ts, packages/core/computedInject/index.ts
=> refactor(computedInject): rename ctx param to oldValue

packages/integrations/useIDBKeyval/index.test.ts, packages/integrations/useIDBKeyval/index.ts
Attempt to add `serializer` option to `useIDBKeyval` to bring it more in line with `useStorage` as per https://vueuse.org/core/useStorage/#custom-serialization
Closes #4780
=> feat(useIDBKeyval): add `options.serializer`

packages/.vitepress/theme/styles/demo.css
In #4692, the textarea min-width was changed to `min(20rem, 100%)` to prevent layout issues on small screens.
This PR applies a similar fix for input fields, ensuring they display correctly on small screens as well.
Before:
After:
=> docs: add responsive styles for input in small screens

packages/shared/refDebounced/index.md, packages/shared/refThrottled/index.md
This PR adds examples of how to use objects with `refDebounced` and `refThrottled`.
Other APIs may encounter the same issue, so we should find a better place to provide a clear explanation.
Since we already have a working solution, the related PRs will be closed. Thanks for their contributions.
reference: #3158
closed: #3705
closed: #3969
=> docs(refDebounce,refThrottled): add usage example with object ref

packages/integrations/useSortable/index.md
closed: #4902 
When moveArrayElement passes the value of shallowRef `list.value` , the responsive setter will not be triggered
```ts {5}
import { moveArrayElement } from '@vueuse/integrations/useSortable'
useSortable(el, list, {
onUpdate: (e) => {
// If the passed list is a shallowRef, then the responsive setter will not be triggered.
// If it is a deepRef, there will be no such problem.
moveArrayElement(list.value, e.oldIndex, e.newIndex, e)
}
})
```
```ts
// So in the document, if you pass in a ref, there will be no such problem.
moveArrayElement(list, e.oldIndex, e.newIndex, e)
```
=> docs(useSortable): moveArrayElement arguments

packages/core/useLocalStorage/index.ts, packages/math/logicNot/index.ts, packages/shared/get/index.ts
=> fix(types): use Vue's native `MaybeRef` and `MaybeRefOrGetter` instead

packages/core/useElementBounding/index.md, packages/core/useElementSize/index.md
The style should be consistent.
=> docs(useElementBounding,useElementSize): convert `<script>` to `<script setup lang="ts">`

packages/core/useMagicKeys/index.test.ts, packages/core/useMagicKeys/index.ts
=> fix(useMagicKeys): prevent incorrect clearing of other keys after releasing shift

packages/integrations/useAsyncValidator/demo.client.vue, packages/integrations/useAxios/demo.vue, packages/integrations/useChangeCase/demo.vue, packages/integrations/useDrauu/demo.client.vue, packages/integrations/useFocusTrap/demo.vue, packages/integrations/useFuse/demo.vue, packages/integrations/useIDBKeyval/demo.client.vue, packages/integrations/useJwt/demo.vue, packages/integrations/useNProgress/demo.vue, packages/integrations/useQRCode/demo.vue, packages/integrations/useSortable/demo.vue
This PR updates `integration` demo imports to use direct paths to prevent errors for users who want to view or use the demos.
This change should not affect the Playground.
=> refactor(integrations): use direct imports in demos

scripts/changelog.ts
---
This PR adds commit d32f80ca4e0f7600b68cbca05341b351e31563c1 to the whitelist in `changelog.ts` so that it appears in the Changelog.
The reason is that the changes in that PR represent a feature-level update instead of just `refactor` from the user’s perspective.
=> docs: add `whitelistCommits` for Changelog

packages/core/useAsyncState/index.test.ts, packages/core/useAsyncState/index.ts
=> feat(useAsyncState)!: set globalThis.reportError as default onError

packages/guidelines.md
This PR updates the guidelines to recommend using `tryOnScopeDispose` instead of `tryOnUnmounted` for cleaning up side-effects.
=> docs: recommend using tryOnScopeDispose instead of tryOnUnmounted

packages/core/usePreferredLanguages/index.ts
This PR refactors `usePreferredLanguages` to use `shallowRef` for better performance.
=> perf(usePreferredLanguages): use shallowRef for better performance

packages/core/usePointer/index.ts
=> perf(usePointer): use shallowRef for better performance

packages/core/useAsyncState/index.test.ts, packages/core/useAsyncState/index.ts
Outside of typescript, we can already do this if `resetOnExecute: false`.
If it is `true`, we cause a maximum stack call exception since we're setting `ref.value = ref` (infinitely).
This updates the source so you can pass a ref in and we turn it into a value before using it as such.
This means you can now use your own ref:
```ts
const myRef = shallowRef(200);
useAsyncState(asyncPromise, myRef);
// some time later, `myRef.value` is whatever `asyncPromise` resolved to
```
=> feat(useAsyncState): allow initial value to be a ref

packages/core/onLongPress/index.test.ts, packages/core/onLongPress/index.ts
=> feat(onLongPress): allow function as value in delay

packages/core/onLongPress/index.test.ts
The test can pass even if we don't call the callback, currently. This is
because the callback returns the same time as the default.
This updates the test to use a non-default time to prove that the
callback is actually called.
=> test(onLongPress): use custom timer in test assertion

tsdown.config.ts
=> build: simplify baseConfig setup and improve `dist` output

packages/.vitepress/theme/styles/vars.css
This PR changes the background color of info blocks to make them more visible.
Brfore:
After:
=> docs: update info block background color

packages/shared/injectLocal/index.ts, packages/shared/provideLocal/index.ts, packages/shared/provideLocal/map.ts
- fall back to current effect scope when component instance is missing
- share the same owner lookup between provideLocal and injectLocal
- allow localProvidedStateMap to key off either component proxies or scopes scopesCloses #4875
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for …
=> fix(shared): support provideLocal/injectLocal in vapor mode

packages/core/useClipboard/index.ts
…Copy
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly …
=> refactor(useClipboard): remove redundant nullish coalescing in legacyCopy
