README.md, packages/core/useElementVisibility/index.md, packages/core/useElementVisibility/index.stories.tsx, packages/core/useElementVisibility/index.ts
=> add basic implementaton of useElementVisibility

README.md, packages/core/useDocumentVisibility/index.md, packages/core/useDocumentVisibility/index.stories.tsx, packages/core/useDocumentVisibility/index.ts
=> useDocumentVisibility

packages/core/useTransition/index.stories.tsx
Sorry for the spam, I promise now i'm done 😅
=> Fix a couple of type errors

README.md, packages/core/useDevicePixelRatio/index.md, packages/core/useDevicePixelRatio/index.stories.tsx, packages/core/useDevicePixelRatio/index.ts
Reactively track [`Window.devicePixelRatio`](https://developer.mozilla.org/ru/docs/Web/API/Window/devicePixelRatio)
=> feat: useDevicePixelRatio

README.md
useIntersectionObserver was missing in the readme
=> docs: add useIntersectionObserver in readme

packages/_docs/showcases/textParticles.stories.tsx
Just a small fix to point to the proper source file.
=> docs: fix showcase source link

packages/core/useEventSource/index.md, packages/core/useEventSource/index.stories.tsx, packages/core/useEventSource/index.ts
=> add useEventSource

packages/core/useMutationObserver/index.md, packages/core/useMutationObserver/index.stories.tsx, packages/core/useMutationObserver/index.ts
Use MutationObserver with watchEffect
=> feat: Add useMutationObserver

package.json, packages/core/useResizeObserver/index.md, packages/core/useResizeObserver/index.stories.tsx, packages/core/useResizeObserver/index.ts, yarn.lock
Use [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) with watchEffect and export `stop` function to manual stop situation
=> feat add useResizeObserver

README.md, packages/core/onStartTyping/index.stories.tsx
I realized composable was missing in the readme so I added it
=> chore: add onStartTyping to readme

packages/_docs/tests.ts, packages/core/createGlobalState/index.test.ts, packages/core/createGlobalState/index.ts, packages/core/utils/index.ts
Added failing tests for `createGlobalState`
=> fix: createGlobalState

README.md, packages/rxjs/README.md, packages/rxjs/from/index.md, packages/rxjs/from/index.stories.tsx, packages/rxjs/from/index.ts, packages/rxjs/readme.stories.tsx, packages/rxjs/toObserver/index.md, packages/rxjs/toObserver/index.stories.tsx, packages/rxjs/toObserver/index.ts, packages/rxjs/useObservable/index.md, packages/rxjs/useObservable/index.stories.tsx, packages/rxjs/useObservable/index.ts, packages/rxjs/useSubscription/index.md, packages/rxjs/useSubscription/index.stories.tsx, packages/rxjs/useSubscription/index.ts, scripts/import.js, scripts/packages.js, scripts/updateReadme.js
use functions to work with rxjs
resolves #132
=> feat: add rxjs addon

packages/core/useRefHistory/index.md, packages/core/useRefHistory/index.test.ts, packages/core/useRefHistory/index.ts
=> refactor!: useRefHistory api changes

packages/core/useRefHistory/index.test.ts, packages/core/useRefHistory/index.ts
Added tests for useRefHistory reset, and fixed an issue in its implementation
=> fix: useRefHistory reset bug plus added tests

packages/core/utils/index.ts, packages/core/when/index.md, packages/core/when/index.stories.tsx, packages/core/when/index.ts
Docs: https://github.com/antfu/vueuse/blob/feat/when/packages/core/when/index.md
=> feat: add when

packages/core/useEventSource/index.ts
=> fix: useEventSource remove 'es.close' for actually closing connection

packages/core/useStoragePlain/index.md, scripts/update-readme.ts
Just fixing a minor typo 🤓 I did a global search for "deprated" (case-insensitive), so the update-readme script should still work.
=> DEPRATED -> DEPRECATED

packages/core/useIntersectionObserver/index.md, packages/core/useIntersectionObserver/index.stories.tsx, packages/core/useIntersectionObserver/index.ts
- Fix `stoping` function 
- Add cases for story of `useIntersectionObserver`
- Add description of `stopping` function
=> fix: useIntersectionObserver stopping

packages/integrations/useAxios/index.ts
Hey, it would be nice to have axios request cancelation out of the box.
=> feat(useAxios): added request cancelation

packages/core/useSpeechRecognition/index.md, packages/core/useSpeechRecognition/index.stories.tsx, packages/core/useSpeechRecognition/index.ts
ported from https://www.reddit.com/r/vuejs/comments/jksizl/speech_recognition_as_a_vue_3_hook
by @wobsoriano
=> feat: new function - useSpeechRecognition

packages/core/onStartTyping/index.stories.tsx, packages/core/useBattery/index.stories.tsx, packages/core/useCssVar/index.stories.tsx, packages/core/useDebounce/index.stories.tsx, packages/core/useDebounceFn/index.stories.tsx, packages/core/useDeviceLight/index.stories.tsx, packages/core/useDeviceOrientation/index.stories.tsx, packages/core/useDevicePixelRatio/index.stories.tsx, packages/core/useEventListener/index.stories.tsx, packages/core/useEventSource/index.stories.tsx, packages/core/useLocalStorage/index.stories.tsx, packages/core/useSessionStorage/index.stories.tsx, packages/core/useWebSocket/index.stories.tsx, packages/core/useWebWorker/index.stories.tsx
WIP
Hi @antfu , what do you think about updating the story templates?
=> docs: update stories template

packages/core/useMediaQuery/index.ts
Hi @antfu , I came across problems with the media query during some tests and decided to send my proposal.
=> fix: adds fallback for Safari < 14 and older browsers

packages/core/_configurable.ts, packages/core/useDeviceLight/index.ts, packages/core/useDeviceMotion/index.ts, packages/core/useDeviceOrientation/index.ts, packages/core/useDevicePixelRatio/index.ts, packages/core/useEventListener/index.ts
close #168
@anteriovieira what do you think?
=> refactor: configurable global to make functions more flexible

packages/core/useBattery/index.stories.tsx, packages/core/useBattery/index.ts, packages/core/useClipboard/index.md, packages/core/useClipboard/index.stories.tsx, packages/core/useClipboard/index.ts, packages/core/useNetwork/index.ts
renamed `supported` to `isSupported` and use plain boolean instead of ref.
=> BREAKING CHANGE: refactor!: supported -> isSupported

packages/core/useDeviceLight/index.stories.tsx, packages/core/useDeviceMotion/index.stories.tsx, packages/core/useDeviceOrientation/index.stories.tsx, packages/core/useDevicePixelRatio/index.stories.tsx, packages/core/useParallax/index.ts
=> docs: uses storybook window context to device's sensors

packages/core/useTransition/index.md, packages/core/useTransition/index.stories.tsx, packages/core/useTransition/index.test.ts, packages/core/useTransition/index.ts
=> BREAKING CHANGE: refactor(useTransition): API changes

docs/Guide.md, packages/core/useDebounce/index.ts, packages/core/useDebounceFn/index.ts, packages/core/useDeviceMotion/index.ts, packages/core/useThrottleFn/index.ts, packages/shared/utils/filters.ts, packages/shared/utils/index.ts
=> feat: event filters

packages/shared/syncRef/index.md, packages/shared/syncRef/index.ts
As discussed in https://github.com/antfu/vueuse/issues/189
=> chore: syncRef watch options docs

packages/core/useGeolocation/index.ts
=> chore: make global dependencies configurable

packages/core/useWindowScroll/index.stories.tsx
=> chore: fix demo styles

README.md
fix the contribute links in readme
=> docs: fix contribute link typo in readme

packages/core/useClipboard/index.ts, yarn.lock
- fix(useClipboard): support cut
- chore: remove unused dependency
=> fix(useClipboard): support cut

packages/core/useResizeObserver/index.ts
- fix(useResizeObserver): fix watch
watch target 需要立即执行
=> fix(useResizeObserver): fix watch

packages/core/useElementVisibility/index.ts
=> feat: add option to use custom scrollTarget with `useElementVisibiity`

packages/core/useVModel/index.ts
=> fix(useVModel): TypeError: Cannot read property '_events' of undefined

packages/.vitepress/theme/components/DarkModeSwitch.vue, packages/.vitepress/theme/components/NavBar.vue, packages/.vitepress/theme/styles/layout.css
this PR adds dark mode setup inspired by nuxt's styles.
=> docs: darkmode 🌗

packages/core/useTransition/index.md, packages/core/useTransition/index.test.ts, packages/core/useTransition/index.ts, packages/shared/utils/is.ts
=> feat(useTransition): transitions and onStarted/onFinished callbacks

packages/integrations/useNProgress/demo.vue, packages/integrations/useNProgress/index.test.ts, packages/integrations/useNProgress/index.ts
=> fix(integrations/useNProgress): makes progress reactive

package.json, packages/core/useVModel/index.md, packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts
add useVModel default value 
also fix the lint-staged, since the path not be resolved correctly
=> feat: add useVModel default value

packages/shared/useToggle/index.md, packages/shared/useToggle/index.ts
=> fix(shared): useToggle type mismatch, close #313

packages/vite.config.ts
I'm not an expert on WindiCSS or Vite, so if there is a better way to solve this feel free to close this PR 🙂 
Closes #344
=> docs: include demos for Windi CSS, closes #344

packages/core/useRafFn/index.md
Docs for useRafFn now more accurately reflect the API as mentioned in issue #359
=> docs(useRafFn): updated docs to more accurately reflect the API, close #359

packages/core/useWebWorker/index.md, packages/core/useWebWorker/index.ts
=> feat(useWebWorker): allow provide WorkerOptions for the Worker, closes #372

packages/core/useStorage/demo.vue
=> fix(useStorage): fix demo issue

packages/shared/debouncedWatch/demo.vue, packages/shared/pausableWatch/demo.vue, packages/shared/throttledWatch/demo.vue, yarn.lock
Added Demos for
- debouncedWatch
- throttledWatch
Updated pausableWatch textbox to use docs textbox style
=> docs: added demos for debouncedWatch and throttledWatch

packages/integrations/useAxios/index.ts
=> fix(useAxios): disable cancel if request finished or not started

packages/core/useSpeechRecognition/demo.vue
=> chore: typo

packages/core/useTitle/index.ts
Should resolve https://github.com/vueuse/vueuse/issues/479
=> feat(useTitle): new option `observe` to watch title changes

packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.ts
=> feat(useWebSocket): add immediate option

packages/core/useMediaControls/index.ts
=> feat(useMediaControls): add error event

packages/core/useStorage/demo.vue, packages/core/useStorage/index.ts
Implements changes discussed in #463
=> feat(useStorage): optimize event handling logic

packages/core/useFetch/index.ts, packages/shared/createEventHook/index.ts
=> feat(createEventHook): added interface

packages/shared/until/index.md, packages/shared/until/index.ts
=> fix(toMatch): UntilBaseInstance#toMatch typedef

packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.ts
https://github.com/vueuse/vueuse/issues/501#issuecomment-839726620
=> refactor(useWebSocket)!: change immediate default for 5.0.0

packages/shared/biSyncRef/index.md
fixed sample code comment on doc.
=> docs(biSyncRef): fix console output comment

packages/index.md
=> docs: get started link address problem

packages/electron/index.ts, packages/electron/useZoomFactor/index.md, packages/electron/useZoomFactor/index.ts
add feat: Reactive [WebFrame](https://www.electronjs.org/docs/api/web-frame#webframe) zoom factor.
=> feat: add electron/useZoomFactor

packages/shared/or/index.md
URL: https://vueuse.org/shared/or/
It should be "OR" instead of "AND" as title for this page 😅
=> docs: typo

packages/core/useWebSocket/index.md
=> docs: fix typo

packages/guide/components.md
I just made the code example a little more relevant to the previous example
=> docs: Fix components code example

packages/shared/useIntervalFn/index.md
refs: https://github.com/vueuse/vueuse/blob/main/packages/shared/useIntervalFn/index.ts#L54-L57
=> docs: update useIntervalFn return function

packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
=> fix(useStorage): read type with default null as null instead of string

packages/.vitepress/theme/utils.ts
=> docs: fixed active routes comparing in documentation

packages/router/useRouteQuery/index.md
Also adds one line of whitespace to give the ts definitions some breathing room.  ;)
=> docs: show default value example for useRouteQuery

packages/core/useNetwork/index.md, packages/core/useNetwork/index.ts
=> feat(useNetwork): add rtt properties

packages/shared/useIntervalFn/index.ts
=> feat(useIntervalFn): new option `immediateCallback`

packages/core/useMediaControls/index.md, packages/core/useMediaControls/index.ts
maybe the `buffering` option does not make sense .
fix #678
=> chore(useMediaControls): remove useless option

packages/core/useAsyncState/index.md, packages/core/useAsyncState/index.ts
=> fix(useAsyncState): onError param type

packages/core/onClickOutside/index.ts
=> feat(onClickOutside): whitelist `click` event

packages/core/useVModel/index.md, packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts
=> feat(useVModel): new options `deep` to emit for deep changes

packages/core/useFetch/index.md
=> docs(useFetch): update Intercepting Request example

packages/core/useEventBus/index.test.ts, packages/core/useEventBus/index.ts, packages/core/useEventBus/internal.ts
I am not very good at writing English documents. If I think this implementation is okay, I may have to trouble you to improve the documents.
=> feat(useEventBus): new Function `once`

packages/core/onClickOutside/demo.vue, packages/core/useDraggable/demo.vue, packages/core/useKeyModifier/demo.vue, packages/core/useMousePressed/demo.vue, packages/core/useTimeAgo/demo.vue, packages/core/useTransition/demo.vue
Fixed some demos for the new theme. Mostly missing backgrounds colors and some sizing issues.
=> fix: updated various demos to support new theme

packages/core/useBreakpoints/breakpoints.ts
Reference: https://quasar.dev/style/breakpoints
=> feat(useBreakpoints): add breakpoints for Quasar

packages/core/asyncComputed/index.test.ts, packages/core/asyncComputed/index.ts
=> feat(asyncComputed): onError option

README.md, indexes.json, packages/add-ons.md, packages/integrations/README.md, packages/integrations/index.ts, packages/integrations/package.json, packages/integrations/pnpm-lock.yaml, packages/integrations/useDrauu/demo.vue, packages/integrations/useDrauu/index.md, packages/integrations/useDrauu/index.ts, yarn.lock
A slightly easier to use and more reactive function for drauu
=> feat(useDrauu): New function

packages/core/useWebSocket/index.md, packages/core/useWebSocket/index.ts
=> feat(useWebsocket): add auto close option

packages/shared/useDebounceFn/index.md, packages/shared/useThrottle/demo.vue, packages/shared/useThrottle/index.md, packages/shared/useThrottle/index.ts, packages/shared/useThrottleFn/index.md, packages/shared/useThrottleFn/index.ts, packages/shared/utils/filters.ts
tweak useThrottle demo
add leading option info to useThrottle docs
fix "addEventLisenter" typo
resoves issue #672
=> feat(throttleFilter): add leading option

packages/shared/toRefs/index.test.ts, packages/shared/toRefs/index.ts
=> fix(toRefs): call set method on computed

packages/shared/useDebounce/demo.vue, packages/shared/useDebounce/index.md, packages/shared/useDebounce/index.ts, packages/shared/useDebounceFn/demo.vue, packages/shared/useDebounceFn/index.md, packages/shared/useDebounceFn/index.ts, packages/shared/utils/filters.ts
#615 
I added maxMs to the debounceFilter and consequentially useDebounce and useDebounceFn.
I updated the demos on useDebounce and useDebounceFn (maxMs = 5000ms) so you can see it working but can drop these.
=> feat(useDebounce & useDebounceFn): accept maxMs parameter

packages/core/useBreakpoints/demo.vue, packages/core/useBreakpoints/index.ts
=> feat(useBreakpoints): shortcuts

packages/core/useFetch/index.ts, packages/core/useLocalStorage/index.ts, packages/core/useSessionStorage/index.ts, packages/core/useStorage/index.ts, packages/shared/useTimeout/index.ts, packages/shared/useTimeoutFn/index.ts, packages/shared/utils/types.ts
=> fix: interface typos

packages/core/useEventSource/index.ts
=> feat(useEventSource): add options

packages/core/nuxt.mjs
https://v3.nuxtjs.org/docs/usage/6-cookies
=> fix(nuxt): add useCookie in disabled composables for Nuxt

packages/core/useVirtualList/component.ts
=> fix(UseVirtualList): fix list not being reactive in component

packages/shared/eagerComputed/index.md
Commit message should be docs(eagerComputed): Add correct console.log output
=> docs(eagerComputed): Add correct console.log output

packages/rxjs/from/_demo.vue, packages/rxjs/from/index.md, packages/rxjs/from/index.ts
Improve from method from the rxjs plugin.
- Cleanup watcher on Observable unsubscription
- Add support for watchOptions
=> feat(rxjs): improve rxjs from

packages/shared/utils/filters.ts
fix https://github.com/vueuse/vueuse/issues/1013
=> feat(throttleFilter): leading fix

packages/core/useWebSocket/index.ts
Set status code as default in method.
Related #995
=>  fix(useWebSocket): close WebSocket gently

packages/core/usePageLeave/index.md
Function usePageLeave index.md component amend
=> docs(usePageLeave): typo

packages/core/useWebSocket/index.ts
The code must be either 1000, or between 3000 and 4999. 1012 is neither, too.
Related #1018
Related #995
=> fix(useWebSocket): close WebSocket gently

packages/core/useFetch/index.md, packages/guidelines.md
Added documentation for creating asynchronous composables
=> docs: asynchronous functions

packages/core/useAsyncState/demo.vue, packages/core/useAsyncState/index.md, packages/core/useAsyncState/index.ts
Add property isLoading can bind to component
=> feat(useAsyncState): add property isLoading

packages/core/useColorMode/index.ts, packages/core/useStorage/index.ts, packages/core/useStorageAsync/index.ts
PR fix #1105
catch DOMException (Failed to read `localStorage`) on accessing defaultWindow.localStorage. see issue #1105 for more information
=> fix(storage): caught DOMException accessing storage

README.md, packages/index.md
=> chore: fix typos in readme.md and index.md

packages/shared/watchAtMost/index.ts, packages/shared/watchOnce/index.ts
=> fix(watchOnce): watchOnce when called with immediate flag

packages/core/useAsyncQueue/index.md
'result' attribute 'value' does not exist
=> docs(useAsyncQueue): update index.md

packages/core/useFetch/index.ts
=> feat(useFetch): support more http method (#1149)

packages/core/useDraggable/component.ts
[useDraggable.component] props is missing a key（storageType）,This causes storage to remain localStorage
=> fix(UseDraggable): add prop key[storageType]

packages/shared/useInterval/index.ts, packages/shared/useIntervalFn/demo.vue, packages/shared/useIntervalFn/index.ts
=> feat(useInterval): support ref as interval

packages/core/useScriptTag/index.ts
=> feat(useScriptTag): custom attrs support

packages/.vitepress/plugins/changelog.ts, packages/.vitepress/plugins/contributors.ts, packages/vite.config.ts, scripts/changelog.ts
=> build(docs): improve docs build performance

packages/core/useStyleTag/index.md
=> docs: fix docs

packages/core/useElementBounding/index.ts
=> fix(useElementBouding): should reset value while element unmounted

packages/core/useElementSize/index.ts
=> fix(useElementSize): should reset value while element unmounted

packages/core/useVModel/index.md
Added a `<script setup>` example to the doc.
=> docs(useVModel): add `<script setup>` example

packages/core/useFetch/index.ts
=> fix(useFetch): fix run `afterFetch` condition

packages/core/useFullscreen/index.ts
=> feat(useFullscreen): autoExit support

packages/core/useEventBus/index.test.ts, packages/core/useEventBus/index.ts
=> feat(useEventBus): payload support

packages/core/useFetch/index.ts, packages/integrations/useAxios/index.ts
=> fix(useFetch): make `error` shallow

packages/core/useTextSelection/demo.vue, packages/core/useTextSelection/index.ts
Close #1053 
less code & optimize
=> fix(useTextSelection)!: listen to `selectionchange` event

packages/core/useStyleTag/index.md
=> chore: fix inconsistencies in code blocks

packages/core/useDocumentVisibility/index.ts
https://github.com/vueuse/vueuse/issues/1334
---
=> fix: use indirect type

packages/core/onLongPress/index.md
fix typo
---
- [x ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
=> docs(onLongPress): fix typo

packages/.vitepress/plugins/markdownTransform.ts, packages/core/computedInject/demo.vue, packages/core/computedInject/demoReceiver.vue, packages/core/onLongPress/demo.vue, packages/core/useBase64/demo.vue, packages/core/useDisplayMedia/index.md, packages/core/useEyeDropper/demo.vue, packages/core/useInfiniteScroll/demo.vue, packages/core/useMediaControls/demo.vue, packages/core/useMousePressed/demo.vue, packages/core/useSpeechRecognition/demo.vue, packages/core/useSpeechSynthesis/demo.vue, packages/core/useTextSelection/demo.vue, packages/core/useWakeLock/demo.vue, packages/integrations/useDrauu/demo.vue, packages/integrations/useFuse/demo.vue, packages/shared/eagerComputed/EagerDemo.vue, packages/shared/eagerComputed/LazyDemo.vue, packages/shared/eagerComputed/demo.vue, packages/shared/eagerComputed/state.ts
Updated various doc pages and updates some demos. Also fixed some bugs
**eagerComputed**
The original demo for this did not work. It has been updated and works and provides a better demo of what the function does.
**useFuse**
Redesigned the demo
**useSpeech**
Just updated the radio button styles.
---
=> docs: update demos & fixes

packages/integrations/useAxios/index.ts
=> feat(useAxios): allow useAxios to be awaited

packages/core/onKeyStroke/directive.test.ts, packages/core/onKeyStroke/directive.ts, packages/core/onKeyStroke/index.md
=> feat(onKeyStroke): directive support

packages/integrations/useAxios/index.test.ts
Add waitUntilFinished logic case
Adjust the test for [function](https://github.com/vueuse/vueuse/pull/1228)
---
=> test(useAxios): Add waitUntilFinished logic case

.vscode/launch.json
support debug single vitest test file in vscode
debug single vitest test file in vscode
---
=> workflow: support debug single vitest test file in vscode

packages/core/onLongPress/directive.test.ts, packages/core/onLongPress/directive.ts, packages/core/onLongPress/index.md
Make `directive` automatic registered normal
---
=> chore(onLongPress): make directive automatic registered normal

packages/core/useElementSize/directive.test.ts, packages/core/useElementSize/directive.ts, packages/core/useElementSize/index.md
=> feat(useElementSize): directive support

packages/nuxt/ssr-plugin.mjs
=> chore: lint

packages/core/useAsyncState/index.ts
=> docs(useAsyncState): update function documentation

packages/contributors.ts
contributors avatar links broken
---
=> chore: fix links broken

packages/core/useWebNotification/demo.vue
useWebNotification need a simple demo
---
=> docs: add useWebNotification demo

packages/index.md
=> docs: functions count [ci:skip]

packages/contributors.ts
=> chore: update contributors

packages/core/useClipboard/index.ts, packages/core/useIntersectionObserver/index.ts, packages/core/useMutationObserver/index.ts, packages/core/useResizeObserver/index.ts, packages/core/useWebWorker/index.ts
=> chore(type): improve types

packages/core/useElementByPoint/demo.vue
=> docs(fixElementByPoint): fix demo. closes #1419

packages/core/useStorage/demo.vue, packages/core/useStorage/index.ts
=> fix: useStorage sync race condition, closes #808

packages/.test/setup.ts, packages/core/useStorage/index.test.ts, packages/core/useStorage/index.ts
Close #1458
Close #848
Close #1446
Close #1444 
I believe this solves the problem from the origin
=> fix(useStorage): fix sync racing and shreding

packages/core/useKeyModifier/index.ts
=> fix(useKeyModifier): `getModifierState` is not a function

packages/core/usePermission/demo.vue, packages/core/usePermission/index.ts
usePermissions was lacking some APIs, this PR should fix that.
---
=> feat(usePermission): support more permissions

packages/core/useFetch/index.ts
close #1144
Just for resolve my issue  and an attempt to contribute to an open source project
=> feat(useFetch): expose whole the http response

packages/core/useNavigatorLanguage/demo.vue
the useNavigatorLanguage need a simple demo
---
=> docs: add useNavigatorLanguage demo

packages/shared/useDateFormat/index.md, packages/shared/useDateFormat/index.test.ts, packages/shared/useDateFormat/index.ts
Support d format. [#1478 ](https://github.com/vueuse/vueuse/issues/1478)
---
=> feat(useDateFormat): support `d` formatter

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
merge default options
closes: #1495
---
=> fix(useFetch): merge default options

README.md
Use dark-mode logo in Github dark mode. Documented [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)
---
=> chore: dark logo for github dark mode

README.md, packages/shared/refAutoReset/index.ts
Looks like it only supports top-level elements so we have to use it on the link instead of the image 🙁 
---
=> chore: fix dark mode logo

packages/guidelines.md
Fix [Best Practice](https://github.com/vueuse/vueuse/blob/main/guide/best-practice.html) dead link in guidelines.md
=> fix(doc): new options Update guidelines.md

packages/integrations/useAxios/index.md
use an instance of `axios` with `immediate` options
closes: #1516 
---
=> doc(useAxios): update

packages/guidelines.md
=> fix(doc): word spelling mistake

packages/.vitepress/theme/components/FunctionBadge.vue, packages/.vitepress/theme/components/FunctionsList.vue, packages/core/useColorMode/demo.vue, packages/core/useDark/demo.vue, packages/core/useDevicesList/demo.vue, packages/core/useFetch/demo.vue, packages/core/useGamepad/demo.vue, packages/core/useMediaControls/demo.vue, packages/core/useSpeechSynthesis/demo.vue, packages/integrations/useDrauu/demo.vue, packages/integrations/useFuse/demo.vue
Update the demos to use unocss icons instead of unplugin-icons components so they are compatible with the playground.
---
=> docs: update demos to use unocss icons

packages/contributors.json, packages/core/useClipboard/demo.vue, packages/core/useColorMode/demo.vue, packages/core/useDevicePixelRatio/demo.vue, packages/core/useFileSystemAccess/demo.vue, packages/core/useGamepad/components/Controller.vue, packages/core/useIdle/demo.vue, packages/core/useParallax/demo.vue, packages/core/usePointerSwipe/demo.vue, packages/core/useScrollLock/demo.vue, packages/core/useUserMedia/demo.vue, packages/core/useWebWorkerFn/demo.vue, packages/shared/computedEager/demo/EagerDemo.vue, packages/shared/createGlobalState/demo.vue, packages/shared/until/demo.vue
Normalize demos to be more consistent and easier to run in playground
---
=> docs: normalize demos to be more consistent

package.json, pnpm-lock.yaml
=> chore: upgrade pnpm 7

packages/core/onLongPress/index.ts, packages/core/useGamepad/index.ts, packages/core/useOffsetPagination/index.ts
```
Circular dependency: ../../node_modules/.pnpm/@vueuse+core@8.2.6_vue@3.2.31/node_modules/@vueuse/core/index.mjs -> ../../node_modules/.pnpm/@vueuse+core@8.2.6_vue@3.2.31/node_modules/@vueuse/core/index.mjs
```
---
=> fix(core): circular reference

packages/core/useCached/index.md
=> docs(useCached): typo of index.md

packages/core/useMutationObserver/index.ts
=> fix(useMutationObserver): isSupported misjudge

packages/integrations/useAxios/index.ts
fix `argsPlaceholder = 0` when url is an empty string 
fix exception when `config` or `options` is `undefined`
fixes: #1533
---
=> fix(useAxios): exception when `args` incorrect

packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts, pnpm-lock.yaml
In the latest release we introduced a default value to v-model. But if the value is false it will return undefined instead which is not desired behavior 
---
=> fix(useVModel): returning undefined on false values

packages/core/useScreenOrientation/index.md
Minor documentation fix for import type is useOrientationScreen()
N/A
=> docs(useScreenOrientation): minor typo correction

packages/core/useVModel/index.test.ts, packages/core/useVModel/index.ts
`defaultValue` can work with null
---
=> fix(useVModel): `defaultValue` can work with null

packages/core/useScrollLock/index.ts
stop event on scope dispose.
---
=> fix(useScrollLock): stop listener properly

meta/ecosystem-functions.ts, packages/add-ons.md, packages/contributors.json, packages/contributors.ts
Documentation for the @vueuse/schema-org add-on
I needed to manually add myself to the contributor list so my GitHub avatar would appear, not sure if this will cause issues once the script runs.
---
=> chore: ecosystem add-on @vueuse/schema-org

packages/shared/watchDebounced/demo.vue, packages/shared/watchDebounced/index.md, packages/shared/watchDebounced/index.ts
=> feat(watchDebounced): new option

packages/core/useMutationObserver/index.md
Fixed incorrect condition in usage example (inverted)
---
=> doc(useMutationObserver): fix incorrect condition in usage example

packages/core/useScrollLock/index.ts, packages/shared/utils/is.ts
```typescript
// TODO: move to @vueuse/share
const isIOS = /* #__PURE__ */ isClient && window?.navigator && window?.navigator?.platform && /iP(ad|hone|od)/.test(window?.navigator?.platform)
```
---
=> chore: move `isIOS` to `@vueuse/shared`

packages/shared/utils/index.test.ts, packages/shared/utils/index.ts
=> fix(shared): correct to ignore undefined

packages/core/useFetch/index.test.ts, packages/core/useFetch/index.ts
=> fix(useFetch): respect custom fetch option

packages/core/useDraggable/component.ts
Be related to https://github.com/vueuse/vueuse/pull/1391#issuecomment-1132923404
---
=> fix(useDraggable): should pass `stopPropagation` option for component

packages/core/useVModel/index.ts
=> chore(useVModel): update docs

packages/shared/useIntervalFn/index.ts
unref `interval` since it may be a ref.
---
=> fix(useIntervalFn): unref interval

packages/core/useBrowserLocation/index.md
Docs read a little weird - so minor update on the useBrowserLocation note
=> docs(useBrowserLocation): improve the documentation

packages/guide/config.md
This PR fixes a typo in the documentation.
---
=> docs: fix a typo in the configurations guide

packages/shared/watchAtMost/index.ts, packages/shared/watchOnce/index.ts
=> chore(watchOnce&watchAtMost): fix typo of duplicated code

packages/core/useScroll/index.ts
close #1155
- fix compatibility for mobile
It can be reproduced on Android mobile terminals, such as WeChat webview.
---
=> fix(useScroll): compatibility for mobile

packages/core/useWakeLock/index.md
Minor documentation fix for usage section in useWakeLock()
---
=> docs(useWakeLock): typo

packages/shared/useIntervalFn/demo.vue
=> docs: update demo

packages/.vitepress/theme/components/FunctionInfo.vue
Add wrapping to "Related" and "Alias" rows of function info.
Before: 
After:
---
=> docs: add flex-wrap to "Alias" and "Related"

packages/core/useFetch/index.md
URL of suspense in vue docs has changed
---
=> docs: update url

packages/core/useMemory/index.ts
=> fix(useMemory)!: rename type `MemoryOptions` to `UseMemoryOptions`

packages/core/useTimeAgo/index.ts
=> feat(useTimeago): use computed ref

packages/core/useClipboard/index.ts, packages/core/useFavicon/index.ts, packages/core/useFileSystemAccess/index.ts, packages/core/usePointerSwipe/index.ts
feat:(useClipboard): use computed ref
feat(usePointerSwipe): use computed ref
feat(useFavicon): use computed ref
feat(useFileSystemAccess): use computed ref
=> feat(usePointerSwipe): use computed ref

packages/shared/useDateFormat/index.ts, packages/shared/useDebounceFn/index.ts
useDebounceFn --> use computed ref
---
=> feat(useDebounceFn): use computed ref

packages/core/useClipboard/index.ts
=> fix(useClipboard): fix type error

packages/shared/utils/types.ts
=> chore: correct type example

packages/shared/useDateFormat/index.ts
=> feat(useDateFormat): use computed ref

packages/core/usePointerSwipe/index.ts
=> fix(usePointerSwipe): fix error

packages/core/useFavicon/index.ts
=> fix(useFavicon): fix error

packages/core/useDraggable/component.ts
=> fix(useDraggable): fix error

packages/core/useTimeoutPoll/index.ts, packages/core/useVibrate/index.ts, packages/shared/useTimeoutFn/index.ts
=> feat: 3 hooks use computed ref

packages/core/useScroll/index.ts, packages/core/useScrollLock/index.ts, packages/core/useShare/index.ts, packages/core/useSpeechRecognition/index.ts, packages/core/useSpeechSynthesis/index.ts
`useScroll` `useScrollLock` `useShare` `useSpeechRecognition` and `useSpeechSynthesis` use computed ref
---
=> feat: five hooks use computed ref

packages/core/usePointer/demo.vue
=> chore(usePointer): remove unused code

packages/core/onKeyStroke/directive.test.ts, packages/core/onKeyStroke/directive.ts, packages/core/onKeyStroke/index.ts
=> fix(onKeyStroke)!: rename type `KeyStrokeOptions` to `OnKeyStrokeOptions`

packages/core/onClickOutside/directive.ts, packages/core/onClickOutside/index.ts
=> feat(onClickOutside): add `detectIframe` option

packages/core/useVModel/index.ts
enhance useVModel instance(in backward compatible manner)
Close #1745 
---
=> feat(useVModel): compact with 2.7, fix #1745

packages/contributors.ts
Adding description for team section, per https://github.com/vueuse/vueuse/issues/1808
=> docs(contributors): add harlan description

packages/math/useFloor/index.md, packages/math/useFloor/index.test.ts, packages/math/useFloor/index.ts
=> feat(useFloor): new function

packages/math/useRound/index.md, packages/math/useRound/index.test.ts, packages/math/useRound/index.ts
---
- [] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
=> feat(useRound): new function

packages/core/useMagicKeys/index.ts
=> fix(useMagicKeys): fix setting properties of undefined value

packages/integrations/useDrauu/index.md, packages/integrations/useDrauu/index.ts
- Add installation tips for the `drauu` library
- Import `useDrauu` by using tree shaking (to fix #1842)
---
=> docs(useDrauu): improve the documention

packages/core/useClipboard/index.ts
rename type `ClipboardOptions` to `UseClipboardOptions` and `ClipboardReturn` to `UseClipboardReturn`
---
=> fix(useClipboard)!: rename type `ClipboardOptions` to `UseClipboardOptions` and `ClipboardReturn` to `UseClipboardReturn`

packages/core/useMagicKeys/index.ts
rename type `MagicKeys` to `UseMagicKeysReturn`
---
=> fix(useMagicKeys)!: rename type `MagicKeys` to `UseMagicKeysReturn`

packages/core/useIdle/component.ts, packages/core/useIdle/index.ts
rename type `IdleOptions` to `UseIdleOptions`
---
=> fix(useIdle)!: rename type `IdleOptions` to `UseIdleOptions`

packages/core/useMouse/component.ts, packages/core/useMouse/index.ts, packages/core/useMouseInElement/index.ts
rename type `MouseOptions` to `UseMouseOptions`
---
=> fix(useMouse)!: rename type `MouseOptions` to `UseMouseOptions`

packages/core/useRafFn/index.ts
rename type `RafFnOptions` to `UseRafFnOptions`
---
=> fix(useRafFn)!: rename type `RafFnOptions` to `UseRafFnOptions`

packages/core/useSpeechRecognition/index.ts
rename type `SpeechRecognitionOptions` to `UseSpeechRecognitionOptions`
---
=> fix(useSpeechRecognition)!: rename type `SpeechRecognitionOptions` to `UseSpeechRecognitionOptions`

packages/core/useSpeechSynthesis/index.ts
rename type `SpeechSynthesisOptions` to `UseSpeechSynthesisOptions`
---
=> fix(useSpeechSynthesis)!: rename type `SpeechSynthesisOptions` to `UseSpeechSynthesisOptions`

packages/core/useTransition/index.ts
rename type `TransitionOptions` to `UseTransitionOptions`
---
=> fix(useTransition)!: rename type `TransitionOptions` to `UseTransitionOptions`

packages/core/useWindowSize/component.ts, packages/core/useWindowSize/index.ts
rename type `WindowSizeOptions` to `UseWindowSizeOptions`
---
=> fix(useWindowSize)!: rename type `WindowSizeOptions` to `UseWindowSizeOptions`

packages/core/useWebWorkerFn/index.ts
rename type `WebWorkerOptions` to `UseWebWorkerOptions`
---
=> fix(useWebWorkerFn)!: rename type `WebWorkerOptions` to `UseWebWorkerOptions`

packages/integrations/useJwt/index.ts
rename type `JwtOptions` to `UseJwtOptions` and `JwtResult` to `UseJwtReturn`
---
=> fix(useJwt)!: rename type `JwtOptions` to `UseJwtOptions` and `JwtResult` to `UseJwtReturn`

packages/firebase/useRTDB/index.ts
rename type `RTDBOptions` to `UseRTDBOptions`
---
=> fix(useRTDB)!: rename type `RTDBOptions` to `UseRTDBOptions`

packages/.vitepress/plugins/markdownTransform.ts
=> docs: fix demo link target attribute

packages/core/useSpeechSynthesis/demo.vue
Closes #1928
Related #1882
This is just fixing the demo for v8.
---
=> docs(useSpeechSynthesis): fix demo

packages/core/useObjectUrl/index.md
=> docs(useObjectUrl): fix example

packages/contributors.ts
=> docs(contributors): add description for wheat

packages/contributors.ts
Looks like my last PR caused some formatting issues on the homepage
---
=> docs(contributors): fix formatting

packages/core/useBluetooth/index.ts, packages/core/useBroadcastChannel/index.ts, packages/core/useCycleList/index.ts, packages/core/useDocumentVisibility/index.ts, packages/core/useDraggable/index.ts, packages/core/useEyeDropper/index.ts, packages/core/useGamepad/index.ts, packages/core/useImage/index.ts, packages/core/useMemory/index.ts, packages/core/useNetwork/index.ts, packages/core/usePointer/index.ts, packages/core/useTextareaAutosize/index.ts, packages/core/useThrottledRefHistory/index.ts, packages/core/useTimeAgo/index.ts, packages/core/useVirtualList/index.ts, packages/core/useWakeLock/index.ts, packages/core/useWebNotification/index.ts, packages/integrations/useNProgress/index.ts
=> types: improve

packages/shared/useInterval/index.ts
rename type `IntervalOptions` to `UseIntervalOptions`
---
=> fix(useInterval)!: rename type `IntervalOptions` to `UseIntervalOptions`

packages/core/useOffsetPagination/index.ts
Close #1942 
Seems caused by #1810.
---
=> fix(useOffsetPagination): incorrectly `currentPageSize` value

packages/.vitepress/theme/styles/main.css
=> docs: remove navbar transparency

packages/core/onClickOutside/index.ts
=> fix(onClickOutside): fix handler type

packages/core/useWebSocket/index.ts
=> fix(useWebSocket): set initial status as `CLOSED`

packages/core/onClickOutside/demo.vue
fix: https://github.com/vueuse/vueuse/issues/1963
---
=> docs: fix the demo of onClickOutside

packages/core/useScreenOrientation/index.md
useScreenOrientation docs use lockOrientation function params incorrect enum value
---
=> docs(useScreenOrientation): fix demo

packages/.vitepress/plugins/markdownTransform.ts, packages/electron/useIpcRenderer/index.md, packages/electron/useIpcRendererInvoke/index.md, packages/electron/useZoomLevel/index.md, packages/integrations/useAsyncValidator/index.md, packages/integrations/useAxios/index.md, packages/integrations/useChangeCase/index.md, packages/integrations/useDrauu/index.md, packages/integrations/useFocusTrap/index.md, packages/integrations/useJwt/index.md, packages/integrations/useNProgress/index.md, packages/integrations/useQRCode/index.md, packages/router/useRouteHash/index.md, packages/router/useRouteParams/index.md, packages/router/useRouteQuery/index.md, packages/rxjs/from/index.md, packages/rxjs/toObserver/index.md, packages/rxjs/useObservable/index.md, packages/rxjs/useSubject/index.md, packages/rxjs/useSubscription/index.md
Improve readability of some pages.
- add some missing punctuation on some pages
- add relevant links to RxJS concepts on RxJS-related pages
- fix missing capitalization at the start of some pages' summaries
---
=> docs: improve readability of some pages

packages/math/logicAnd/index.test.ts
Add tests for `logicAnd()`.
---
=> test(logicAnd): add tests

packages/core/useOffsetPagination/index.test.ts
Add tests for `useOffsetPagination()`.
---
=> test(useOffsetPagination): add tests

packages/math/logicAnd/index.test.ts, packages/math/logicNot/index.test.ts, packages/math/logicOr/index.test.ts, packages/math/useProjection/index.test.ts
test: implement some additional tests for math-related composables
---
=> test: implement some additional tests for math-related composables

packages/integrations/useNProgress/index.ts
=> fix(useNProgress): improve SSR support

packages/core/useTextDirection/demo.vue
remove unused function: `onUnmounted`
---
=> docs(useTextDirection): remove unused function

packages/shared/useArrayEvery/index.ts, packages/shared/useArrayFilter/index.ts, packages/shared/useArrayFind/index.ts, packages/shared/useArrayFindIndex/index.ts, packages/shared/useArrayJoin/index.ts, packages/shared/useArrayMap/index.ts, packages/shared/useArrayReduce/index.ts, packages/shared/useArraySome/index.ts
- Provide missing JSDoc for `useArray` utilities to improve DX
---
=> docs(useArray): improve JSDoc for `useArray` utilities

packages/core/useCycleList/index.ts
`MaybeRef` for `initialValue` (I did it to stop getting type error for the useColorMode demo)
---
=> feat(useCycleList): support MaybeRef for initialValue

packages/.vitepress/config.ts
In the current version of the docs functions under the math package don't show a sidebar
---
=> docs: fix sidebar in docs for math module

packages/ecosystem.md
Updates the image path of vue demi logo.
=> docs: Vue Demi logo image path

packages/ecosystem.md
Simplifies Vue Chemistry example
It was hard from the example to follow and understand what the library does. Calculation complexity was replaced with a simple addition taken from the example used in [Vue chemistry official docs](https://github.com/vueuse/vue-chemistry)
---
=> docs: simplifies Vue Chemistry example

packages/shared/useArrayMap/index.md
fix `useArrayMap` example code
---
=> docs(useArrayMap): fix example code

packages/shared/createGlobalState/index.md
`createGlobalState` add an example without persistence
---
=> docs(createGlobalState): add an example without persistence (#1991)

packages/core/useMemoize/index.test.ts, packages/core/useMemoize/index.ts
#closes #2062
---
- [] Ideally, include relevant tests that fail without this PR but pass with it.
=> fix(useMemoize): allow number in `getKey`

packages/integrations/useAxios/index.ts
=> fix(useAxios): reset error on `execute`

packages/core/computedAsync/index.ts, packages/core/onLongPress/index.ts
---
- [√] Other
- [√] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [√] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [√] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [√] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [√] Ideally, include relevant tests that fail without this PR but pass with it.
=> chore: improve types

packages/shared/until/index.md
replace "ready" with "isReady"
---
=> docs(until): fix outdated variable name

packages/shared/createGlobalState/index.md
Fix undefined return variable in bigger example of `createGlobalState`.
---
=> docs(createGlobalState): typo

packages/core/useFocusWithin/index.ts
=> fix(useFocusWithin): change focused typing to ComputedRef

packages/core/useUrlSearchParams/index.ts
fix [#2164](https://github.com/vueuse/vueuse/issues/2164)
---
=> feat(useUrlSearchParams): add `write` option

packages/core/useColorMode/index.ts, packages/core/useDark/index.ts, packages/core/useDevicesList/index.md, packages/core/useDevicesList/index.ts, packages/core/useNavigatorLanguage/index.ts, packages/core/useSpeechRecognition/index.ts, packages/core/useTimeAgo/index.ts, packages/integrations/useAxios/index.ts, packages/nuxt/index.ts, packages/shared/extendRef/index.ts, packages/shared/refWithControl/index.ts, packages/shared/toRefs/index.md, packages/shared/useArrayFind/index.test.ts, packages/shared/utils/types.ts, packages/shared/watchAtMost/index.ts, packages/shared/watchDebounced/index.ts, packages/shared/watchOnce/index.ts, packages/shared/watchPausable/index.ts, packages/shared/watchWithFilter/index.ts
just got a boring day, and did a thorough typo check.
---
=> chore: fix typo

packages/shared/useDateFormat/index.ts
=> docs(useDateFormat): update desc

packages/integrations/useAxios/index.ts
=> feat(useAxios): add second generic type to error

.gitignore, package.json
=> chore: add cache for  eslint

packages/core/useElementVisibility/index.test.ts, packages/core/useUrlSearchParams/index.test.ts, packages/shared/utils/index.test.ts, packages/shared/watchArray/index.test.ts, packages/shared/watchPausable/index.test.ts
All PRs from this branch intend to increase UT coverage and optimize vueuse source code. I will continuously commit test code to this branch. 
All commits in this branch are atomic, feel free to merge PR at any time.@antfu 
History PRs: 
- https://github.com/vueuse/vueuse/pull/2185
- https://github.com/vueuse/vueuse/pull/2233
|api|statements|branches|functions|lines
|-----|------|------|-----|-----|
|watchArray|100% ⬆️|100% ⬆️ |100%  |  100% ⬆️
|watchPausable|100% ⬆️|100%  |100%  ⬆️|  100% ⬆️
|utils/index|100% ⬆️|100% ⬆️   |100%  ⬆️|  100% ⬆️
|utils/is|100% ⬆️|100% ⬆️   |100%  ⬆️|  100% ⬆️
|useUrlSearchParams|100% ⬆️|100% ⬆️ |100%  |  100% ⬆️
|useElementVisibility|100% ⬆️|100% ⬆️ |100%  |  100% ⬆️
=> test: improve test coverage

packages/shared/useDebounceFn/index.md, packages/shared/useThrottleFn/index.md
=> doc(shared): correct addEventListener target

packages/.vitepress/plugins/utils.ts
文档中的 `y` 会被加上 `''`
see: https://vueuse.org/core/useMouse/#demo
解决方法是给 `YAML.dump` 函数添加 `noCompatMode: true` 选项
=> docs(useMouse): fix demo

packages/shared/refDebounced/index.ts
=> feat(refDebounced): use MaybeComputedRef for ms

packages/firebase/useFirestore/index.md
=> doc(useFirestore): fix overload type

packages/core/onClickOutside/index.ts
=> fix(onClickOutside): access correct `document`

packages/.vitepress/theme/components/Contributors.vue
=> chore: remove unused import

.github/workflows/ci.yml
=> ci: lint and test in node 18

packages/core/useClipboard/index.md
Adding a brief description for option `legacy` of `useClipboard` https://github.com/vueuse/vueuse/pull/2336#issuecomment-1290011451
---
=> docs(useClipboard): add brief of option legacy

packages/nuxt/package.json, playgrounds/nuxt3/package.json, pnpm-lock.yaml
Updates `@vueuse/nuxt` dependencies to use Nuxt 3 stable.
---
=> chore(nuxt): update dependencies to Nuxt 3 stable

packages/core/useBreakpoints/breakpoints.ts
This pull request will add some breakpoints from slightly popular css framework [Master CSS](https://github.com/master-co/css). And this is the [breakpoints reference](https://docs.master.co/css/breakpoints).
---
=> feat(useBreakpoints): add breakpoints for Master CSS

packages/core/onClickOutside/index.ts
> **Warning**
> Built on top of #2438. It should be merged before this PR.
---
=> feat(onClickOutside): allow selector strings for ignore list

packages/shared/createGlobalState/index.md
Closes #2570 Issue. Updated Documentation for createGlobalState. The initialValue value was never initialized
---
=> docs: fix demo #2570

packages/core/unrefElement/index.md
=> docs(unrefElement): fix example

packages/core/useMouse/index.ts
This PR implements additional type of mouse position tracking that is needed primarily for pointer locking and described [here](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API#extensions_to_mouse_events).
This is the part of implementation of functionality described in issue #2584.
=> feat(useMouse): support for movement detection

packages/core/onKeyStroke/index.ts
=> fix(onKeyStroke): make `target` ref nullable

packages/.vitepress/theme/components/Home.vue
Remove unnecessary import on `Home.vue`.
---
=> fix(docs): remove unnecessary import

packages/core/useElementByPoint/index.ts, packages/guide/config.md
closes #2604 
Along with a typo fix.
=> fix(useElementByPoint): make `document` configurable

packages/.vitepress/plugins/markdownTransform.ts, packages/shared/useTimeoutFn/index.md
https://vueuse.org/shared/reactifyObject/
Current:
Changed：
---
=> docs: Beautify function name display 

packages/shared/useArrayUnique/index.md, packages/shared/useArrayUnique/index.test.ts
=> docs(useArrayUnique): fix demo

packages/core/useSpeechRecognition/index.md
Link seems to have changed since this was first created.
---
- [na] Ideally, include relevant tests that fail without this PR but pass with it.
=> docs(useSpeechRecognition): Update caniuse link for speech recognition API

.vscode/settings.json, packages/core/useIdle/demo.vue, packages/core/useInfiniteScroll/index.md, packages/core/useWebWorkerFn/demo.vue, packages/core/useWebWorkerFn/lib/depsParser.ts, packages/integrations/useAsyncValidator/demo.client.vue
do some format stuff and fix typos by the way.
=> chore: update format, typo

packages/router/useRouteQuery/index.ts
=> fix: allow setting multiple route queries of useRouteQuery in same tick

packages/core/useAsyncState/index.test.ts
add test cases
useAsyncState
---
=> feat(useAsyncState): add test cases

packages/core/useWindowScroll/index.md, packages/core/useWindowScroll/index.ts
=> refactor(useWindowScroll): deprecate in favor of useScroll

packages/shared/createInjectionState/index.ts
Returns the `state` created in `useProvidingState`, fix #1997
---
=> feat(createInjectionState): return state when providing injection state

package.json, packages/integrations/package.json, packages/integrations/useAxios/index.test.ts, packages/integrations/useAxios/index.ts, pnpm-lock.yaml
Update axios to get compatible with axios 1.2.3 new type.
=> refactor(useAxios): update axios

packages/core/useElementSize/index.ts
Fixes https://github.com/vueuse/vueuse/issues/2519
---
=> fix(useElementSize): use contentBoxSize as an array in useElementSize

packages/core/useResizeObserver/index.md
There's an extra close parentheses in the 'Usage' code example.
---
=> docs: remove extra close parentheses.

packages/core/useStepper/demo.vue
Currently this example works incorrectly, my PR fixes it.
---
=> docs(useStepper): fix `stepper.isLast` usage in `demo.vue`

packages/core/useMouseInElement/index.ts
=> fix(useMouseInElement): check if mouse out of window

packages/core/useMagicKeys/demo.vue
Fix demo className typo 
useMagicKeys
---
=> docs(useMagicKeys): fix demo

packages/core/useDropZone/index.md
A small typo on https://vueuse.org/core/useDropZone/
n/a
---
=> docs(useDropZone): typo

package.json, pnpm-lock.yaml, scripts/post-docs.ts
Install `@types/remove-markdown` and fix ts error in `scripts/post-docs.ts`
---
=> chore: install `@types/remove-markdown`

packages/core/useStorageAsync/index.ts
=> fix(useStorageAsync): handle mergeDefaults option

packages/.vitepress/theme/styles/demo.css, packages/.vitepress/theme/styles/main.css, packages/core/useBase64/demo.vue, packages/core/useIntersectionObserver/demo.vue, packages/integrations/useNProgress/style.css
remove redundant css styles
---
=> docs: remove redundant css styles

packages/core/useFullscreen/demo.vue
=> docs(useFullscreen): remove useless code in demo

packages/.vitepress/config.ts
=> docs(useScreenSafeArea): fix the demo always `0px`

packages/shared/useInterval/index.md, packages/shared/useInterval/index.ts
reset the counter back to 0 in useInterval
---
=> feat(useInterval): add `reset` function

packages/integrations/useChangeCase/index.md
=> docs(useChangeCase): add substitute info for better search

packages/core/useElementHover/index.ts
=> fix(useElementHover): `window` is not defined

packages/core/usePointerSwipe/demo.vue
=> docs(usePointerSwipe): fix ts type error

packages/.vitepress/theme/components/Contributors.vue, packages/.vitepress/theme/components/DemoContainer.vue, packages/.vitepress/theme/components/FunctionBadge.vue, packages/.vitepress/theme/components/FunctionInfo.vue, packages/.vitepress/theme/components/TeamMember.vue
=> docs: fix ts error

packages/core/useManualRefHistory/index.ts
=> docs: updated docs

packages/core/useMousePressed/demo.vue
=> docs(useMousePressed): fix demo

packages/.vitepress/plugins/markdownTransform.ts
=> docs: optimize the regular in markdownTransform

packages/core/computedInject/index.md, packages/core/useBroadcastChannel/index.md, packages/core/useGamepad/index.md, packages/core/useMediaControls/index.md, packages/integrations/useChangeCase/index.md, packages/shared/createInjectionState/index.md, packages/shared/toRefs/index.md
=> docs: update docs

packages/core/useFetch/index.ts
=> fix(useFetch): abort before updating state

packages/.vitepress/plugins/markdownTransform.ts
=> docs: update the regex in markdownTransform

packages/shared/watchImmediate/index.ts
=> docs(watchImmediate): fix jsdoc

packages/core/useStorage/index.md
=> docs: fix broken link to nitro useStorage

packages/shared/createGlobalState/index.ts, packages/shared/createSharedComposable/index.ts, packages/shared/reactifyObject/index.ts, packages/shared/resolveUnref/index.ts, packages/shared/useTimeoutFn/index.ts
Some optimizations about TS types.
=> refactor: extract common `AnyFn` type

packages/shared/useArrayDifference/index.md
=> docs(useArrayDifference): fix typo

packages/shared/useArrayDifference/index.ts
=> fix(useArrayDifference): error with falsey

packages/core/useAsyncState/index.ts, packages/core/useBroadcastChannel/index.ts, packages/core/useEventSource/index.ts, packages/core/useGeolocation/index.ts
=> refactor: refactor `error` to use shallowRef

packages/core/useFileDialog/demo.vue, packages/core/useFileDialog/index.md, packages/core/useFileDialog/index.ts
=> feat(useFileDialog): add listener for file change events

packages/core/useColorMode/demo.vue
=> docs: fix useColorMode demo

packages/core/useTransition/index.test.ts, packages/core/useTransition/index.ts
=> feat(useTransition): support `MaybeComputedRef`

packages/shared/reactivePick/index.md, packages/shared/reactivePick/index.test.ts, packages/shared/reactivePick/index.ts
=> feat(reactivePick): add predicate parameter

packages/core/createReusableTemplate/index.md
=> docs(createReusableTemplate): update typo

packages/core/useEventListener/index.md
docs(useEventListener): improve documentation for usage with Nuxt 3
---
Updated with an additional usage example for Nuxt 3 / SSR / SSG ...
=> docs(useEventListener): add note for usage in SSR

packages/.vitepress/plugins/markdownTransform.ts, packages/.vitepress/theme/components/CodeToggle.vue, packages/shared/reactivePick/index.md
=> docs: toggle js blocks

packages/core/createReusableTemplate/index.md
=> docs(createReusableTemplate): grammar fix

packages/shared/utils/is.ts
=> feat(isIOS): detect new iPad

packages/core/useFetch/index.md
I found a small typo in the documentation, might as well fix it :)
=> Fix typo in useFetch documentation

packages/core/useDropZone/index.ts
fix:修复dragenter阶段event.dataTransfer!.types 类型错误的问题
=> fix(useDropZone): fix file types filter

packages/core/useScreenOrientation/index.ts
=> fix(useScreenOrientation): Add fault tolerance to lock and unlock

packages/contributors.json, packages/contributors.ts
=> chore(contributors): add contributors :D

.gitattributes, scripts/export-size.ts, scripts/utils.ts
=> chore: include `.gitattributes`

packages/core/useDraggable/demo.vue
=> docs: prefer using class in demo

packages/add-ons.md
Updating the description in addons for vueuse/sound
=> docs: fix old links

packages/shared/tryOnBeforeMount/index.ts, packages/shared/tryOnBeforeUnmount/index.ts, packages/shared/tryOnMounted/index.ts, packages/shared/tryOnUnmounted/index.ts, packages/shared/utils/index.ts
=> fix: fix `tryOnMounted` in vue2

packages/core/onClickOutside/index.ts
=> chore(onClickOutside): Fixed export type

packages/core/useStorageAsync/index.ts
=> fix(useStorageAsync): correct ssr handler

packages/core/useCloned/index.md
=> docs(useClone): correct the output

packages/core/useDraggable/index.ts
=> fix(useDraggable): can not work well when parent element is scrollable

packages/shared/useLastChanged/index.md
=> docs(useLastChanged): improve examples

packages/metadata/scripts/update.ts
=> docs: fix invalid description in functions page

packages/core/useNow/index.ts
Add time unit to doc string for clarity
=> docs: add update interval time unit

packages/shared/createInjectionState/index.ts
=> feat(createInjectionState): injectionKey use composable name

packages/core/useUserMedia/index.ts
=> fix(useUserMedia): stop stream on scope dispose

packages/core/useCycleList/index.md, packages/core/useCycleList/index.test.ts, packages/core/useCycleList/index.ts
=> feat(useCycleList): add `go` function

packages/shared/createInjectionState/index.md
=> docs: fix createInjectionState example

packages/core/useCloned/index.ts
=> fix(useCloned): correct return type

packages/core/useStorage/index.ts
=> refactor(useStorage): minor cleanup

packages/shared/whenever/index.test.ts, packages/shared/whenever/index.ts
=> feat(whenever): override once option

packages/core/onLongPress/index.md
=> docs(onLongPress): fix demo

packages/core/useTextDirection/index.md
=> fixed typo in docs for useTextDirection

packages/shared/watchDeep/index.md, packages/shared/watchImmediate/index.md
…example
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly …
=> docs(watchDeep,watchImmediate): modify the correct reference for the example

packages/core/useMutationObserver/index.ts
=> refactor(useMutationObserver): refactor remove duplicated conditional statements

packages/core/useDraggable/index.ts
=> fix(useDraggable): should ignore right clicks

packages/nuxt/README.md
=> docs: add `@vueuse/core` to Nuxt module installation instructions

packages/core/useDevicePixelRatio/index.md
=> Link to non-language specific mozilla docs

.github/FUNDING.yml
=> chore: add vueuse open collective

packages/guide/index.md
replace redirect link address with official website url
=> docs: change composition api hyperlink

packages/core/useBreakpoints/index.md
Add import note to breakpoints
https://github.com/vueuse/vueuse/issues/3790
=> docs(useBreakpoints): list presets

packages/shared/makeDestructurable/index.md, packages/shared/makeDestructurable/index.ts
=> refactor(makeDestructurable): use const type parameters

packages/core/useWebNotification/index.ts
=> fix(useWebNotification): catch `TypeError`

packages/core/useColorMode/demo.vue
=> refactor(useColorMode): Update demo.vue - better type

packages/core/useAnimate/index.ts
=> fix(useAnimate): `commitStyles` when finish

packages/shared/refWithControl/index.ts, packages/shared/useToNumber/index.ts
=> docs(refWithControl): typo

packages/core/useMediaControls/index.ts
=> fix(useMediaControls): target params may not be ref

packages/core/useActiveElement/index.test.ts, packages/core/useActiveElement/index.ts
=> feat(useActiveElement): add `triggerOnRemoval` option

packages/core/useFocus/index.ts
added preventScroll option for useFocus
fixes: [#3986](https://github.com/vueuse/vueuse/issues/3986)
=> feat(useFocus): support `preventScroll` option

packages/integrations/useNProgress/index.md
- [] Ideally, include relevant tests that fail without this PR but pass with it.
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on …
=> docs(useNProgress): fix dead link

CONTRIBUTING.md
=> docs: update @vueuse/integrations link

packages/core/createTemplatePromise/index.md, packages/shared/toRefs/index.md
replace redirect link address with official website url
=> docs: update API hyperlinks

packages/integrations/useCookies/index.md
=> docs(useCookies): Bump useCookies major version in docs

meta/ecosystem-functions.ts
=> docs(@Motion): fix redirect @vueuse/motion cause 404

packages/core/useInfiniteScroll/demo.vue, packages/core/useInfiniteScroll/index.md, packages/core/useInfiniteScroll/index.ts
=> feat(useInfiniteScroll): add a reset method

packages/core/usePermission/index.ts
=> fix(usePermission): fix memory leak

packages/core/templateRef/index.ts
=> feat(templateRef): support specifying allowed keys via generic argument

packages/core/useIntersectionObserver/index.ts
=> fix(useIntersectionObserver): add `Document` type for root

packages/core/onKeyStroke/demo.vue
=> docs(onKeyStroke): fix arrow down & up cause scroll event

packages/core/useDraggable/component.ts
=> fix(useDraggable): draggable component not work with container

packages/core/useFileDialog/demo.vue, packages/core/useFileDialog/index.md, packages/core/useFileDialog/index.ts
=> feat(useFileDialog): return `onCancel` handler

packages/core/onClickOutside/index.ts
=> fix(onClickOutside): improve cross-browser compatibility

packages/core/useShare/index.md
=> fix: typo in `useShare` docs

packages/core/useResizeObserver/index.ts
=> fix(useResizeObserver): update type

packages/core/useNetwork/index.ts
=> fix(useNetwork): return immutable values

packages/core/useInfiniteScroll/index.ts
=> fix(useInfiniteScroll): stop watch when unmounted

packages/integrations/useSortable/index.md
Fix typo
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly …
=> docs(useSortable): fix typo

packages/core/useManualRefHistory/index.ts
=> fix(useManualRefHistory): `canUndo` and `canRedo` typing to be computed ref

packages/shared/useArrayReduce/index.test.ts, packages/shared/useArrayReduce/index.ts
=> fix(useArrayReduce): initialValue can be a function

packages/shared/useIntervalFn/index.test.ts, packages/shared/useIntervalFn/index.ts
=> fix(useIntervalFn): prevent timer being set after pause is called in cb

packages/core/useWebSocket/index.ts
fixes #4310, fixes #4181 
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their …
=> fix(useWebSocket): autoreconnect when ws close

packages/core/useVirtualList/index.md
=> docs(useVirtualList): add props.index for quick understanding

packages/core/useUrlSearchParams/index.ts
=> fix(useUrlSearchParams): `hash` mode missing `location.search`

packages/guide/index.md, packages/nuxt/README.md
=> docs: add description to install vueuse using nuxi for nuxt

packages/core/useUserMedia/demo.vue, packages/core/useUserMedia/index.md
fix #3414 #4321 
<details>
<br>
> …
=> docs(useUserMedia): fix examples

packages/router/_types.ts, packages/router/useRouteParams/index.test.ts, packages/router/useRouteParams/index.ts, packages/router/useRouteQuery/index.test.ts, packages/router/useRouteQuery/index.ts
=> feat(router): transform get / set

README.md, packages/guide/index.md
Fix version number typo from https://github.com/vueuse/vueuse/pull/4349
=> Documentation: Fix version typo for vue2

packages/core/useUserMedia/demo.vue
=> docs(useUserMedia): fix demo.vue reactive import

packages/shared/watchWithFilter/index.md
=> fix: typo on `watchWithFilter` docs

packages/core/useVModel/index.md
---
- fixes #4209
Make sure that `useVModel` has some use-cases and is here to stay
=> docs(useVModel): add hint to defineModel

packages/shared/watchIgnorable/index.md
=> docs(watchIgnorable): update author link of recommended reading

packages/contributors.json, packages/contributors.ts, scripts/utils.ts
=> docs: add team and contributor info

packages/core/useBase64/index.ts
reference #4311 
<details>
<br>
> …
=> feat(useBase64): add options for Data URL output control

packages/core/useColorMode/index.test.ts, packages/core/useMediaQuery/index.ts
=> fix(useMediaQuery): the return value should be computed

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: fix issue template title convention escaping

packages/core/useClipboardItems/index.md
=> docs(useClipboardItems): display current copied value with content

packages/shared/createEventHook/index.test.ts, packages/shared/createEventHook/index.ts
resolve: #4375 
<details>
<br>
> …
=> feat(createEventHook): add `clear` function

packages/core/useDevicesList/index.md
=> docs(useDevicesList): add permissions request example

packages/core/useWindowSize/index.ts
=> feat(useWindowSize): add `type: visual` option that leverage `visualViewport`

packages/core/useUrlSearchParams/index.test.ts, packages/core/useUrlSearchParams/index.ts
Resolve [#4389](https://github.com/vueuse/vueuse/issues/4389)
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your …
=> feat(useUrlSearchParams): add `writeMode` options

packages/core/onKeyStroke/demo.vue
=> docs(onKeyStroke): demo from preventing w and s keypress in global search.

packages/core/useMediaControls/index.ts
Adding media option to sources. This specifies the media query for the resource's intended media.
=> feat(useMediaControls): add 'media' option to define media query for resources

packages/core/computedAsync/index.test.ts, packages/core/onLongPress/index.test.ts, packages/core/useConfirmDialog/index.test.ts, packages/core/useCssVar/index.test.ts, packages/core/useDebouncedRefHistory/index.test.ts, packages/core/useFetch/index.test.ts, packages/core/useMutationObserver/index.test.ts, packages/core/useNow/index.test.ts, packages/core/useStorage/index.test.ts, packages/core/useThrottledRefHistory/index.test.ts, packages/core/useTimeAgo/index.test.ts, packages/core/useTimeoutPoll/index.test.ts, packages/core/useTimestamp/index.test.ts, packages/core/useWakeLock/index.test.ts, packages/integrations/useAxios/index.test.ts, packages/integrations/useIDBKeyval/index.test.ts, packages/rxjs/useExtractedObservable/index.test.ts, packages/rxjs/watchExtractedObservable/index.test.ts, packages/shared/createEventHook/index.test.ts, packages/shared/refAutoReset/index.test.ts, packages/shared/until/index.test.ts, packages/shared/useIntervalFn/index.test.ts, packages/shared/useThrottleFn/index.test.ts, packages/shared/useTimeout/index.test.ts, packages/shared/useTimeoutFn/index.test.ts, packages/shared/watchDebounced/index.test.ts, packages/shared/watchThrottled/index.test.ts
=> test: replace timeouts with fake timers

packages/integrations/useSortable/index.md
related to https://github.com/vueuse/vueuse/issues/3647#issuecomment-2227462571
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them …
=> docs(useSortable): add restriction warning

packages/core/useMousePressed/index.ts
=> feat(useMousePressed): add `onPressed` and `onReleased` as options

packages/core/useScroll/index.test.ts, packages/core/useScroll/index.ts, packages/core/useWindowScroll/demo.vue, packages/core/useWindowScroll/index.test.ts, packages/core/useWindowScroll/index.ts
=> feat(useWindowScroll): use `useScroll` under the hood

packages/core/useElementBounding/index.browser.test.ts, packages/core/useElementBounding/index.test.ts, tsconfig.json, vitest.workspace.ts
=> test(useElementBounding): add basic browser tests

packages/core/useStorageAsync/index.ts
=> fix(useStorageAsync): correct initialization when `initialValue` is getter

packages/shared/useToNumber/index.test.ts, packages/shared/useToNumber/index.ts
=> feat(useToNumber): `method` support custom function

package.json, packages/.vitepress/theme/components/Changelog.vue, packages/.vitepress/theme/components/ReloadPrompt.vue, packages/core/useAsyncState/demo.vue, packages/core/useAsyncState/index.ts, packages/core/useCssVar/index.ts, packages/core/useFetch/demo.vue, packages/core/useGamepad/components/Gamepad.vue, packages/core/useMouse/demo.vue, packages/core/useParallax/demo.vue, packages/core/usePointerLock/demo.vue, packages/integrations/useNProgress/index.ts, packages/shared/useDateFormat/demo.vue, pnpm-lock.yaml, pnpm-workspace.yaml, tsconfig.json
=> test: use `vue-tsc` instead of `tsc` to also check `*.vue` files

packages/integrations/useCookies/index.test.ts
I added this test to my project, but I guess it would be better to add it directly to `vueuse`.
Let me know if I can improve it.
=> test(useCookies): add unit test

packages/core/useTitle/index.md, packages/core/useTitle/index.ts, packages/nuxt/index.ts
=> docs(useTitle): update tip for auto import in Nuxt 3

packages/.vitepress/theme/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> docs: update VitePress to 1.6.1

packages/core/useMagicKeys/index.test.ts, packages/core/useMagicKeys/index.ts
=> fix(useMagicKeys): fix key order issue on first use

packages/core/useClipboardItems/demo.vue, packages/core/useClipboardItems/index.md
fixes https://github.com/vueuse/vueuse/issues/4461
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and …
=> docs(useClipboardItems): fix demo by using `text/plain` mime type 

pnpm-lock.yaml, pnpm-workspace.yaml
=> docs: update VitePress to 1.6.3 (search broken)

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: update issue templates to support githubs new issue types

pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: downgrade playwright to prevent flaky FF tests

packages/core/onClickOutside/index.browser.test.ts
=> test(onClickOutside): browser tests for ignored elements

packages/core/onClickOutside/component.ts, packages/core/onClickOutside/directive.ts, packages/core/onClickOutside/index.md, packages/core/onClickOutside/index.ts
=> feat(onClickOutside): add `controls`

packages/core/useAnimate/index.ts
=> fix(useAnimate): Clear animate when element is gone

README.md
=> docs: update README.md usage example to script setup

packages/core/useAnimate/index.ts
=> fix(useAnimate): Correct condition for updating keyframes

pnpm-lock.yaml, pnpm-workspace.yaml
Upgrades vitest to latest version (comes with some performance gains).
=> chore: upgrade vitest to 3.0.7

packages/core/useEventSource/index.test.ts
Adds a test suite for `useEventSource`
Depends on #4598
=> test(useEventSource): add initial tests

packages/core/createReusableTemplate/index.md, packages/core/useDeviceMotion/index.md, packages/core/useDeviceOrientation/index.md, packages/integrations/useFocusTrap/index.md
=> docs: set right the links

packages/core/useEventSource/index.ts
=> fix(useEventSource): remove readonly to not be breaking

.github/workflows/ci.yml, attw-esm-only.json, package.json, packages/components/package.json, packages/core/package.json, packages/electron/package.json, packages/firebase/package.json, packages/integrations/package.json, packages/math/package.json, packages/metadata/package.json, packages/nuxt/package.json, packages/router/package.json, packages/rxjs/package.json, packages/shared/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> test(ci): add additional attw test for built packages

packages/shared/refAutoReset/index.md
=> docs(refAutoReset): add info about using `triggerRef` for deep mutations

packages/.vitepress/theme/components/Changelog.vue, packages/.vitepress/theme/components/ChangelogEntry.vue
=> docs(changelog): fix date hydration mismatch

.github/ISSUE_TEMPLATE/bug_report.yml
=> chore: recommend opening a reproduction via playground.vueuse.org

packages/core/usePointerSwipe/index.ts
fix #4637
This PR changes the [touch-action ](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)value set within tryOnMounted from none to pan-y. 
This allows vertical panning (scrolling) gestures, preventing the blockage of native scroll behavior. Horizontal swipe detection continues to function as expected.
<details>
<br>
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and …
=> fix: allow vertical scroll in usePointerSwipe (#4637)

packages/core/useElementSize/component.ts
=> fix(useElementSize): component type warning

packages/core/useEventSource/index.ts
=> fix(useEventSource): add missing data generic

packages/core/createTemplatePromise/index.md, packages/core/useCurrentElement/index.md, packages/core/useCurrentElement/index.test.ts, packages/core/useTemplateRefsList/index.md, packages/index.md, packages/router/README.md, packages/shared/refWithControl/index.md
=> docs: remove vue 3 only warnings

packages/core/useFullscreen/index.ts
=> fix(useFullscreen): get the correct initial state while mounted

packages/core/useFetch/index.ts
=> fix(useFetch): use `globalThis.fetch` when `defaultWindow.fetch` not exist

packages/core/useScreenSafeArea/index.ts
=> fix(useScreenSafeArea): сhanged initial value update

packages/core/useElementVisibility/index.md
=> docs(useElementVisibility): explain threshold option

packages/core/useEventSource/index.ts
=> feat(useEventSource): added lastEventId for named events

packages/shared/computedWithControl/index.ts
=> perf(computedWithControl): Optimize with shallowRef

packages/shared/computedWithControl/index.md, packages/shared/computedWithControl/index.test.ts, packages/shared/computedWithControl/index.ts
=> fix(computedWithControl): allow deeply watching source

packages/.test/mount.ts
=> fix: render Comp to trigger its setup

packages/core/useSpeechSynthesis/demo.vue, packages/core/useSpeechSynthesis/index.ts
=> feat(useSpeechSynthesis): add reactivity for volume

packages/core/onClickOutside/index.md, packages/core/onClickOutside/index.ts
=> docs: onClickOutside ignore by CSS Selectors

packages/integrations/package.json
=> fix(useCookie): update `universal-cookie` range to `^7 || ^8`

packages/core/useActiveElement/index.md, packages/core/useDocumentVisibility/index.md, packages/core/useDropZone/index.md, packages/core/useMutationObserver/index.md, packages/core/useParentElement/index.md, packages/core/useResizeObserver/index.md, packages/core/useWindowFocus/index.md, packages/core/useWindowScroll/index.md, packages/core/useWindowSize/index.md
The style should be unified as follows:
```
```vue
</script>
```
=> docs(Elements): format the doc's Usage section

packages/core/useAsyncState/index.md
=> docs(useAsyncState): fix usage example

.vscode/extensions.json
=> chore: update VSCode extensions recommendations

package.json
This PR adds a new `up` script that combines dependency updates using `taze` with size checking.
=> chore: add new script for updating dependencies and checking size

packages/.test/setup.ts, packages/core/useFetch/index.test.ts
This PR adds the MSW mock server to the test setup.
=> refactor(test): add MSW mock server to setup

tsconfig.json
=> types: add `@vueuse/integrations/*` paths

packages/core/computedAsync/index.test.ts, packages/core/computedAsync/index.ts
=> feat(computedAsync): use globalThis.reportError as default onError

packages/core/useMagicKeys/index.test.ts
=> test(useMagicKeys): add tests

.vscode/launch.json, packages/.vitepress/vite.config.ts
=> chore: add breakpoint debugging config for VS Code

packages/rxjs/useExtractedObservable/index.ts, packages/rxjs/watchExtractedObservable/index.ts, packages/shared/watchDeep/index.ts, packages/shared/watchImmediate/index.ts, packages/shared/watchOnce/index.ts
=> fix(types): update type casting for watch functions to use WatchSource<T>

packages/core/useFetch/index.md
=> docs(useFetch): correct spelling error in useFetch documentation

packages/core/computedAsync/index.ts, packages/core/onClickOutside/directive.ts, packages/core/onLongPress/directive.ts, packages/math/logicAnd/index.ts, packages/math/logicNot/index.ts, packages/math/logicOr/index.ts, packages/shared/computedEager/index.ts, packages/shared/computedWithControl/index.ts, packages/shared/reactify/index.ts, packages/shared/refAutoReset/index.ts, packages/shared/refDebounced/index.ts, packages/shared/refThrottled/index.ts, packages/shared/refWithControl/index.ts, packages/shared/watchDebounced/index.ts, packages/shared/watchIgnorable/index.ts, packages/shared/watchPausable/index.ts, packages/shared/watchThrottled/index.ts
=> feat!: deprecate alias exports in favor of original function names

packages/shared/watchAtMost/index.ts, packages/shared/watchWithFilter/index.ts
=> feat(watchAtMost): add pause and resume to return value 

.github/workflows/ci.yml, package.json, packages/shared/createSharedComposable/index.md, packages/shared/createSharedComposable/index.server.test.ts, packages/shared/createSharedComposable/index.test.ts, packages/shared/createSharedComposable/index.ts, packages/shared/utils/index.server.test.ts, vitest.config.ts
=> feat(createSharedComposable)!: return only the sharedComposable on client side

packages/core/useShare/index.ts
=> fix(useShare): improve the accuracy of sharing logic

packages/core/useAsyncState/index.test.ts, packages/core/useAsyncState/index.ts
=> fix(useAsyncState): track latest execution to avoid newer results being replaced by outdated ones

packages/core/createTemplatePromise/index.test.ts
=> chore(createTemplatePromise): add basic usage test case
